/**
 * CSS Levels for CodeQuest
 * Theme: Artist / Creative Studio
 */

const cssLevels = [
    // ===== Module 1: Basics =====
    {
        id: 'css-01',
        module: 'Основы CSS',
        title: 'Цвет текста',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Свойство color задаёт цвет текста. Можно использовать названия цветов или коды.',
        task: 'Сделай текст красным',
        hint: 'Используй свойство color со значением red',
        template: 'p {\n  ___: red;\n}',
        blanks: ['color'],
        expected: 'p {\n  color: red;\n}',
        xp: 10,
        visual: { type: 'text', property: 'color' }
    },
    {
        id: 'css-02',
        module: 'Основы CSS',
        title: 'Цвет фона',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Свойство background-color задаёт цвет фона элемента.',
        task: 'Установи синий фон',
        hint: 'Используй background-color',
        template: 'div {\n  ___: blue;\n}',
        blanks: ['background-color'],
        expected: 'div {\n  background-color: blue;\n}',
        xp: 10,
        visual: { type: 'box', property: 'background-color' }
    },
    {
        id: 'css-03',
        module: 'Основы CSS',
        title: 'Селектор класса',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Классы в CSS обозначаются точкой перед именем. Например: .myclass',
        task: 'Создай стиль для класса "highlight"',
        hint: 'Класс начинается с точки',
        template: '___highlight {\n  background-color: yellow;\n}',
        blanks: ['.'],
        expected: '.highlight {\n  background-color: yellow;\n}',
        xp: 10
    },
    {
        id: 'css-04',
        module: 'Основы CSS',
        title: 'Селектор ID',
        difficulty: 1,
        type: 'fill-blank',
        description: 'ID в CSS обозначается символом # перед именем. ID уникален для страницы.',
        task: 'Создай стиль для элемента с id="header"',
        hint: 'ID начинается с #',
        template: '___header {\n  background-color: navy;\n}',
        blanks: ['#'],
        expected: '#header {\n  background-color: navy;\n}',
        xp: 10
    },
    {
        id: 'css-05',
        module: 'Основы CSS',
        title: 'HEX цвета',
        difficulty: 2,
        type: 'fill-blank',
        description: 'HEX-коды цветов начинаются с # и содержат 6 символов. #ff0000 - красный.',
        task: 'Установи чисто красный цвет в HEX формате',
        hint: 'Красный в HEX: #ff0000',
        template: 'p {\n  color: ___;\n}',
        blanks: ['#ff0000'],
        expected: 'p {\n  color: #ff0000;\n}',
        xp: 15
    },
    {
        id: 'css-06',
        module: 'Основы CSS',
        title: 'RGB цвета',
        difficulty: 2,
        type: 'fill-blank',
        description: 'RGB задаёт цвет через значения красного, зелёного и синего (0-255).',
        task: 'Создай чистый зелёный цвет в RGB',
        hint: 'Зелёный: rgb(0, 255, 0)',
        template: 'p {\n  color: rgb(___, 255, ___);\n}',
        blanks: ['0', '0'],
        expected: 'p {\n  color: rgb(0, 255, 0);\n}',
        xp: 15
    },
    {
        id: 'css-07',
        module: 'Основы CSS',
        title: 'Единицы измерения',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Пиксели (px) - абсолютные единицы. 16px = стандартный размер текста.',
        task: 'Установи размер шрифта 20 пикселей',
        hint: 'Используй единицу px',
        template: 'p {\n  font-size: 20___;\n}',
        blanks: ['px'],
        expected: 'p {\n  font-size: 20px;\n}',
        xp: 10
    },
    {
        id: 'css-08',
        module: 'Основы CSS',
        title: 'Единицы em',
        difficulty: 2,
        type: 'fill-blank',
        description: 'em - относительная единица, равная текущему размеру шрифта. 1.5em = 150% от родителя.',
        task: 'Установи размер в полтора раза больше родительского',
        hint: 'Используй 1.5em',
        template: 'p {\n  font-size: ___;\n}',
        blanks: ['1.5em'],
        expected: 'p {\n  font-size: 1.5em;\n}',
        xp: 15
    },

    // ===== Module 2: Text & Fonts =====
    {
        id: 'css-09',
        module: 'Текст и шрифты',
        title: 'Семейство шрифтов',
        difficulty: 1,
        type: 'fill-blank',
        description: 'font-family задаёт шрифт текста. Можно указать несколько через запятую.',
        task: 'Установи шрифт Arial',
        hint: 'Используй font-family',
        template: 'body {\n  ___: Arial, sans-serif;\n}',
        blanks: ['font-family'],
        expected: 'body {\n  font-family: Arial, sans-serif;\n}',
        xp: 10
    },
    {
        id: 'css-10',
        module: 'Текст и шрифты',
        title: 'Размер шрифта',
        difficulty: 1,
        type: 'fill-blank',
        description: 'font-size задаёт размер шрифта.',
        task: 'Установи размер шрифта 18px',
        hint: 'Используй font-size',
        template: 'p {\n  ___: 18px;\n}',
        blanks: ['font-size'],
        expected: 'p {\n  font-size: 18px;\n}',
        xp: 10
    },
    {
        id: 'css-11',
        module: 'Текст и шрифты',
        title: 'Жирность шрифта',
        difficulty: 1,
        type: 'fill-blank',
        description: 'font-weight задаёт толщину шрифта. bold - жирный, normal - обычный.',
        task: 'Сделай текст жирным',
        hint: 'font-weight: bold',
        template: 'h1 {\n  font-weight: ___;\n}',
        blanks: ['bold'],
        expected: 'h1 {\n  font-weight: bold;\n}',
        xp: 10
    },
    {
        id: 'css-12',
        module: 'Текст и шрифты',
        title: 'Курсивный текст',
        difficulty: 1,
        type: 'fill-blank',
        description: 'font-style: italic делает текст курсивным.',
        task: 'Сделай текст курсивным',
        hint: 'font-style: italic',
        template: 'em {\n  font-style: ___;\n}',
        blanks: ['italic'],
        expected: 'em {\n  font-style: italic;\n}',
        xp: 10
    },
    {
        id: 'css-13',
        module: 'Текст и шрифты',
        title: 'Выравнивание текста',
        difficulty: 1,
        type: 'fill-blank',
        description: 'text-align выравнивает текст: left, center, right, justify.',
        task: 'Выровняй текст по центру',
        hint: 'text-align: center',
        template: 'h1 {\n  text-align: ___;\n}',
        blanks: ['center'],
        expected: 'h1 {\n  text-align: center;\n}',
        xp: 10
    },
    {
        id: 'css-14',
        module: 'Текст и шрифты',
        title: 'Подчёркивание',
        difficulty: 1,
        type: 'fill-blank',
        description: 'text-decoration управляет линиями: underline, line-through, none.',
        task: 'Убери подчёркивание у ссылок',
        hint: 'text-decoration: none',
        template: 'a {\n  text-decoration: ___;\n}',
        blanks: ['none'],
        expected: 'a {\n  text-decoration: none;\n}',
        xp: 10
    },
    {
        id: 'css-15',
        module: 'Текст и шрифты',
        title: 'Межстрочный интервал',
        difficulty: 2,
        type: 'fill-blank',
        description: 'line-height задаёт высоту строки. 1.5 = полуторный интервал.',
        task: 'Установи полуторный межстрочный интервал',
        hint: 'line-height: 1.5',
        template: 'p {\n  line-height: ___;\n}',
        blanks: ['1.5'],
        expected: 'p {\n  line-height: 1.5;\n}',
        xp: 15
    },

    // ===== Module 3: Box Model =====
    {
        id: 'css-16',
        module: 'Блочная модель',
        title: 'Ширина',
        difficulty: 1,
        type: 'fill-blank',
        description: 'width задаёт ширину элемента.',
        task: 'Установи ширину 300 пикселей',
        hint: 'width: 300px',
        template: 'div {\n  ___: 300px;\n}',
        blanks: ['width'],
        expected: 'div {\n  width: 300px;\n}',
        xp: 10
    },
    {
        id: 'css-17',
        module: 'Блочная модель',
        title: 'Высота',
        difficulty: 1,
        type: 'fill-blank',
        description: 'height задаёт высоту элемента.',
        task: 'Установи высоту 200 пикселей',
        hint: 'height: 200px',
        template: 'div {\n  ___: 200px;\n}',
        blanks: ['height'],
        expected: 'div {\n  height: 200px;\n}',
        xp: 10
    },
    {
        id: 'css-18',
        module: 'Блочная модель',
        title: 'Внутренний отступ',
        difficulty: 1,
        type: 'fill-blank',
        description: 'padding - внутренний отступ от границы до контента.',
        task: 'Добавь внутренний отступ 20 пикселей',
        hint: 'padding: 20px',
        template: 'div {\n  ___: 20px;\n}',
        blanks: ['padding'],
        expected: 'div {\n  padding: 20px;\n}',
        xp: 10
    },
    {
        id: 'css-19',
        module: 'Блочная модель',
        title: 'Внешний отступ',
        difficulty: 1,
        type: 'fill-blank',
        description: 'margin - внешний отступ от элемента до соседних.',
        task: 'Добавь внешний отступ 10 пикселей',
        hint: 'margin: 10px',
        template: 'div {\n  ___: 10px;\n}',
        blanks: ['margin'],
        expected: 'div {\n  margin: 10px;\n}',
        xp: 10
    },
    {
        id: 'css-20',
        module: 'Блочная модель',
        title: 'Граница',
        difficulty: 2,
        type: 'fill-blank',
        description: 'border: ширина стиль цвет. Например: 1px solid black',
        task: 'Добавь сплошную чёрную границу 2px',
        hint: 'border: 2px solid black',
        template: 'div {\n  border: 2px ___ black;\n}',
        blanks: ['solid'],
        expected: 'div {\n  border: 2px solid black;\n}',
        xp: 15
    },
    {
        id: 'css-21',
        module: 'Блочная модель',
        title: 'Скругление углов',
        difficulty: 2,
        type: 'fill-blank',
        description: 'border-radius скругляет углы элемента.',
        task: 'Скругли углы на 10 пикселей',
        hint: 'border-radius: 10px',
        template: 'div {\n  ___: 10px;\n}',
        blanks: ['border-radius'],
        expected: 'div {\n  border-radius: 10px;\n}',
        xp: 15
    },
    {
        id: 'css-22',
        module: 'Блочная модель',
        title: 'Круг',
        difficulty: 2,
        type: 'fill-blank',
        description: '50% border-radius превращает квадрат в круг.',
        task: 'Сделай элемент круглым',
        hint: 'border-radius: 50%',
        template: 'div {\n  width: 100px;\n  height: 100px;\n  border-radius: ___;\n}',
        blanks: ['50%'],
        expected: 'div {\n  width: 100px;\n  height: 100px;\n  border-radius: 50%;\n}',
        xp: 15
    },

    // ===== Module 4: Positioning =====
    {
        id: 'css-23',
        module: 'Позиционирование',
        title: 'Display block',
        difficulty: 2,
        type: 'fill-blank',
        description: 'display: block делает элемент блочным (занимает всю ширину).',
        task: 'Сделай span блочным элементом',
        hint: 'display: block',
        template: 'span {\n  display: ___;\n}',
        blanks: ['block'],
        expected: 'span {\n  display: block;\n}',
        xp: 15
    },
    {
        id: 'css-24',
        module: 'Позиционирование',
        title: 'Display inline',
        difficulty: 2,
        type: 'fill-blank',
        description: 'display: inline делает элемент строчным (в одной строке с текстом).',
        task: 'Сделай div строчным элементом',
        hint: 'display: inline',
        template: 'div {\n  display: ___;\n}',
        blanks: ['inline'],
        expected: 'div {\n  display: inline;\n}',
        xp: 15
    },
    {
        id: 'css-25',
        module: 'Позиционирование',
        title: 'Position relative',
        difficulty: 2,
        type: 'fill-blank',
        description: 'position: relative позволяет сдвигать элемент относительно его обычного места.',
        task: 'Установи относительное позиционирование',
        hint: 'position: relative',
        template: 'div {\n  position: ___;\n}',
        blanks: ['relative'],
        expected: 'div {\n  position: relative;\n}',
        xp: 15
    },
    {
        id: 'css-26',
        module: 'Позиционирование',
        title: 'Position absolute',
        difficulty: 2,
        type: 'fill-blank',
        description: 'position: absolute вырывает элемент из потока и позиционирует относительно родителя.',
        task: 'Установи абсолютное позиционирование',
        hint: 'position: absolute',
        template: 'div {\n  position: ___;\n  top: 0;\n  left: 0;\n}',
        blanks: ['absolute'],
        expected: 'div {\n  position: absolute;\n  top: 0;\n  left: 0;\n}',
        xp: 15
    },
    {
        id: 'css-27',
        module: 'Позиционирование',
        title: 'Position fixed',
        difficulty: 2,
        type: 'fill-blank',
        description: 'position: fixed фиксирует элемент относительно окна браузера.',
        task: 'Зафиксируй элемент в правом верхнем углу',
        hint: 'position: fixed с top и right',
        template: 'div {\n  position: ___;\n  top: 0;\n  right: 0;\n}',
        blanks: ['fixed'],
        expected: 'div {\n  position: fixed;\n  top: 0;\n  right: 0;\n}',
        xp: 15
    },
    {
        id: 'css-28',
        module: 'Позиционирование',
        title: 'Z-index',
        difficulty: 2,
        type: 'fill-blank',
        description: 'z-index управляет порядком наложения элементов. Больше число - выше слой.',
        task: 'Помести элемент поверх других (z-index: 10)',
        hint: 'z-index: 10',
        template: 'div {\n  position: relative;\n  ___: 10;\n}',
        blanks: ['z-index'],
        expected: 'div {\n  position: relative;\n  z-index: 10;\n}',
        xp: 15
    },

    // ===== Module 5: Flexbox =====
    {
        id: 'css-29',
        module: 'Flexbox',
        title: 'Display flex',
        difficulty: 2,
        type: 'fill-blank',
        description: 'display: flex превращает контейнер во flex-контейнер.',
        task: 'Сделай контейнер flex-контейнером',
        hint: 'display: flex',
        template: '.container {\n  display: ___;\n}',
        blanks: ['flex'],
        expected: '.container {\n  display: flex;\n}',
        xp: 15
    },
    {
        id: 'css-30',
        module: 'Flexbox',
        title: 'Justify-content',
        difficulty: 2,
        type: 'fill-blank',
        description: 'justify-content выравнивает элементы по главной оси (обычно горизонтально).',
        task: 'Распредели элементы с равными промежутками',
        hint: 'justify-content: space-between',
        template: '.container {\n  display: flex;\n  justify-content: ___;\n}',
        blanks: ['space-between'],
        expected: '.container {\n  display: flex;\n  justify-content: space-between;\n}',
        xp: 15
    },
    {
        id: 'css-31',
        module: 'Flexbox',
        title: 'Align-items',
        difficulty: 2,
        type: 'fill-blank',
        description: 'align-items выравнивает элементы по поперечной оси (обычно вертикально).',
        task: 'Выровняй элементы по центру вертикально',
        hint: 'align-items: center',
        template: '.container {\n  display: flex;\n  align-items: ___;\n}',
        blanks: ['center'],
        expected: '.container {\n  display: flex;\n  align-items: center;\n}',
        xp: 15
    },
    {
        id: 'css-32',
        module: 'Flexbox',
        title: 'Flex-direction',
        difficulty: 2,
        type: 'fill-blank',
        description: 'flex-direction задаёт направление: row (строка) или column (столбец).',
        task: 'Расположи элементы в столбец',
        hint: 'flex-direction: column',
        template: '.container {\n  display: flex;\n  flex-direction: ___;\n}',
        blanks: ['column'],
        expected: '.container {\n  display: flex;\n  flex-direction: column;\n}',
        xp: 15
    },
    {
        id: 'css-33',
        module: 'Flexbox',
        title: 'Flex-wrap',
        difficulty: 2,
        type: 'fill-blank',
        description: 'flex-wrap: wrap разрешает перенос элементов на новую строку.',
        task: 'Разреши перенос элементов',
        hint: 'flex-wrap: wrap',
        template: '.container {\n  display: flex;\n  flex-wrap: ___;\n}',
        blanks: ['wrap'],
        expected: '.container {\n  display: flex;\n  flex-wrap: wrap;\n}',
        xp: 15
    },
    {
        id: 'css-34',
        module: 'Flexbox',
        title: 'Gap',
        difficulty: 2,
        type: 'fill-blank',
        description: 'gap задаёт промежутки между flex-элементами.',
        task: 'Добавь промежуток 20px между элементами',
        hint: 'gap: 20px',
        template: '.container {\n  display: flex;\n  ___: 20px;\n}',
        blanks: ['gap'],
        expected: '.container {\n  display: flex;\n  gap: 20px;\n}',
        xp: 15
    },
    {
        id: 'css-35',
        module: 'Flexbox',
        title: 'Центрирование',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Комбинация justify-content и align-items центрирует содержимое.',
        task: 'Отцентрируй элемент по обеим осям',
        hint: 'justify-content: center и align-items: center',
        template: '.container {\n  display: flex;\n  justify-content: ___;\n  align-items: ___;\n}',
        blanks: ['center', 'center'],
        expected: '.container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}',
        xp: 15
    },

    // ===== Module 6: Grid =====
    {
        id: 'css-36',
        module: 'Grid',
        title: 'Display grid',
        difficulty: 2,
        type: 'fill-blank',
        description: 'display: grid превращает элемент в grid-контейнер.',
        task: 'Создай grid-контейнер',
        hint: 'display: grid',
        template: '.container {\n  display: ___;\n}',
        blanks: ['grid'],
        expected: '.container {\n  display: grid;\n}',
        xp: 15
    },
    {
        id: 'css-37',
        module: 'Grid',
        title: 'Grid columns',
        difficulty: 2,
        type: 'fill-blank',
        description: 'grid-template-columns определяет количество и ширину колонок.',
        task: 'Создай 3 равные колонки',
        hint: 'Используй 1fr 1fr 1fr или repeat(3, 1fr)',
        template: '.container {\n  display: grid;\n  grid-template-columns: 1fr 1fr ___;\n}',
        blanks: ['1fr'],
        expected: '.container {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr;\n}',
        xp: 15
    },
    {
        id: 'css-38',
        module: 'Grid',
        title: 'Grid gap',
        difficulty: 2,
        type: 'fill-blank',
        description: 'gap задаёт промежутки между ячейками сетки.',
        task: 'Добавь промежуток 15px',
        hint: 'gap: 15px',
        template: '.container {\n  display: grid;\n  gap: ___;\n}',
        blanks: ['15px'],
        expected: '.container {\n  display: grid;\n  gap: 15px;\n}',
        xp: 15
    },

    // ===== Module 7: Transitions & Animations =====
    {
        id: 'css-39',
        module: 'Анимации',
        title: 'Псевдокласс hover',
        difficulty: 2,
        type: 'fill-blank',
        description: ':hover применяет стили при наведении мыши.',
        task: 'Измени цвет при наведении',
        hint: 'Используй селектор :hover',
        template: 'button:___ {\n  background-color: blue;\n}',
        blanks: ['hover'],
        expected: 'button:hover {\n  background-color: blue;\n}',
        xp: 15
    },
    {
        id: 'css-40',
        module: 'Анимации',
        title: 'Transition',
        difficulty: 2,
        type: 'fill-blank',
        description: 'transition создаёт плавный переход между состояниями.',
        task: 'Добавь плавный переход 0.3 секунды',
        hint: 'transition: 0.3s или transition: all 0.3s',
        template: 'button {\n  ___: 0.3s;\n}',
        blanks: ['transition'],
        expected: 'button {\n  transition: 0.3s;\n}',
        xp: 15
    },
    {
        id: 'css-41',
        module: 'Анимации',
        title: 'Transform scale',
        difficulty: 2,
        type: 'fill-blank',
        description: 'transform: scale() увеличивает или уменьшает элемент.',
        task: 'Увеличь элемент в 1.2 раза',
        hint: 'transform: scale(1.2)',
        template: 'button:hover {\n  transform: ___(1.2);\n}',
        blanks: ['scale'],
        expected: 'button:hover {\n  transform: scale(1.2);\n}',
        xp: 15
    },
    {
        id: 'css-42',
        module: 'Анимации',
        title: 'Transform rotate',
        difficulty: 2,
        type: 'fill-blank',
        description: 'transform: rotate() поворачивает элемент на указанный угол.',
        task: 'Поверни элемент на 45 градусов',
        hint: 'transform: rotate(45deg)',
        template: '.icon:hover {\n  transform: rotate(___deg);\n}',
        blanks: ['45'],
        expected: '.icon:hover {\n  transform: rotate(45deg);\n}',
        xp: 15
    },
    {
        id: 'css-43',
        module: 'Анимации',
        title: 'Opacity',
        difficulty: 1,
        type: 'fill-blank',
        description: 'opacity управляет прозрачностью. 0 - невидимый, 1 - полностью видимый.',
        task: 'Сделай элемент полупрозрачным (50%)',
        hint: 'opacity: 0.5',
        template: 'div {\n  opacity: ___;\n}',
        blanks: ['0.5'],
        expected: 'div {\n  opacity: 0.5;\n}',
        xp: 10
    },
    {
        id: 'css-44',
        module: 'Анимации',
        title: 'Box shadow',
        difficulty: 2,
        type: 'fill-blank',
        description: 'box-shadow добавляет тень элементу: смещение-x смещение-y размытие цвет.',
        task: 'Добавь тень 5px вниз с размытием 10px',
        hint: 'box-shadow: 0 5px 10px color',
        template: '.card {\n  box-shadow: 0 5px ___ rgba(0,0,0,0.2);\n}',
        blanks: ['10px'],
        expected: '.card {\n  box-shadow: 0 5px 10px rgba(0,0,0,0.2);\n}',
        xp: 15
    },
    {
        id: 'css-45',
        module: 'Анимации',
        title: 'CSS переменные',
        difficulty: 3,
        type: 'fill-blank',
        description: 'CSS переменные объявляются с -- и используются через var().',
        task: 'Используй переменную --main-color',
        hint: 'var(--main-color)',
        template: 'button {\n  background-color: ___(--main-color);\n}',
        blanks: ['var'],
        expected: 'button {\n  background-color: var(--main-color);\n}',
        xp: 20
    },

    // Additional levels to reach 55
    {
        id: 'css-46',
        module: 'Дополнительно',
        title: 'Cursor pointer',
        difficulty: 1,
        type: 'fill-blank',
        description: 'cursor: pointer показывает руку при наведении (как у ссылок).',
        task: 'Измени курсор на руку',
        hint: 'cursor: pointer',
        template: 'button {\n  cursor: ___;\n}',
        blanks: ['pointer'],
        expected: 'button {\n  cursor: pointer;\n}',
        xp: 10
    },
    {
        id: 'css-47',
        module: 'Дополнительно',
        title: 'List style',
        difficulty: 1,
        type: 'fill-blank',
        description: 'list-style: none убирает маркеры у списка.',
        task: 'Убери маркеры списка',
        hint: 'list-style: none',
        template: 'ul {\n  list-style: ___;\n}',
        blanks: ['none'],
        expected: 'ul {\n  list-style: none;\n}',
        xp: 10
    },
    {
        id: 'css-48',
        module: 'Дополнительно',
        title: 'Overflow hidden',
        difficulty: 2,
        type: 'fill-blank',
        description: 'overflow: hidden скрывает содержимое, выходящее за границы.',
        task: 'Скрой переполнение',
        hint: 'overflow: hidden',
        template: '.card {\n  overflow: ___;\n}',
        blanks: ['hidden'],
        expected: '.card {\n  overflow: hidden;\n}',
        xp: 15
    },
    {
        id: 'css-49',
        module: 'Дополнительно',
        title: 'Object fit',
        difficulty: 2,
        type: 'fill-blank',
        description: 'object-fit: cover масштабирует изображение с сохранением пропорций.',
        task: 'Сделай изображение cover',
        hint: 'object-fit: cover',
        template: 'img {\n  object-fit: ___;\n}',
        blanks: ['cover'],
        expected: 'img {\n  object-fit: cover;\n}',
        xp: 15
    },
    {
        id: 'css-50',
        module: 'Дополнительно',
        title: 'Max width',
        difficulty: 1,
        type: 'fill-blank',
        description: 'max-width ограничивает максимальную ширину элемента.',
        task: 'Ограничь ширину до 1200px',
        hint: 'max-width: 1200px',
        template: '.container {\n  ___: 1200px;\n}',
        blanks: ['max-width'],
        expected: '.container {\n  max-width: 1200px;\n}',
        xp: 10
    },
    {
        id: 'css-51',
        module: 'Дополнительно',
        title: 'Min height',
        difficulty: 1,
        type: 'fill-blank',
        description: 'min-height задаёт минимальную высоту элемента.',
        task: 'Установи минимальную высоту 100vh',
        hint: 'min-height: 100vh',
        template: 'body {\n  ___: 100vh;\n}',
        blanks: ['min-height'],
        expected: 'body {\n  min-height: 100vh;\n}',
        xp: 10
    },
    {
        id: 'css-52',
        module: 'Дополнительно',
        title: 'Text shadow',
        difficulty: 2,
        type: 'fill-blank',
        description: 'text-shadow добавляет тень к тексту.',
        task: 'Добавь тень текста 2px 2px',
        hint: 'text-shadow: 2px 2px цвет',
        template: 'h1 {\n  text-shadow: 2px 2px ___;\n}',
        blanks: ['#000'],
        expected: 'h1 {\n  text-shadow: 2px 2px #000;\n}',
        xp: 15
    },
    {
        id: 'css-53',
        module: 'Дополнительно',
        title: 'White space',
        difficulty: 2,
        type: 'fill-blank',
        description: 'white-space: nowrap запрещает перенос текста на новую строку.',
        task: 'Запрети перенос текста',
        hint: 'white-space: nowrap',
        template: '.button {\n  white-space: ___;\n}',
        blanks: ['nowrap'],
        expected: '.button {\n  white-space: nowrap;\n}',
        xp: 15
    },
    {
        id: 'css-54',
        module: 'Дополнительно',
        title: 'Text overflow',
        difficulty: 2,
        type: 'fill-blank',
        description: 'text-overflow: ellipsis показывает ... для обрезанного текста.',
        task: 'Покажи многоточие для длинного текста',
        hint: 'text-overflow: ellipsis',
        template: '.text {\n  overflow: hidden;\n  text-overflow: ___;\n}',
        blanks: ['ellipsis'],
        expected: '.text {\n  overflow: hidden;\n  text-overflow: ellipsis;\n}',
        xp: 15
    },
    {
        id: 'css-55',
        module: 'Дополнительно',
        title: 'Градиент',
        difficulty: 3,
        type: 'fill-blank',
        description: 'linear-gradient создаёт градиентный фон.',
        task: 'Создай градиент от синего к фиолетовому',
        hint: 'linear-gradient(направление, цвет1, цвет2)',
        template: '.header {\n  background: ___(to right, blue, purple);\n}',
        blanks: ['linear-gradient'],
        expected: '.header {\n  background: linear-gradient(to right, blue, purple);\n}',
        xp: 20
    }
];

// Make available globally
window.cssLevels = cssLevels;
