/**
 * Git Levels for CodeQuest
 * Theme: Version Control / Timeline
 */

const gitLevels = [
    // ===== Module 1: Basics =====
    {
        id: 'git-01',
        module: 'Основы Git',
        title: 'Инициализация репозитория',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Команда <code>git init</code> создаёт новый Git-репозиторий в текущей папке.',
        task: 'Инициализируй новый репозиторий',
        hint: 'git init',
        template: 'git ___',
        blanks: ['init'],
        blankLabels: ['команда'],
        expected: 'git init',
        xp: 10
    },
    {
        id: 'git-02',
        module: 'Основы Git',
        title: 'Статус репозитория',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Команда <code>git status</code> показывает состояние файлов: изменённые, добавленные, неотслеживаемые.',
        task: 'Проверь статус репозитория',
        hint: 'git status',
        template: 'git ___',
        blanks: ['status'],
        blankLabels: ['команда'],
        expected: 'git status',
        xp: 10
    },
    {
        id: 'git-03',
        module: 'Основы Git',
        title: 'Добавление файла',
        difficulty: 1,
        type: 'fill-blank',
        description: '<code>git add</code> добавляет файлы в staging area (подготовка к коммиту).',
        task: 'Добавь файл index.html',
        hint: 'git add имя_файла',
        template: 'git ___ index.html',
        blanks: ['add'],
        blankLabels: ['команда'],
        expected: 'git add index.html',
        xp: 10
    },
    {
        id: 'git-04',
        module: 'Основы Git',
        title: 'Добавление всех файлов',
        difficulty: 1,
        type: 'fill-blank',
        description: '<code>git add .</code> добавляет все изменённые файлы в текущей папке.',
        task: 'Добавь все файлы',
        hint: 'Точка означает "все файлы"',
        template: 'git add ___',
        blanks: ['.'],
        blankLabels: ['символ'],
        expected: 'git add .',
        xp: 10
    },
    {
        id: 'git-05',
        module: 'Основы Git',
        title: 'Создание коммита',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git commit</code> сохраняет изменения. Флаг <code>-m</code> добавляет сообщение.',
        task: 'Создай коммит с сообщением "Initial commit"',
        hint: 'git commit -m "сообщение"',
        template: 'git ___ -m "Initial commit"',
        blanks: ['commit'],
        blankLabels: ['команда'],
        expected: 'git commit -m "Initial commit"',
        xp: 15
    },
    {
        id: 'git-06',
        module: 'Основы Git',
        title: 'Просмотр истории',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git log</code> показывает историю коммитов.',
        task: 'Посмотри историю коммитов',
        hint: 'git log',
        template: 'git ___',
        blanks: ['log'],
        blankLabels: ['команда'],
        expected: 'git log',
        xp: 15
    },
    {
        id: 'git-07',
        module: 'Основы Git',
        title: 'Просмотр изменений',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git diff</code> показывает различия между версиями файлов.',
        task: 'Посмотри изменения в файлах',
        hint: 'git diff',
        template: 'git ___',
        blanks: ['diff'],
        blankLabels: ['команда'],
        expected: 'git diff',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 1
    {
        id: 'git-07-challenge',
        module: 'Основы Git',
        title: '🏆 Контрольное: Первый коммит',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Выполни полный цикл: добавь все файлы и создай коммит.',
        task: 'Добавь все файлы и сделай коммит "Add files"',
        hint: 'git add . && git commit -m "..."',
        template: 'git ___ .\ngit ___ -m "Add files"',
        blanks: ['add', 'commit'],
        blankLabels: ['добавить', 'коммит'],
        expected: 'git add .\ngit commit -m "Add files"',
        xp: 50
    },

    // ===== Module 2: Branching =====
    {
        id: 'git-08',
        module: 'Ветки',
        title: 'Создание ветки',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git branch имя</code> создаёт новую ветку.',
        task: 'Создай ветку feature',
        hint: 'git branch имя_ветки',
        template: 'git ___ feature',
        blanks: ['branch'],
        blankLabels: ['команда'],
        expected: 'git branch feature',
        xp: 15
    },
    {
        id: 'git-09',
        module: 'Ветки',
        title: 'Список веток',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git branch</code> без аргументов показывает все локальные ветки.',
        task: 'Посмотри список веток',
        hint: 'git branch',
        template: 'git ___',
        blanks: ['branch'],
        blankLabels: ['команда'],
        expected: 'git branch',
        xp: 15
    },
    {
        id: 'git-10',
        module: 'Ветки',
        title: 'Переключение ветки',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git checkout</code> переключается на другую ветку.',
        task: 'Переключись на ветку feature',
        hint: 'git checkout имя_ветки',
        template: 'git ___ feature',
        blanks: ['checkout'],
        blankLabels: ['команда'],
        expected: 'git checkout feature',
        xp: 15
    },
    {
        id: 'git-11',
        module: 'Ветки',
        title: 'Создание и переключение',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>git checkout -b</code> создаёт ветку и сразу переключается на неё.',
        task: 'Создай ветку dev и переключись на неё',
        hint: 'git checkout -b имя',
        template: 'git checkout ___ dev',
        blanks: ['-b'],
        blankLabels: ['флаг'],
        expected: 'git checkout -b dev',
        xp: 20
    },
    {
        id: 'git-12',
        module: 'Ветки',
        title: 'Слияние веток',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>git merge</code> объединяет указанную ветку с текущей.',
        task: 'Влей ветку feature в текущую',
        hint: 'git merge имя_ветки',
        template: 'git ___ feature',
        blanks: ['merge'],
        blankLabels: ['команда'],
        expected: 'git merge feature',
        xp: 20
    },
    {
        id: 'git-13',
        module: 'Ветки',
        title: 'Удаление ветки',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git branch -d</code> удаляет ветку (после слияния).',
        task: 'Удали ветку feature',
        hint: 'git branch -d имя',
        template: 'git branch ___ feature',
        blanks: ['-d'],
        blankLabels: ['флаг'],
        expected: 'git branch -d feature',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 2
    {
        id: 'git-13-challenge',
        module: 'Ветки',
        title: '🏆 Контрольное: Workflow с ветками',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Создай ветку, переключись и сделай слияние.',
        task: 'Создай ветку fix, переключись на main, влей fix',
        hint: 'checkout -b → checkout → merge',
        template: 'git checkout ___ fix\ngit ___ main\ngit ___ fix',
        blanks: ['-b', 'checkout', 'merge'],
        blankLabels: ['создать', 'переключиться', 'слить'],
        expected: 'git checkout -b fix\ngit checkout main\ngit merge fix',
        xp: 50
    },

    // ===== Module 3: Remote =====
    {
        id: 'git-14',
        module: 'Удалённый репозиторий',
        title: 'Клонирование',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git clone</code> копирует удалённый репозиторий на компьютер.',
        task: 'Клонируй репозиторий с GitHub',
        hint: 'git clone URL',
        template: 'git ___ https://github.com/user/repo.git',
        blanks: ['clone'],
        blankLabels: ['команда'],
        expected: 'git clone https://github.com/user/repo.git',
        xp: 15
    },
    {
        id: 'git-15',
        module: 'Удалённый репозиторий',
        title: 'Добавление remote',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>git remote add</code> связывает локальный репозиторий с удалённым.',
        task: 'Добавь удалённый репозиторий origin',
        hint: 'git remote add имя URL',
        template: 'git ___ add origin https://github.com/user/repo.git',
        blanks: ['remote'],
        blankLabels: ['команда'],
        expected: 'git remote add origin https://github.com/user/repo.git',
        xp: 20
    },
    {
        id: 'git-16',
        module: 'Удалённый репозиторий',
        title: 'Отправка изменений',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git push</code> отправляет коммиты на удалённый сервер.',
        task: 'Отправь изменения в origin main',
        hint: 'git push remote ветка',
        template: 'git ___ origin main',
        blanks: ['push'],
        blankLabels: ['команда'],
        expected: 'git push origin main',
        xp: 15
    },
    {
        id: 'git-17',
        module: 'Удалённый репозиторий',
        title: 'Получение изменений',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>git pull</code> скачивает и применяет изменения с сервера.',
        task: 'Получи изменения из origin main',
        hint: 'git pull remote ветка',
        template: 'git ___ origin main',
        blanks: ['pull'],
        blankLabels: ['команда'],
        expected: 'git pull origin main',
        xp: 15
    },
    {
        id: 'git-18',
        module: 'Удалённый репозиторий',
        title: 'Fetch без слияния',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>git fetch</code> скачивает изменения, но не применяет их.',
        task: 'Скачай изменения без слияния',
        hint: 'git fetch',
        template: 'git ___',
        blanks: ['fetch'],
        blankLabels: ['команда'],
        expected: 'git fetch',
        xp: 20
    },
    {
        id: 'git-19',
        module: 'Удалённый репозиторий',
        title: 'Первый push',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>git push -u</code> устанавливает upstream для ветки.',
        task: 'Отправь ветку main и установи upstream',
        hint: 'git push -u origin main',
        template: 'git push ___ origin main',
        blanks: ['-u'],
        blankLabels: ['флаг'],
        expected: 'git push -u origin main',
        xp: 20
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 3
    {
        id: 'git-19-challenge',
        module: 'Удалённый репозиторий',
        title: '🏆 Контрольное: Синхронизация',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Получи изменения, добавь файлы, сделай коммит и отправь.',
        task: 'Pull → add → commit → push',
        hint: 'pull, add, commit, push',
        template: 'git ___ origin main\ngit add .\ngit ___ -m "Update"\ngit ___ origin main',
        blanks: ['pull', 'commit', 'push'],
        blankLabels: ['получить', 'коммит', 'отправить'],
        expected: 'git pull origin main\ngit add .\ngit commit -m "Update"\ngit push origin main',
        xp: 50
    },

    // ===== Module 4: Advanced =====
    {
        id: 'git-20',
        module: 'Продвинутые команды',
        title: 'Stash изменений',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>git stash</code> временно сохраняет незакоммиченные изменения.',
        task: 'Сохрани изменения во временное хранилище',
        hint: 'git stash',
        template: 'git ___',
        blanks: ['stash'],
        blankLabels: ['команда'],
        expected: 'git stash',
        xp: 20
    },
    {
        id: 'git-21',
        module: 'Продвинутые команды',
        title: 'Восстановление stash',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>git stash pop</code> восстанавливает последние сохранённые изменения.',
        task: 'Восстанови изменения из stash',
        hint: 'git stash pop',
        template: 'git stash ___',
        blanks: ['pop'],
        blankLabels: ['команда'],
        expected: 'git stash pop',
        xp: 20
    },
    {
        id: 'git-22',
        module: 'Продвинутые команды',
        title: 'Отмена изменений в файле',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>git checkout -- файл</code> отменяет изменения в файле.',
        task: 'Отмени изменения в index.html',
        hint: 'git checkout -- файл',
        template: 'git checkout ___ index.html',
        blanks: ['--'],
        blankLabels: ['разделитель'],
        expected: 'git checkout -- index.html',
        xp: 20
    },
    {
        id: 'git-23',
        module: 'Продвинутые команды',
        title: 'Reset коммита',
        difficulty: 4,
        type: 'fill-blank',
        description: '<code>git reset --soft HEAD~1</code> отменяет последний коммит, сохраняя изменения.',
        task: 'Отмени последний коммит (сохрани изменения)',
        hint: 'git reset --soft HEAD~1',
        template: 'git ___ --soft HEAD~1',
        blanks: ['reset'],
        blankLabels: ['команда'],
        expected: 'git reset --soft HEAD~1',
        xp: 25
    },
    {
        id: 'git-24',
        module: 'Продвинутые команды',
        title: 'Cherry-pick',
        difficulty: 4,
        type: 'fill-blank',
        description: '<code>git cherry-pick</code> копирует конкретный коммит в текущую ветку.',
        task: 'Скопируй коммит abc123 в текущую ветку',
        hint: 'git cherry-pick хеш',
        template: 'git ___ abc123',
        blanks: ['cherry-pick'],
        blankLabels: ['команда'],
        expected: 'git cherry-pick abc123',
        xp: 25
    },
    {
        id: 'git-25',
        module: 'Продвинутые команды',
        title: 'Rebase',
        difficulty: 4,
        type: 'fill-blank',
        description: '<code>git rebase</code> переносит коммиты на другую базу.',
        task: 'Сделай rebase на ветку main',
        hint: 'git rebase ветка',
        template: 'git ___ main',
        blanks: ['rebase'],
        blankLabels: ['команда'],
        expected: 'git rebase main',
        xp: 25
    },
    // 🏆 ФИНАЛЬНОЕ КОНТРОЛЬНОЕ ЗАДАНИЕ
    {
        id: 'git-25-challenge',
        module: 'Продвинутые команды',
        title: '🏆 Финальное: Git мастер',
        difficulty: 5,
        type: 'fill-blank',
        description: '<strong>🏆 ФИНАЛЬНОЕ КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Сохрани изменения в stash, переключись на main, получи обновления, восстанови stash.<br><br>🎉 Это финальное задание курса Git!',
        task: 'Stash → checkout main → pull → stash pop',
        hint: 'stash, checkout, pull, stash pop',
        template: 'git ___\ngit ___ main\ngit ___ origin main\ngit stash ___',
        blanks: ['stash', 'checkout', 'pull', 'pop'],
        blankLabels: ['сохранить', 'переключить', 'получить', 'восстановить'],
        expected: 'git stash\ngit checkout main\ngit pull origin main\ngit stash pop',
        xp: 75
    }
];

// Make available globally
window.gitLevels = gitLevels;
