/**
 * HTML Levels for CodeQuest
 * Theme: Builder / Construction
 */

const htmlLevels = [
    // ===== Module 1: Basics =====
    {
        id: 'html-01',
        module: 'Основы HTML',
        title: 'Твой первый заголовок',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Заголовки в HTML создаются с помощью тегов от &lt;h1&gt; до &lt;h6&gt;. Тег &lt;h1&gt; - самый главный заголовок на странице.',
        task: 'Впиши название тега для главного заголовка (без скобок)',
        hint: 'Главный заголовок - это h1',
        template: '<[[TAG]]>Привет, мир!</[[TAG]]>',
        blanks: ['h1'],
        blankLabels: ['тег'],
        expected: '<h1>Привет, мир!</h1>',
        xp: 10
    },
    {
        id: 'html-02',
        module: 'Основы HTML',
        title: 'Разные заголовки',
        difficulty: 1,
        type: 'fill-blank',
        description: 'В HTML есть 6 уровней заголовков: h1 (самый важный) до h6 (наименее важный).',
        task: 'Впиши название тега для заголовка второго уровня',
        hint: 'Заголовок второго уровня - это h2',
        template: '<[[TAG]]>Подзаголовок</[[TAG]]>',
        blanks: ['h2'],
        blankLabels: ['тег'],
        expected: '<h2>Подзаголовок</h2>',
        xp: 10
    },
    {
        id: 'html-03',
        module: 'Основы HTML',
        title: 'Параграфы',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Параграфы текста создаются с помощью тега &lt;p&gt;. Это основной способ добавления текста на страницу.',
        task: 'Впиши название тега для параграфа',
        hint: 'Тег для параграфа - p',
        template: '<[[TAG]]>Это мой первый параграф</[[TAG]]>',
        blanks: ['p'],
        blankLabels: ['тег'],
        expected: '<p>Это мой первый параграф</p>',
        xp: 10
    },
    {
        id: 'html-04',
        module: 'Основы HTML',
        title: 'Жирный текст',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Чтобы сделать текст жирным, используй тег &lt;strong&gt;. Он также указывает на важность текста.',
        task: 'Впиши название тега для жирного текста',
        hint: 'Тег для важного/жирного текста - strong',
        template: 'Это <[[TAG]]>важно</[[TAG]]> запомнить!',
        blanks: ['strong'],
        blankLabels: ['тег'],
        expected: 'Это <strong>важно</strong> запомнить!',
        xp: 10
    },
    {
        id: 'html-05',
        module: 'Основы HTML',
        title: 'Курсивный текст',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Тег &lt;em&gt; делает текст курсивным и указывает на смысловое ударение.',
        task: 'Впиши название тега для курсива',
        hint: 'Тег для курсива/выделения - em',
        template: 'Это <[[TAG]]>очень</[[TAG]]> интересно!',
        blanks: ['em'],
        blankLabels: ['тег'],
        expected: 'Это <em>очень</em> интересно!',
        xp: 10
    },
    {
        id: 'html-06',
        module: 'Основы HTML',
        title: 'Перенос строки',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Тег &lt;br&gt; создаёт перенос строки. Это одиночный тег, его не нужно закрывать.',
        task: 'Впиши название тега для переноса строки',
        hint: 'Тег переноса - br (break)',
        template: 'Первая строка.<___>Вторая строка.',
        blanks: ['br'],
        blankLabels: ['тег'],
        expected: 'Первая строка.<br>Вторая строка.',
        xp: 10
    },
    {
        id: 'html-07',
        module: 'Основы HTML',
        title: 'Горизонтальная линия',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Тег &lt;hr&gt; создаёт горизонтальную разделительную линию.',
        task: 'Впиши название тега для горизонтальной линии',
        hint: 'Тег линии - hr (horizontal rule)',
        template: '<h1>Заголовок</h1><___><p>Текст</p>',
        blanks: ['hr'],
        blankLabels: ['тег'],
        expected: '<h1>Заголовок</h1><hr><p>Текст</p>',
        xp: 10
    },
    {
        id: 'html-08',
        module: 'Основы HTML',
        title: 'Выделение текста',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Тег &lt;mark&gt; выделяет текст жёлтым маркером.',
        task: 'Впиши название тега для выделения маркером',
        hint: 'Тег выделения - mark',
        template: 'Это <[[TAG]]>выделенный</[[TAG]]> текст.',
        blanks: ['mark'],
        blankLabels: ['тег'],
        expected: 'Это <mark>выделенный</mark> текст.',
        xp: 10
    },

    // ===== Module 2: Links and Images =====
    {
        id: 'html-09',
        module: 'Ссылки и изображения',
        title: 'Создание ссылки',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Ссылки создаются тегом &lt;a&gt;. Атрибут href указывает адрес, куда ведёт ссылка.',
        task: 'Создай ссылку: впиши тег и атрибут для адреса',
        hint: 'Тег ссылки - a, атрибут адреса - href',
        template: '<[[TAG]] ___="#">Перейти на сайт</[[TAG]]>',
        blanks: ['a', 'href'],
        blankLabels: ['тег', 'атрибут'],
        expected: '<a href="#">Перейти на сайт</a>',
        xp: 15
    },
    {
        id: 'html-10',
        module: 'Ссылки и изображения',
        title: 'Ссылка в новой вкладке',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Атрибут target="_blank" открывает ссылку в новой вкладке браузера.',
        task: 'Впиши атрибут и его значение для открытия в новой вкладке',
        hint: 'Атрибут: target, значение: _blank',
        template: '<a href="#" ___="___">Открыть в новом окне</a>',
        blanks: ['target', '_blank'],
        blankLabels: ['атрибут', 'значение'],
        expected: '<a href="#" target="_blank">Открыть в новом окне</a>',
        xp: 20
    },
    {
        id: 'html-11',
        module: 'Ссылки и изображения',
        title: 'Тег изображения',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Изображения добавляются тегом &lt;img&gt;.',
        task: 'Впиши название тега для изображения',
        hint: 'Тег изображения - img',
        template: '<___ src="photo.jpg">',
        blanks: ['img'],
        blankLabels: ['тег'],
        expected: '<img src="photo.jpg">',
        xp: 10
    },
    {
        id: 'html-12',
        module: 'Ссылки и изображения',
        title: 'Путь к изображению',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Атрибут src указывает путь к файлу изображения.',
        task: 'Впиши название атрибута для пути к картинке',
        hint: 'Атрибут пути - src (source)',
        template: '<img ___="photo.jpg">',
        blanks: ['src'],
        blankLabels: ['атрибут'],
        expected: '<img src="photo.jpg">',
        xp: 10
    },
    {
        id: 'html-13',
        module: 'Ссылки и изображения',
        title: 'Полное изображение',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Изображение должно иметь атрибуты src (путь) и alt (описание для доступности).',
        task: 'Создай изображение с путём и описанием',
        hint: 'Атрибут пути - src, атрибут описания - alt',
        template: '<img ___="sunset.jpg" ___="Красивый закат">',
        blanks: ['src', 'alt'],
        blankLabels: ['путь', 'описание'],
        expected: '<img src="sunset.jpg" alt="Красивый закат">',
        xp: 20
    },
    {
        id: 'html-14',
        module: 'Ссылки и изображения',
        title: 'Размеры изображения',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Атрибуты width и height задают размеры изображения в пикселях.',
        task: 'Укажи атрибуты для ширины 300 и высоты 200',
        hint: 'width - ширина, height - высота',
        template: '<img src="photo.jpg" ___="300" ___="200">',
        blanks: ['width', 'height'],
        blankLabels: ['ширина', 'высота'],
        expected: '<img src="photo.jpg" width="300" height="200">',
        xp: 20
    },

    // ===== Module 3: Lists =====
    {
        id: 'html-15',
        module: 'Списки',
        title: 'Маркированный список',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Маркированный список создаётся тегом &lt;ul&gt; (unordered list).',
        task: 'Впиши название тега для маркированного списка',
        hint: 'ul - unordered list',
        template: '<[[TAG]]><li>Пункт 1</li><li>Пункт 2</li></[[TAG]]>',
        blanks: ['ul'],
        blankLabels: ['тег'],
        expected: '<ul><li>Пункт 1</li><li>Пункт 2</li></ul>',
        xp: 10
    },
    {
        id: 'html-16',
        module: 'Списки',
        title: 'Нумерованный список',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Нумерованный список создаётся тегом &lt;ol&gt; (ordered list).',
        task: 'Впиши название тега для нумерованного списка',
        hint: 'ol - ordered list',
        template: '<[[TAG]]><li>Первый</li><li>Второй</li></[[TAG]]>',
        blanks: ['ol'],
        blankLabels: ['тег'],
        expected: '<ol><li>Первый</li><li>Второй</li></ol>',
        xp: 10
    },
    {
        id: 'html-17',
        module: 'Списки',
        title: 'Элемент списка',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Каждый пункт списка оборачивается в тег &lt;li&gt; (list item).',
        task: 'Впиши название тега для элемента списка',
        hint: 'li - list item',
        template: '<ul><[[TAG]]>Яблоко</[[TAG]]></ul>',
        blanks: ['li'],
        blankLabels: ['тег'],
        expected: '<ul><li>Яблоко</li></ul>',
        xp: 10
    },

    // ===== Module 4: Tables =====
    {
        id: 'html-18',
        module: 'Таблицы',
        title: 'Тег таблицы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Таблицы создаются тегом &lt;table&gt;.',
        task: 'Впиши название тега для таблицы',
        hint: 'Тег таблицы - table',
        template: '<[[TAG]]><tr><td>Ячейка</td></tr></[[TAG]]>',
        blanks: ['table'],
        blankLabels: ['тег'],
        expected: '<table><tr><td>Ячейка</td></tr></table>',
        xp: 15
    },
    {
        id: 'html-19',
        module: 'Таблицы',
        title: 'Строка таблицы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;tr&gt; (table row) создаёт строку в таблице.',
        task: 'Впиши название тега для строки таблицы',
        hint: 'tr - table row',
        template: '<table><[[TAG]]><td>1</td><td>2</td></[[TAG]]></table>',
        blanks: ['tr'],
        blankLabels: ['тег'],
        expected: '<table><tr><td>1</td><td>2</td></tr></table>',
        xp: 15
    },
    {
        id: 'html-20',
        module: 'Таблицы',
        title: 'Ячейка таблицы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;td&gt; (table data) создаёт ячейку с данными.',
        task: 'Впиши название тега для ячейки данных',
        hint: 'td - table data',
        template: '<table><tr><[[TAG]]>Данные</[[TAG]]></tr></table>',
        blanks: ['td'],
        blankLabels: ['тег'],
        expected: '<table><tr><td>Данные</td></tr></table>',
        xp: 15
    },
    {
        id: 'html-21',
        module: 'Таблицы',
        title: 'Заголовок таблицы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;th&gt; (table header) создаёт ячейку-заголовок.',
        task: 'Впиши название тега для заголовка столбца',
        hint: 'th - table header',
        template: '<table><tr><[[TAG]]>Имя</[[TAG]]><th>Возраст</th></tr></table>',
        blanks: ['th'],
        blankLabels: ['тег'],
        expected: '<table><tr><th>Имя</th><th>Возраст</th></tr></table>',
        xp: 15
    },
    {
        id: 'html-22',
        module: 'Таблицы',
        title: 'Объединение столбцов',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Атрибут colspan объединяет ячейки по горизонтали.',
        task: 'Впиши название атрибута для объединения столбцов',
        hint: 'colspan - column span',
        template: '<table><tr><td ___="2">Объединённая</td></tr></table>',
        blanks: ['colspan'],
        blankLabels: ['атрибут'],
        expected: '<table><tr><td colspan="2">Объединённая</td></tr></table>',
        xp: 20
    },

    // ===== Module 5: Forms =====
    {
        id: 'html-23',
        module: 'Формы',
        title: 'Тег формы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Форма создаётся тегом &lt;form&gt;.',
        task: 'Впиши название тега для формы',
        hint: 'Тег формы - form',
        template: '<[[TAG]]><input type="text"></[[TAG]]>',
        blanks: ['form'],
        blankLabels: ['тег'],
        expected: '<form><input type="text"></form>',
        xp: 15
    },
    {
        id: 'html-24',
        module: 'Формы',
        title: 'Поле ввода',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;input&gt; создаёт поле ввода.',
        task: 'Впиши название тега для поля ввода',
        hint: 'Тег ввода - input',
        template: '<___ type="text">',
        blanks: ['input'],
        blankLabels: ['тег'],
        expected: '<input type="text">',
        xp: 15
    },
    {
        id: 'html-25',
        module: 'Формы',
        title: 'Поле для пароля',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Поле пароля скрывает ввод. Используй тег input с type="password".',
        task: 'Создай поле для пароля: укажи тег и тип',
        hint: 'Тег - input, тип - password',
        template: '<___ type="___" name="pass">',
        blanks: ['input', 'password'],
        blankLabels: ['тег', 'тип'],
        expected: '<input type="password" name="pass">',
        xp: 20
    },
    {
        id: 'html-26',
        module: 'Формы',
        title: 'Поле email с подсказкой',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Атрибут placeholder показывает подсказку, type="email" проверяет формат.',
        task: 'Создай поле для email с подсказкой',
        hint: 'type="email", атрибут подсказки - placeholder',
        template: '<input type="___" ___="Введите ваш email">',
        blanks: ['email', 'placeholder'],
        blankLabels: ['тип', 'атрибут'],
        expected: '<input type="email" placeholder="Введите ваш email">',
        xp: 20
    },
    {
        id: 'html-27',
        module: 'Формы',
        title: 'Кнопка',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;button&gt; создаёт кнопку.',
        task: 'Впиши название тега для кнопки',
        hint: 'Тег кнопки - button',
        template: '<[[TAG]] type="submit">Отправить</[[TAG]]>',
        blanks: ['button'],
        blankLabels: ['тег'],
        expected: '<button type="submit">Отправить</button>',
        xp: 15
    },
    {
        id: 'html-28',
        module: 'Формы',
        title: 'Чекбокс',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тип checkbox создаёт флажок для выбора.',
        task: 'Впиши тип для чекбокса',
        hint: 'Тип флажка - checkbox',
        template: '<input type="___"> Согласен',
        blanks: ['checkbox'],
        blankLabels: ['тип'],
        expected: '<input type="checkbox"> Согласен',
        xp: 15
    },
    {
        id: 'html-29',
        module: 'Формы',
        title: 'Обязательное поле',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Атрибут required делает поле обязательным.',
        task: 'Впиши название атрибута для обязательного поля',
        hint: 'Атрибут - required',
        template: '<input type="text" ___>',
        blanks: ['required'],
        blankLabels: ['атрибут'],
        expected: '<input type="text" required>',
        xp: 15
    },
    {
        id: 'html-30',
        module: 'Формы',
        title: 'Текстовая область',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;textarea&gt; создаёт многострочное поле ввода.',
        task: 'Впиши название тега для текстовой области',
        hint: 'Тег - textarea',
        template: '<[[TAG]]>Текст...</[[TAG]]>',
        blanks: ['textarea'],
        blankLabels: ['тег'],
        expected: '<textarea>Текст...</textarea>',
        xp: 15
    },

    // ===== Module 6: Semantic HTML =====
    {
        id: 'html-31',
        module: 'Семантика',
        title: 'Шапка с заголовком',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Тег &lt;header&gt; обозначает шапку. Внутри обычно &lt;h1&gt; с названием.',
        task: 'Создай шапку страницы с главным заголовком',
        hint: 'Шапка - header, главный заголовок - h1',
        template: '<[[OUTER]]><[[INNER]]>Мой сайт</[[INNER]]></[[OUTER]]>',
        blanks: ['header', 'h1'],
        blankLabels: ['контейнер', 'заголовок'],
        expected: '<header><h1>Мой сайт</h1></header>',
        xp: 20
    },
    {
        id: 'html-32',
        module: 'Семантика',
        title: 'Навигационное меню',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Навигация &lt;nav&gt; содержит ссылки &lt;a&gt; на разделы сайта.',
        task: 'Создай навигацию со ссылкой на главную',
        hint: 'Навигация - nav, ссылка - a с атрибутом href',
        template: '<[[NAV]]><[[LINK]] href="/">Главная</[[LINK]]></[[NAV]]>',
        blanks: ['nav', 'a'],
        blankLabels: ['контейнер', 'ссылка'],
        expected: '<nav><a href="/">Главная</a></nav>',
        xp: 20
    },
    {
        id: 'html-33',
        module: 'Семантика',
        title: 'Структура страницы',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Тег &lt;main&gt; содержит основной контент, &lt;section&gt; - его разделы.',
        task: 'Создай основной контент с разделом внутри',
        hint: 'Основной контент - main, раздел - section',
        template: '<[[MAIN]]><[[SECTION]]><p>Контент раздела</p></[[SECTION]]></[[MAIN]]>',
        blanks: ['main', 'section'],
        blankLabels: ['основной', 'раздел'],
        expected: '<main><section><p>Контент раздела</p></section></main>',
        xp: 25
    },
    {
        id: 'html-34',
        module: 'Семантика',
        title: 'Статья блога',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Статья &lt;article&gt; содержит заголовок и текст, самодостаточна.',
        task: 'Создай статью с заголовком h2 и параграфом',
        hint: 'article, h2, p',
        template: '<[[ART]]><[[HEAD]]>Новость дня</[[HEAD]]><[[TEXT]]>Текст новости...</[[TEXT]]></[[ART]]>',
        blanks: ['article', 'h2', 'p'],
        blankLabels: ['статья', 'заголовок', 'текст'],
        expected: '<article><h2>Новость дня</h2><p>Текст новости...</p></article>',
        xp: 25
    },
    {
        id: 'html-35',
        module: 'Семантика',
        title: 'Полная структура',
        difficulty: 4,
        type: 'fill-blank',
        description: 'Страница содержит header (шапку), main (контент) и footer (подвал).',
        task: 'Собери базовую структуру страницы из трёх частей',
        hint: 'Шапка - header, контент - main, подвал - footer',
        template: '<[[HEAD]]>Шапка</[[HEAD]]><[[MAIN]]>Контент</[[MAIN]]><[[FOOT]]>© 2024</[[FOOT]]>',
        blanks: ['header', 'main', 'footer'],
        blankLabels: ['шапка', 'контент', 'подвал'],
        expected: '<header>Шапка</header><main>Контент</main><footer>© 2024</footer>',
        xp: 30
    }
];

// Make available globally
window.htmlLevels = htmlLevels;
