/**
 * HTML Levels for CodeQuest
 * Theme: Builder / Construction
 */

const htmlLevels = [
    // ===== Module 1: Basics =====
    {
        id: 'html-01',
        module: 'Основы HTML',
        title: 'Твой первый заголовок',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Заголовки в HTML создаются с помощью тегов от &lt;h1&gt; до &lt;h6&gt;. Тег &lt;h1&gt; - самый главный заголовок на странице.',
        task: 'Впиши название тега для главного заголовка (без скобок)',
        hint: 'Главный заголовок - это h1',
        template: '<[[TAG]]>Привет, мир!</[[TAG]]>',
        blanks: ['h1'],
        blankLabels: ['тег'],
        expected: '<h1>Привет, мир!</h1>',
        xp: 10
    },
    {
        id: 'html-02',
        module: 'Основы HTML',
        title: 'Разные заголовки',
        difficulty: 1,
        type: 'fill-blank',
        description: 'В HTML есть 6 уровней заголовков: h1 (самый важный) до h6 (наименее важный).',
        task: 'Впиши название тега для заголовка второго уровня',
        hint: 'Заголовок второго уровня - это h2',
        template: '<[[TAG]]>Подзаголовок</[[TAG]]>',
        blanks: ['h2'],
        blankLabels: ['тег'],
        expected: '<h2>Подзаголовок</h2>',
        xp: 10
    },
    {
        id: 'html-03',
        module: 'Основы HTML',
        title: 'Параграфы',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Параграфы текста создаются с помощью тега &lt;p&gt;. Это основной способ добавления текста на страницу.',
        task: 'Впиши название тега для параграфа',
        hint: 'Тег для параграфа - p',
        template: '<[[TAG]]>Это мой первый параграф</[[TAG]]>',
        blanks: ['p'],
        blankLabels: ['тег'],
        expected: '<p>Это мой первый параграф</p>',
        xp: 10
    },
    {
        id: 'html-04',
        module: 'Основы HTML',
        title: 'Жирный текст',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Чтобы сделать текст жирным, используй тег &lt;strong&gt;. Он также указывает на важность текста.',
        task: 'Впиши название тега для жирного текста',
        hint: 'Тег для важного/жирного текста - strong',
        template: 'Это <[[TAG]]>важно</[[TAG]]> запомнить!',
        blanks: ['strong'],
        blankLabels: ['тег'],
        expected: 'Это <strong>важно</strong> запомнить!',
        xp: 10
    },
    {
        id: 'html-05',
        module: 'Основы HTML',
        title: 'Курсивный текст',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Тег &lt;em&gt; делает текст курсивным и указывает на смысловое ударение.',
        task: 'Впиши название тега для курсива',
        hint: 'Тег для курсива/выделения - em',
        template: 'Это <[[TAG]]>очень</[[TAG]]> интересно!',
        blanks: ['em'],
        blankLabels: ['тег'],
        expected: 'Это <em>очень</em> интересно!',
        xp: 10
    },
    {
        id: 'html-06',
        module: 'Основы HTML',
        title: 'Перенос строки',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Тег &lt;br&gt; создаёт перенос строки. Это одиночный тег, его не нужно закрывать.',
        task: 'Впиши название тега для переноса строки',
        hint: 'Тег переноса - br (break)',
        template: 'Первая строка.<___>Вторая строка.',
        blanks: ['br'],
        blankLabels: ['тег'],
        expected: 'Первая строка.<br>Вторая строка.',
        xp: 10
    },
    {
        id: 'html-07',
        module: 'Основы HTML',
        title: 'Горизонтальная линия',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Тег &lt;hr&gt; создаёт горизонтальную разделительную линию.',
        task: 'Впиши название тега для горизонтальной линии',
        hint: 'Тег линии - hr (horizontal rule)',
        template: '<h1>Заголовок</h1><___><p>Текст</p>',
        blanks: ['hr'],
        blankLabels: ['тег'],
        expected: '<h1>Заголовок</h1><hr><p>Текст</p>',
        xp: 10
    },
    {
        id: 'html-08',
        module: 'Основы HTML',
        title: 'Выделение текста',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Тег &lt;mark&gt; выделяет текст жёлтым маркером.',
        task: 'Впиши название тега для выделения маркером',
        hint: 'Тег выделения - mark',
        template: 'Это <[[TAG]]>выделенный</[[TAG]]> текст.',
        blanks: ['mark'],
        blankLabels: ['тег'],
        expected: 'Это <mark>выделенный</mark> текст.',
        xp: 10
    },

    // ===== Module 2: Links and Images =====
    {
        id: 'html-09',
        module: 'Ссылки и изображения',
        title: 'Простая ссылка',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Ссылки создаются тегом &lt;a&gt;. Атрибут href указывает адрес.',
        task: 'Впиши название атрибута для адреса ссылки',
        hint: 'Атрибут адреса - href',
        template: '<a ___="https://google.com">Google</a>',
        blanks: ['href'],
        blankLabels: ['атрибут'],
        expected: '<a href="https://google.com">Google</a>',
        xp: 10
    },
    {
        id: 'html-10',
        module: 'Ссылки и изображения',
        title: 'Ссылка в новой вкладке',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Атрибут target="_blank" открывает ссылку в новой вкладке.',
        task: 'Впиши значение target для открытия в новой вкладке',
        hint: 'Значение: _blank',
        template: '<a href="https://google.com" target="___">Google</a>',
        blanks: ['_blank'],
        blankLabels: ['значение'],
        expected: '<a href="https://google.com" target="_blank">Google</a>',
        xp: 15
    },
    {
        id: 'html-11',
        module: 'Ссылки и изображения',
        title: 'Тег изображения',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Изображения добавляются тегом &lt;img&gt;.',
        task: 'Впиши название тега для изображения',
        hint: 'Тег изображения - img',
        template: '<___ src="photo.jpg">',
        blanks: ['img'],
        blankLabels: ['тег'],
        expected: '<img src="photo.jpg">',
        xp: 10
    },
    {
        id: 'html-12',
        module: 'Ссылки и изображения',
        title: 'Путь к изображению',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Атрибут src указывает путь к файлу изображения.',
        task: 'Впиши название атрибута для пути к картинке',
        hint: 'Атрибут пути - src (source)',
        template: '<img ___="photo.jpg">',
        blanks: ['src'],
        blankLabels: ['атрибут'],
        expected: '<img src="photo.jpg">',
        xp: 10
    },
    {
        id: 'html-13',
        module: 'Ссылки и изображения',
        title: 'Альтернативный текст',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Атрибут alt содержит описание картинки для доступности.',
        task: 'Впиши название атрибута для описания изображения',
        hint: 'Атрибут описания - alt',
        template: '<img src="sunset.jpg" ___="Красивый закат">',
        blanks: ['alt'],
        blankLabels: ['атрибут'],
        expected: '<img src="sunset.jpg" alt="Красивый закат">',
        xp: 15
    },
    {
        id: 'html-14',
        module: 'Ссылки и изображения',
        title: 'Ширина изображения',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Атрибут width задаёт ширину изображения.',
        task: 'Впиши название атрибута для ширины',
        hint: 'Атрибут ширины - width',
        template: '<img src="photo.jpg" ___="300">',
        blanks: ['width'],
        blankLabels: ['атрибут'],
        expected: '<img src="photo.jpg" width="300">',
        xp: 15
    },

    // ===== Module 3: Lists =====
    {
        id: 'html-15',
        module: 'Списки',
        title: 'Маркированный список',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Маркированный список создаётся тегом &lt;ul&gt; (unordered list).',
        task: 'Впиши название тега для маркированного списка',
        hint: 'ul - unordered list',
        template: '<[[TAG]]><li>Пункт 1</li><li>Пункт 2</li></[[TAG]]>',
        blanks: ['ul'],
        blankLabels: ['тег'],
        expected: '<ul><li>Пункт 1</li><li>Пункт 2</li></ul>',
        xp: 10
    },
    {
        id: 'html-16',
        module: 'Списки',
        title: 'Нумерованный список',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Нумерованный список создаётся тегом &lt;ol&gt; (ordered list).',
        task: 'Впиши название тега для нумерованного списка',
        hint: 'ol - ordered list',
        template: '<[[TAG]]><li>Первый</li><li>Второй</li></[[TAG]]>',
        blanks: ['ol'],
        blankLabels: ['тег'],
        expected: '<ol><li>Первый</li><li>Второй</li></ol>',
        xp: 10
    },
    {
        id: 'html-17',
        module: 'Списки',
        title: 'Элемент списка',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Каждый пункт списка оборачивается в тег &lt;li&gt; (list item).',
        task: 'Впиши название тега для элемента списка',
        hint: 'li - list item',
        template: '<ul><[[TAG]]>Яблоко</[[TAG]]></ul>',
        blanks: ['li'],
        blankLabels: ['тег'],
        expected: '<ul><li>Яблоко</li></ul>',
        xp: 10
    },

    // ===== Module 4: Tables =====
    {
        id: 'html-18',
        module: 'Таблицы',
        title: 'Тег таблицы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Таблицы создаются тегом &lt;table&gt;.',
        task: 'Впиши название тега для таблицы',
        hint: 'Тег таблицы - table',
        template: '<[[TAG]]><tr><td>Ячейка</td></tr></[[TAG]]>',
        blanks: ['table'],
        blankLabels: ['тег'],
        expected: '<table><tr><td>Ячейка</td></tr></table>',
        xp: 15
    },
    {
        id: 'html-19',
        module: 'Таблицы',
        title: 'Строка таблицы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;tr&gt; (table row) создаёт строку в таблице.',
        task: 'Впиши название тега для строки таблицы',
        hint: 'tr - table row',
        template: '<table><[[TAG]]><td>1</td><td>2</td></[[TAG]]></table>',
        blanks: ['tr'],
        blankLabels: ['тег'],
        expected: '<table><tr><td>1</td><td>2</td></tr></table>',
        xp: 15
    },
    {
        id: 'html-20',
        module: 'Таблицы',
        title: 'Ячейка таблицы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;td&gt; (table data) создаёт ячейку с данными.',
        task: 'Впиши название тега для ячейки данных',
        hint: 'td - table data',
        template: '<table><tr><[[TAG]]>Данные</[[TAG]]></tr></table>',
        blanks: ['td'],
        blankLabels: ['тег'],
        expected: '<table><tr><td>Данные</td></tr></table>',
        xp: 15
    },
    {
        id: 'html-21',
        module: 'Таблицы',
        title: 'Заголовок таблицы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;th&gt; (table header) создаёт ячейку-заголовок.',
        task: 'Впиши название тега для заголовка столбца',
        hint: 'th - table header',
        template: '<table><tr><[[TAG]]>Имя</[[TAG]]><th>Возраст</th></tr></table>',
        blanks: ['th'],
        blankLabels: ['тег'],
        expected: '<table><tr><th>Имя</th><th>Возраст</th></tr></table>',
        xp: 15
    },
    {
        id: 'html-22',
        module: 'Таблицы',
        title: 'Объединение столбцов',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Атрибут colspan объединяет ячейки по горизонтали.',
        task: 'Впиши название атрибута для объединения столбцов',
        hint: 'colspan - column span',
        template: '<table><tr><td ___="2">Объединённая</td></tr></table>',
        blanks: ['colspan'],
        blankLabels: ['атрибут'],
        expected: '<table><tr><td colspan="2">Объединённая</td></tr></table>',
        xp: 20
    },

    // ===== Module 5: Forms =====
    {
        id: 'html-23',
        module: 'Формы',
        title: 'Тег формы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Форма создаётся тегом &lt;form&gt;.',
        task: 'Впиши название тега для формы',
        hint: 'Тег формы - form',
        template: '<[[TAG]]><input type="text"></[[TAG]]>',
        blanks: ['form'],
        blankLabels: ['тег'],
        expected: '<form><input type="text"></form>',
        xp: 15
    },
    {
        id: 'html-24',
        module: 'Формы',
        title: 'Поле ввода',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;input&gt; создаёт поле ввода.',
        task: 'Впиши название тега для поля ввода',
        hint: 'Тег ввода - input',
        template: '<___ type="text">',
        blanks: ['input'],
        blankLabels: ['тег'],
        expected: '<input type="text">',
        xp: 15
    },
    {
        id: 'html-25',
        module: 'Формы',
        title: 'Тип поля',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Атрибут type определяет тип поля: text, password, email и др.',
        task: 'Впиши тип для поля пароля',
        hint: 'Тип пароля - password',
        template: '<input type="___">',
        blanks: ['password'],
        blankLabels: ['тип'],
        expected: '<input type="password">',
        xp: 15
    },
    {
        id: 'html-26',
        module: 'Формы',
        title: 'Подсказка в поле',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Атрибут placeholder показывает подсказку в пустом поле.',
        task: 'Впиши название атрибута для подсказки',
        hint: 'Атрибут подсказки - placeholder',
        template: '<input type="email" ___="Введите email">',
        blanks: ['placeholder'],
        blankLabels: ['атрибут'],
        expected: '<input type="email" placeholder="Введите email">',
        xp: 15
    },
    {
        id: 'html-27',
        module: 'Формы',
        title: 'Кнопка',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;button&gt; создаёт кнопку.',
        task: 'Впиши название тега для кнопки',
        hint: 'Тег кнопки - button',
        template: '<[[TAG]] type="submit">Отправить</[[TAG]]>',
        blanks: ['button'],
        blankLabels: ['тег'],
        expected: '<button type="submit">Отправить</button>',
        xp: 15
    },
    {
        id: 'html-28',
        module: 'Формы',
        title: 'Чекбокс',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тип checkbox создаёт флажок для выбора.',
        task: 'Впиши тип для чекбокса',
        hint: 'Тип флажка - checkbox',
        template: '<input type="___"> Согласен',
        blanks: ['checkbox'],
        blankLabels: ['тип'],
        expected: '<input type="checkbox"> Согласен',
        xp: 15
    },
    {
        id: 'html-29',
        module: 'Формы',
        title: 'Обязательное поле',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Атрибут required делает поле обязательным.',
        task: 'Впиши название атрибута для обязательного поля',
        hint: 'Атрибут - required',
        template: '<input type="text" ___>',
        blanks: ['required'],
        blankLabels: ['атрибут'],
        expected: '<input type="text" required>',
        xp: 15
    },
    {
        id: 'html-30',
        module: 'Формы',
        title: 'Текстовая область',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;textarea&gt; создаёт многострочное поле ввода.',
        task: 'Впиши название тега для текстовой области',
        hint: 'Тег - textarea',
        template: '<[[TAG]]>Текст...</[[TAG]]>',
        blanks: ['textarea'],
        blankLabels: ['тег'],
        expected: '<textarea>Текст...</textarea>',
        xp: 15
    },

    // ===== Module 6: Semantic HTML =====
    {
        id: 'html-31',
        module: 'Семантика',
        title: 'Шапка страницы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;header&gt; обозначает шапку страницы.',
        task: 'Впиши название тега для шапки',
        hint: 'Тег шапки - header',
        template: '<[[TAG]]><h1>Мой сайт</h1></[[TAG]]>',
        blanks: ['header'],
        blankLabels: ['тег'],
        expected: '<header><h1>Мой сайт</h1></header>',
        xp: 15
    },
    {
        id: 'html-32',
        module: 'Семантика',
        title: 'Навигация',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;nav&gt; обозначает навигационное меню.',
        task: 'Впиши название тега для навигации',
        hint: 'Тег навигации - nav',
        template: '<[[TAG]]><a href="/">Главная</a></[[TAG]]>',
        blanks: ['nav'],
        blankLabels: ['тег'],
        expected: '<nav><a href="/">Главная</a></nav>',
        xp: 15
    },
    {
        id: 'html-33',
        module: 'Семантика',
        title: 'Основной контент',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;main&gt; содержит основной контент страницы.',
        task: 'Впиши название тега для основного контента',
        hint: 'Тег основного контента - main',
        template: '<[[TAG]]><h1>Статья</h1><p>Текст...</p></[[TAG]]>',
        blanks: ['main'],
        blankLabels: ['тег'],
        expected: '<main><h1>Статья</h1><p>Текст...</p></main>',
        xp: 15
    },
    {
        id: 'html-34',
        module: 'Семантика',
        title: 'Статья',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;article&gt; обозначает независимую статью или пост.',
        task: 'Впиши название тега для статьи',
        hint: 'Тег статьи - article',
        template: '<[[TAG]]><h2>Новость</h2><p>Текст...</p></[[TAG]]>',
        blanks: ['article'],
        blankLabels: ['тег'],
        expected: '<article><h2>Новость</h2><p>Текст...</p></article>',
        xp: 15
    },
    {
        id: 'html-35',
        module: 'Семантика',
        title: 'Подвал страницы',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тег &lt;footer&gt; обозначает подвал страницы.',
        task: 'Впиши название тега для подвала',
        hint: 'Тег подвала - footer',
        template: '<[[TAG]]><p>© 2024</p></[[TAG]]>',
        blanks: ['footer'],
        blankLabels: ['тег'],
        expected: '<footer><p>© 2024</p></footer>',
        xp: 15
    }
];

// Make available globally
window.htmlLevels = htmlLevels;
