/**
 * JavaScript Levels for CodeQuest
 * Theme: Space / Astronaut
 */

const jsLevels = [
    // ===== Module 1: Basics =====
    {
        id: 'js-01',
        module: 'Основы JavaScript',
        title: 'Первый вывод',
        difficulty: 1,
        type: 'fill-blank',
        description: 'console.log() выводит сообщение в консоль. Это основной инструмент отладки.',
        task: 'Выведи "Привет, мир!" в консоль',
        hint: 'Используй console.log() с текстом в кавычках',
        template: 'console.___(\"Привет, мир!\");',
        blanks: ['log'],
        expected: 'console.log(\"Привет, мир!\");',
        xp: 10
    },
    {
        id: 'js-02',
        module: 'Основы JavaScript',
        title: 'Переменная let',
        difficulty: 1,
        type: 'fill-blank',
        description: 'let создаёт переменную, значение которой можно изменить.',
        task: 'Создай переменную name со значением "Космонавт"',
        hint: 'let имя = значение',
        template: '___ name = \"Космонавт\";',
        blanks: ['let'],
        expected: 'let name = \"Космонавт\";',
        xp: 10
    },
    {
        id: 'js-03',
        module: 'Основы JavaScript',
        title: 'Константа const',
        difficulty: 1,
        type: 'fill-blank',
        description: 'const создаёт константу - переменную, которую нельзя переназначить.',
        task: 'Создай константу PI со значением 3.14',
        hint: 'const имя = значение',
        template: '___ PI = 3.14;',
        blanks: ['const'],
        expected: 'const PI = 3.14;',
        xp: 10
    },
    {
        id: 'js-04',
        module: 'Основы JavaScript',
        title: 'Строки',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Строки заключаются в кавычки: одинарные, двойные или обратные.',
        task: 'Создай строку "Hello" с двойными кавычками',
        hint: 'Используй двойные кавычки "..."',
        template: 'let greeting = ___Hello___;',
        blanks: ['\"', '\"'],
        expected: 'let greeting = \"Hello\";',
        xp: 10
    },
    {
        id: 'js-05',
        module: 'Основы JavaScript',
        title: 'Числа',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Числа в JavaScript могут быть целыми или дробными.',
        task: 'Сложи два числа: 5 и 3',
        hint: 'Используй оператор +',
        template: 'let sum = 5 ___ 3;',
        blanks: ['+'],
        expected: 'let sum = 5 + 3;',
        xp: 10
    },
    {
        id: 'js-06',
        module: 'Основы JavaScript',
        title: 'Арифметика',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Операторы: + сложение, - вычитание, * умножение, / деление.',
        task: 'Умножь 6 на 7',
        hint: 'Используй оператор *',
        template: 'let result = 6 ___ 7;',
        blanks: ['*'],
        expected: 'let result = 6 * 7;',
        xp: 10
    },
    {
        id: 'js-07',
        module: 'Основы JavaScript',
        title: 'Остаток от деления',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Оператор % возвращает остаток от деления.',
        task: 'Найди остаток от деления 10 на 3',
        hint: 'Используй оператор %',
        template: 'let remainder = 10 ___ 3;',
        blanks: ['%'],
        expected: 'let remainder = 10 % 3;',
        xp: 15
    },
    {
        id: 'js-08',
        module: 'Основы JavaScript',
        title: 'Шаблонные строки',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Обратные кавычки `` позволяют вставлять переменные через ${}.',
        task: 'Вставь переменную name в строку',
        hint: 'Используй ${name} внутри ``',
        template: 'let name = \"Космонавт\";\nlet message = `Привет, ___name___!`;',
        blanks: ['${', '}'],
        expected: 'let name = \"Космонавт\";\nlet message = `Привет, ${name}!`;',
        xp: 15
    },
    {
        id: 'js-09',
        module: 'Основы JavaScript',
        title: 'Typeof',
        difficulty: 2,
        type: 'fill-blank',
        description: 'typeof возвращает тип данных переменной.',
        task: 'Узнай тип переменной x',
        hint: 'typeof переменная',
        template: 'let x = 42;\nconsole.log(___ x);',
        blanks: ['typeof'],
        expected: 'let x = 42;\nconsole.log(typeof x);',
        xp: 15
    },
    {
        id: 'js-10',
        module: 'Основы JavaScript',
        title: 'Конкатенация',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Оператор + соединяет строки вместе.',
        task: 'Соедини две строки',
        hint: 'Строка1 + строка2',
        template: 'let full = \"Hello\" ___ \" World\";',
        blanks: ['+'],
        expected: 'let full = \"Hello\" + \" World\";',
        xp: 10
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 1
    {
        id: 'js-10-challenge',
        module: 'Основы JavaScript',
        title: '🏆 Контрольное: Переменные и вычисления',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Используй все знания из модуля "Основы JavaScript":<br>• Создание констант (<code>const</code>)<br>• Арифметические операции (<code>*</code>)<br>• Шаблонные строки (<code>${}</code>)<br>• Вывод в консоль (<code>console.log</code>)<br><br>Вычисли площадь прямоугольника!',
        task: 'Создай константы width и height, вычисли площадь, выведи результат в шаблонной строке',
        hint: 'const, умножение *, шаблонная строка `${}`',
        template: '___ width = 10;\nconst height = 5;\nconst area = width ___ height;\nconsole.___(`Площадь: ___area___`);',
        blanks: ['const', '*', 'log', '${', '}'],
        blankLabels: ['ключ.слово', 'оператор', 'метод', 'начало', 'конец'],
        expected: 'const width = 10;\nconst height = 5;\nconst area = width * height;\nconsole.log(`Площадь: ${area}`);',
        xp: 50
    },

    // ===== Module 2: Conditions =====
    {
        id: 'js-11',
        module: 'Условия',
        title: 'If statement',
        difficulty: 1,
        type: 'fill-blank',
        description: 'if выполняет код, если условие истинно (true).',
        task: 'Напиши условие: если age >= 18',
        hint: 'if (условие) { ... }',
        template: '___ (age >= 18) {\n  console.log(\"Взрослый\");\n}',
        blanks: ['if'],
        expected: 'if (age >= 18) {\n  console.log(\"Взрослый\");\n}',
        xp: 10
    },
    {
        id: 'js-12',
        module: 'Условия',
        title: 'Else',
        difficulty: 1,
        type: 'fill-blank',
        description: 'else выполняется, когда условие if ложно.',
        task: 'Добавь ветку else',
        hint: 'else { ... }',
        template: 'if (age >= 18) {\n  console.log(\"Взрослый\");\n} ___ {\n  console.log(\"Ребёнок\");\n}',
        blanks: ['else'],
        expected: 'if (age >= 18) {\n  console.log(\"Взрослый\");\n} else {\n  console.log(\"Ребёнок\");\n}',
        xp: 10
    },
    {
        id: 'js-13',
        module: 'Условия',
        title: 'Сравнение равенства',
        difficulty: 1,
        type: 'fill-blank',
        description: '=== проверяет строгое равенство (значение И тип).',
        task: 'Проверь, равно ли x числу 10',
        hint: 'Используй ===',
        template: 'if (x ___ 10) {\n  console.log(\"Равно!\");\n}',
        blanks: ['==='],
        expected: 'if (x === 10) {\n  console.log(\"Равно!\");\n}',
        xp: 10
    },
    {
        id: 'js-14',
        module: 'Условия',
        title: 'Неравенство',
        difficulty: 1,
        type: 'fill-blank',
        description: '!== проверяет, что значения НЕ равны.',
        task: 'Проверь, что status не равен "error"',
        hint: 'Используй !==',
        template: 'if (status ___ \"error\") {\n  console.log(\"Всё хорошо!\");\n}',
        blanks: ['!=='],
        expected: 'if (status !== \"error\") {\n  console.log(\"Всё хорошо!\");\n}',
        xp: 10
    },
    {
        id: 'js-15',
        module: 'Условия',
        title: 'Логическое И',
        difficulty: 2,
        type: 'fill-blank',
        description: '&& (И) - оба условия должны быть true.',
        task: 'Проверь, что age >= 18 И hasLicense === true',
        hint: 'условие1 && условие2',
        template: 'if (age >= 18 ___ hasLicense === true) {\n  console.log(\"Можно водить!\");\n}',
        blanks: ['&&'],
        expected: 'if (age >= 18 && hasLicense === true) {\n  console.log(\"Можно водить!\");\n}',
        xp: 15
    },
    {
        id: 'js-16',
        module: 'Условия',
        title: 'Логическое ИЛИ',
        difficulty: 2,
        type: 'fill-blank',
        description: '|| (ИЛИ) - хотя бы одно условие должно быть true.',
        task: 'Проверь, что day === "суббота" ИЛИ day === "воскресенье"',
        hint: 'условие1 || условие2',
        template: 'if (day === \"суббота\" ___ day === \"воскресенье\") {\n  console.log(\"Выходной!\");\n}',
        blanks: ['||'],
        expected: 'if (day === \"суббота\" || day === \"воскресенье\") {\n  console.log(\"Выходной!\");\n}',
        xp: 15
    },
    {
        id: 'js-17',
        module: 'Условия',
        title: 'Тернарный оператор',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Тернарный оператор: условие ? значение_если_true : значение_если_false',
        task: 'Используй тернарный оператор для проверки age >= 18',
        hint: 'условие ? да : нет',
        template: 'let status = age >= 18 ___ \"взрослый\" : \"ребёнок\";',
        blanks: ['?'],
        expected: 'let status = age >= 18 ? \"взрослый\" : \"ребёнок\";',
        xp: 15
    },
    {
        id: 'js-18',
        module: 'Условия',
        title: 'Switch',
        difficulty: 2,
        type: 'fill-blank',
        description: 'switch проверяет переменную на несколько значений.',
        task: 'Создай switch для переменной color',
        hint: 'switch (переменная) { case ... }',
        template: '___(color) {\n  case \"red\":\n    console.log(\"Красный\");\n    break;\n}',
        blanks: ['switch'],
        expected: 'switch(color) {\n  case \"red\":\n    console.log(\"Красный\");\n    break;\n}',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 2
    {
        id: 'js-18-challenge',
        module: 'Условия',
        title: '🏆 Контрольное: Проверка доступа',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Создай проверку доступа к системе:<br>• Условие if (<code>if</code>)<br>• Логическое И (<code>&&</code>)<br>• Сравнение (<code>===</code>, <code>>=</code>)<br>• Ветка else<br><br>Проверь возраст И наличие пароля!',
        task: 'Если age >= 18 И password === "secret", выведи "Доступ разрешён", иначе "Доступ запрещён"',
        hint: 'if с условием &&, else',
        template: '___ (age >= 18 ___ password ___ \"secret\") {\n  console.log(\"Доступ разрешён\");\n} ___ {\n  console.log(\"Доступ запрещён\");\n}',
        blanks: ['if', '&&', '===', 'else'],
        blankLabels: ['условие', 'логич.И', 'сравнение', 'иначе'],
        expected: 'if (age >= 18 && password === \"secret\") {\n  console.log(\"Доступ разрешён\");\n} else {\n  console.log(\"Доступ запрещён\");\n}',
        xp: 50
    },

    // ===== Module 3: Loops =====
    {
        id: 'js-19',
        module: 'Циклы',
        title: 'For loop',
        difficulty: 2,
        type: 'fill-blank',
        description: 'for (начало; условие; шаг) выполняет код заданное число раз.',
        task: 'Создай цикл от 0 до 5',
        hint: 'for (let i = 0; i < 5; i++)',
        template: '___ (let i = 0; i < 5; i++) {\n  console.log(i);\n}',
        blanks: ['for'],
        expected: 'for (let i = 0; i < 5; i++) {\n  console.log(i);\n}',
        xp: 15
    },
    {
        id: 'js-20',
        module: 'Циклы',
        title: 'While loop',
        difficulty: 2,
        type: 'fill-blank',
        description: 'while выполняется пока условие истинно.',
        task: 'Создай цикл while с условием count < 3',
        hint: 'while (условие) { ... }',
        template: 'let count = 0;\n___ (count < 3) {\n  console.log(count);\n  count++;\n}',
        blanks: ['while'],
        expected: 'let count = 0;\nwhile (count < 3) {\n  console.log(count);\n  count++;\n}',
        xp: 15
    },
    {
        id: 'js-21',
        module: 'Циклы',
        title: 'Инкремент',
        difficulty: 1,
        type: 'fill-blank',
        description: 'i++ увеличивает переменную на 1. Эквивалентно i = i + 1.',
        task: 'Увеличь переменную i на 1',
        hint: 'Используй ++',
        template: 'let i = 0;\ni___;',
        blanks: ['++'],
        expected: 'let i = 0;\ni++;',
        xp: 10
    },
    {
        id: 'js-22',
        module: 'Циклы',
        title: 'Break',
        difficulty: 2,
        type: 'fill-blank',
        description: 'break прерывает выполнение цикла досрочно.',
        task: 'Прерви цикл когда i === 3',
        hint: 'if (условие) break;',
        template: 'for (let i = 0; i < 10; i++) {\n  if (i === 3) ___;\n  console.log(i);\n}',
        blanks: ['break'],
        expected: 'for (let i = 0; i < 10; i++) {\n  if (i === 3) break;\n  console.log(i);\n}',
        xp: 15
    },
    {
        id: 'js-23',
        module: 'Циклы',
        title: 'Continue',
        difficulty: 2,
        type: 'fill-blank',
        description: 'continue пропускает текущую итерацию и переходит к следующей.',
        task: 'Пропусти итерацию когда i === 2',
        hint: 'if (условие) continue;',
        template: 'for (let i = 0; i < 5; i++) {\n  if (i === 2) ___;\n  console.log(i);\n}',
        blanks: ['continue'],
        expected: 'for (let i = 0; i < 5; i++) {\n  if (i === 2) continue;\n  console.log(i);\n}',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 3
    {
        id: 'js-23-challenge',
        module: 'Циклы',
        title: '🏆 Контрольное: Поиск в цикле',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Найди первое чётное число и останови цикл:<br>• Цикл for с условием<br>• Проверка на чётность (<code>% 2 === 0</code>)<br>• Прерывание цикла (<code>break</code>)<br>• Инкремент (<code>i++</code>)<br><br>Оптимизация циклов — важный навык!',
        task: 'Цикл от 1 до 10, найди первое чётное число (i % 2 === 0) и прерви цикл',
        hint: 'for, оператор %, break, инкремент ++',
        template: '___ (let i = 1; i <= 10; i___) {\n  if (i ___ 2 === 0) {\n    console.log(\"Найдено:\", i);\n    ___;\n  }\n}',
        blanks: ['for', '++', '%', 'break'],
        blankLabels: ['цикл', 'инкремент', 'остаток', 'прервать'],
        expected: 'for (let i = 1; i <= 10; i++) {\n  if (i % 2 === 0) {\n    console.log(\"Найдено:\", i);\n    break;\n  }\n}',
        xp: 50
    },

    // ===== Module 4: Functions =====
    {
        id: 'js-24',
        module: 'Функции',
        title: 'Объявление функции',
        difficulty: 2,
        type: 'fill-blank',
        description: 'function имя() { } создаёт именованную функцию.',
        task: 'Создай функцию sayHello',
        hint: 'function имя() { ... }',
        template: '___ sayHello() {\n  console.log(\"Привет!\");\n}',
        blanks: ['function'],
        expected: 'function sayHello() {\n  console.log(\"Привет!\");\n}',
        xp: 15
    },
    {
        id: 'js-25',
        module: 'Функции',
        title: 'Вызов функции',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Чтобы выполнить функцию, нужно её вызвать: имя().',
        task: 'Вызови функцию greet',
        hint: 'имя_функции()',
        template: 'function greet() {\n  console.log(\"Привет!\");\n}\n\ngreet___;',
        blanks: ['()'],
        expected: 'function greet() {\n  console.log(\"Привет!\");\n}\n\ngreet();',
        xp: 10
    },
    {
        id: 'js-26',
        module: 'Функции',
        title: 'Параметры',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Параметры - это переменные, которые функция принимает на вход.',
        task: 'Добавь параметр name в функцию',
        hint: 'function имя(параметр) { ... }',
        template: 'function greet(___) {\n  console.log(\"Привет, \" + name);\n}',
        blanks: ['name'],
        expected: 'function greet(name) {\n  console.log(\"Привет, \" + name);\n}',
        xp: 15
    },
    {
        id: 'js-27',
        module: 'Функции',
        title: 'Return',
        difficulty: 2,
        type: 'fill-blank',
        description: 'return возвращает значение из функции.',
        task: 'Верни сумму a и b',
        hint: 'return значение;',
        template: 'function add(a, b) {\n  ___ a + b;\n}',
        blanks: ['return'],
        expected: 'function add(a, b) {\n  return a + b;\n}',
        xp: 15
    },
    {
        id: 'js-28',
        module: 'Функции',
        title: 'Стрелочная функция',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Стрелочные функции: (параметры) => выражение',
        task: 'Создай стрелочную функцию double',
        hint: 'const имя = (x) => x * 2',
        template: 'const double = (x) ___ x * 2;',
        blanks: ['=>'],
        expected: 'const double = (x) => x * 2;',
        xp: 15
    },
    {
        id: 'js-29',
        module: 'Функции',
        title: 'Параметр по умолчанию',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Можно задать значение параметра по умолчанию.',
        task: 'Установи значение по умолчанию "Гость" для name',
        hint: 'параметр = "значение"',
        template: 'function greet(name ___ \"Гость\") {\n  console.log(\"Привет, \" + name);\n}',
        blanks: ['='],
        expected: 'function greet(name = \"Гость\") {\n  console.log(\"Привет, \" + name);\n}',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 4
    {
        id: 'js-29-challenge',
        module: 'Функции',
        title: '🏆 Контрольное: Калькулятор',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Создай функцию-калькулятор:<br>• Объявление функции (<code>function</code>)<br>• Параметры функции<br>• Возврат значения (<code>return</code>)<br>• Стрелочная функция (<code>=></code>)<br><br>Функции — основа программирования!',
        task: 'Создай функцию multiply, которая возвращает произведение a и b, затем стрелочную версию',
        hint: 'function с return, стрелочная функция =>',
        template: '___ multiply(a, b) {\n  ___ a * b;\n}\n\nconst multiplyArrow = (a, b) ___ a * b;',
        blanks: ['function', 'return', '=>'],
        blankLabels: ['объявление', 'возврат', 'стрелка'],
        expected: 'function multiply(a, b) {\n  return a * b;\n}\n\nconst multiplyArrow = (a, b) => a * b;',
        xp: 50
    },

    // ===== Module 5: Arrays =====
    {
        id: 'js-30',
        module: 'Массивы',
        title: 'Создание массива',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Массив создаётся с помощью квадратных скобок [].',
        task: 'Создай массив с числами 1, 2, 3',
        hint: '[элемент1, элемент2, ...]',
        template: 'let numbers = ___1, 2, 3___;',
        blanks: ['[', ']'],
        expected: 'let numbers = [1, 2, 3];',
        xp: 10
    },
    {
        id: 'js-31',
        module: 'Массивы',
        title: 'Доступ к элементу',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Элементы массива нумеруются с 0. arr[0] - первый элемент.',
        task: 'Получи первый элемент массива fruits',
        hint: 'массив[индекс]',
        template: 'let fruits = [\"яблоко\", \"банан\", \"апельсин\"];\nlet first = fruits___0___;',
        blanks: ['[', ']'],
        expected: 'let fruits = [\"яблоко\", \"банан\", \"апельсин\"];\nlet first = fruits[0];',
        xp: 10
    },
    {
        id: 'js-32',
        module: 'Массивы',
        title: 'Длина массива',
        difficulty: 1,
        type: 'fill-blank',
        description: 'arr.length возвращает количество элементов в массиве.',
        task: 'Получи длину массива items',
        hint: 'массив.length',
        template: 'let items = [1, 2, 3, 4, 5];\nlet count = items.___;',
        blanks: ['length'],
        expected: 'let items = [1, 2, 3, 4, 5];\nlet count = items.length;',
        xp: 10
    },
    {
        id: 'js-33',
        module: 'Массивы',
        title: 'Push',
        difficulty: 1,
        type: 'fill-blank',
        description: 'push() добавляет элемент в конец массива.',
        task: 'Добавь "груша" в конец массива fruits',
        hint: 'массив.push(элемент)',
        template: 'let fruits = [\"яблоко\", \"банан\"];\nfruits.___(\"груша\");',
        blanks: ['push'],
        expected: 'let fruits = [\"яблоко\", \"банан\"];\nfruits.push(\"груша\");',
        xp: 10
    },
    {
        id: 'js-34',
        module: 'Массивы',
        title: 'Pop',
        difficulty: 1,
        type: 'fill-blank',
        description: 'pop() удаляет и возвращает последний элемент массива.',
        task: 'Удали последний элемент из массива',
        hint: 'массив.pop()',
        template: 'let numbers = [1, 2, 3];\nlet last = numbers.___();',
        blanks: ['pop'],
        expected: 'let numbers = [1, 2, 3];\nlet last = numbers.pop();',
        xp: 10
    },
    {
        id: 'js-35',
        module: 'Массивы',
        title: 'forEach',
        difficulty: 2,
        type: 'fill-blank',
        description: 'forEach() выполняет функцию для каждого элемента массива.',
        task: 'Выведи каждый элемент массива',
        hint: 'массив.forEach(элемент => ...)',
        template: 'let nums = [1, 2, 3];\nnums.___(num => console.log(num));',
        blanks: ['forEach'],
        expected: 'let nums = [1, 2, 3];\nnums.forEach(num => console.log(num));',
        xp: 15
    },
    {
        id: 'js-36',
        module: 'Массивы',
        title: 'Map',
        difficulty: 2,
        type: 'fill-blank',
        description: 'map() создаёт новый массив, применяя функцию к каждому элементу.',
        task: 'Удвой каждый элемент массива',
        hint: 'массив.map(x => x * 2)',
        template: 'let nums = [1, 2, 3];\nlet doubled = nums.___(x => x * 2);',
        blanks: ['map'],
        expected: 'let nums = [1, 2, 3];\nlet doubled = nums.map(x => x * 2);',
        xp: 15
    },
    {
        id: 'js-37',
        module: 'Массивы',
        title: 'Filter',
        difficulty: 2,
        type: 'fill-blank',
        description: 'filter() создаёт массив из элементов, прошедших проверку.',
        task: 'Отфильтруй числа больше 2',
        hint: 'массив.filter(x => x > 2)',
        template: 'let nums = [1, 2, 3, 4];\nlet big = nums.___(x => x > 2);',
        blanks: ['filter'],
        expected: 'let nums = [1, 2, 3, 4];\nlet big = nums.filter(x => x > 2);',
        xp: 15
    },
    {
        id: 'js-38',
        module: 'Массивы',
        title: 'Find',
        difficulty: 2,
        type: 'fill-blank',
        description: 'find() возвращает первый элемент, соответствующий условию.',
        task: 'Найди первое число больше 3',
        hint: 'массив.find(x => условие)',
        template: 'let nums = [1, 2, 4, 5];\nlet found = nums.___(x => x > 3);',
        blanks: ['find'],
        expected: 'let nums = [1, 2, 4, 5];\nlet found = nums.find(x => x > 3);',
        xp: 15
    },
    {
        id: 'js-39',
        module: 'Массивы',
        title: 'Includes',
        difficulty: 1,
        type: 'fill-blank',
        description: 'includes() проверяет, есть ли элемент в массиве.',
        task: 'Проверь, есть ли "банан" в массиве',
        hint: 'массив.includes(элемент)',
        template: 'let fruits = [\"яблоко\", \"банан\"];\nlet hasBanana = fruits.___(\"банан\");',
        blanks: ['includes'],
        expected: 'let fruits = [\"яблоко\", \"банан\"];\nlet hasBanana = fruits.includes(\"банан\");',
        xp: 10
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 5
    {
        id: 'js-39-challenge',
        module: 'Массивы',
        title: '🏆 Контрольное: Обработка данных',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Обработай массив чисел:<br>• Создание массива (<code>[]</code>)<br>• Фильтрация (<code>filter</code>)<br>• Преобразование (<code>map</code>)<br>• Добавление элемента (<code>push</code>)<br><br>Методы массивов — мощнейший инструмент!',
        task: 'Отфильтруй числа > 5, удвой их через map, добавь 100 в конец',
        hint: 'filter для фильтрации, map для преобразования, push для добавления',
        template: 'let nums = [2, 6, 3, 8, 4, 10];\nlet big = nums.___(x => x > 5);\nlet doubled = big.___(x => x * 2);\ndoubled.___(100);',
        blanks: ['filter', 'map', 'push'],
        blankLabels: ['фильтр', 'преобраз.', 'добавить'],
        expected: 'let nums = [2, 6, 3, 8, 4, 10];\nlet big = nums.filter(x => x > 5);\nlet doubled = big.map(x => x * 2);\ndoubled.push(100);',
        xp: 50
    },

    // ===== Module 6: Objects =====
    {
        id: 'js-40',
        module: 'Объекты',
        title: 'Создание объекта',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Объект создаётся с помощью фигурных скобок {}.',
        task: 'Создай объект с именем и возрастом',
        hint: '{ ключ: значение }',
        template: 'let user = ___\n  name: \"Космонавт\",\n  age: 30\n___;',
        blanks: ['{', '}'],
        expected: 'let user = {\n  name: \"Космонавт\",\n  age: 30\n};',
        xp: 10
    },
    {
        id: 'js-41',
        module: 'Объекты',
        title: 'Доступ к свойству',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Доступ к свойству: объект.свойство или объект["свойство"].',
        task: 'Получи имя пользователя',
        hint: 'объект.свойство',
        template: 'let user = { name: \"Анна\", age: 25 };\nlet userName = user.___;',
        blanks: ['name'],
        expected: 'let user = { name: \"Анна\", age: 25 };\nlet userName = user.name;',
        xp: 10
    },
    {
        id: 'js-42',
        module: 'Объекты',
        title: 'Изменение свойства',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Свойства объекта можно изменять присваиванием.',
        task: 'Измени возраст пользователя на 26',
        hint: 'объект.свойство = новое_значение',
        template: 'let user = { name: \"Анна\", age: 25 };\nuser.___ = 26;',
        blanks: ['age'],
        expected: 'let user = { name: \"Анна\", age: 25 };\nuser.age = 26;',
        xp: 10
    },
    {
        id: 'js-43',
        module: 'Объекты',
        title: 'Метод объекта',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Метод - это функция, которая является свойством объекта.',
        task: 'Вызови метод greet у объекта user',
        hint: 'объект.метод()',
        template: 'let user = {\n  name: \"Космонавт\",\n  greet() { console.log(\"Привет!\"); }\n};\nuser.___();',
        blanks: ['greet'],
        expected: 'let user = {\n  name: \"Космонавт\",\n  greet() { console.log(\"Привет!\"); }\n};\nuser.greet();',
        xp: 15
    },
    {
        id: 'js-44',
        module: 'Объекты',
        title: 'This',
        difficulty: 3,
        type: 'fill-blank',
        description: 'this внутри метода ссылается на сам объект.',
        task: 'Используй this для доступа к name',
        hint: 'this.свойство',
        template: 'let user = {\n  name: \"Космонавт\",\n  sayHi() {\n    console.log(\"Привет, \" + ___.name);\n  }\n};',
        blanks: ['this'],
        expected: 'let user = {\n  name: \"Космонавт\",\n  sayHi() {\n    console.log(\"Привет, \" + this.name);\n  }\n};',
        xp: 20
    },
    {
        id: 'js-45',
        module: 'Объекты',
        title: 'Деструктуризация',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Деструктуризация извлекает свойства в отдельные переменные.',
        task: 'Извлеки name и age из объекта user',
        hint: 'const { свойство1, свойство2 } = объект',
        template: 'const user = { name: \"Космонавт\", age: 30 };\nconst ___ name, age ___ = user;',
        blanks: ['{', '}'],
        expected: 'const user = { name: \"Космонавт\", age: 30 };\nconst { name, age } = user;',
        xp: 15
    },
    {
        id: 'js-46',
        module: 'Объекты',
        title: 'Spread оператор',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Spread (...) копирует свойства объекта в новый объект.',
        task: 'Скопируй объект user в newUser',
        hint: '{ ...объект }',
        template: 'const user = { name: \"Космонавт\" };\nconst newUser = { ___user };',
        blanks: ['...'],
        expected: 'const user = { name: \"Космонавт\" };\nconst newUser = { ...user };',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 6
    {
        id: 'js-46-challenge',
        module: 'Объекты',
        title: '🏆 Контрольное: Профиль пользователя',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Работа с объектом пользователя:<br>• Создание объекта (<code>{}</code>)<br>• Метод объекта с <code>this</code><br>• Деструктуризация (<code>{ }</code>)<br>• Spread оператор (<code>...</code>)<br><br>Объекты — основа ООП в JavaScript!',
        task: 'Создай объект с методом, который использует this, затем деструктуризируй и скопируй',
        hint: 'this для доступа к свойствам, {} для деструктуризации, ... для spread',
        template: 'const user = ___\n  name: \"Космонавт\",\n  greet() { return \"Привет, \" + ___.name; }\n___;\nconst ___ name ___ = user;\nconst copy = { ___user };',
        blanks: ['{', 'this', '}', '{', '}', '...'],
        blankLabels: ['начало', 'this', 'конец', 'дестр.', 'дестр.', 'spread'],
        expected: 'const user = {\n  name: \"Космонавт\",\n  greet() { return \"Привет, \" + this.name; }\n};\nconst { name } = user;\nconst copy = { ...user };',
        xp: 50
    },

    // ===== Module 7: DOM =====
    {
        id: 'js-47',
        module: 'DOM',
        title: 'getElementById',
        difficulty: 2,
        type: 'fill-blank',
        description: 'document.getElementById() находит элемент по его id.',
        task: 'Найди элемент с id="title"',
        hint: 'document.getElementById("id")',
        template: 'const title = document.___(\"title\");',
        blanks: ['getElementById'],
        expected: 'const title = document.getElementById(\"title\");',
        xp: 15
    },
    {
        id: 'js-48',
        module: 'DOM',
        title: 'querySelector',
        difficulty: 2,
        type: 'fill-blank',
        description: 'querySelector() находит первый элемент по CSS-селектору.',
        task: 'Найди первый элемент с классом .btn',
        hint: 'document.querySelector("селектор")',
        template: 'const btn = document.___(\"___\");',
        blanks: ['querySelector', '.btn'],
        expected: 'const btn = document.querySelector(\".btn\");',
        xp: 15
    },
    {
        id: 'js-49',
        module: 'DOM',
        title: 'textContent',
        difficulty: 2,
        type: 'fill-blank',
        description: 'textContent получает или устанавливает текст элемента.',
        task: 'Измени текст элемента на "Привет!"',
        hint: 'элемент.textContent = "текст"',
        template: 'const el = document.getElementById(\"msg\");\nel.___ = \"Привет!\";',
        blanks: ['textContent'],
        expected: 'const el = document.getElementById(\"msg\");\nel.textContent = \"Привет!\";',
        xp: 15
    },
    {
        id: 'js-50',
        module: 'DOM',
        title: 'innerHTML',
        difficulty: 2,
        type: 'fill-blank',
        description: 'innerHTML получает или устанавливает HTML-содержимое элемента.',
        task: 'Вставь HTML "<strong>Важно!</strong>" в элемент',
        hint: 'элемент.innerHTML = "HTML"',
        template: 'const el = document.getElementById(\"content\");\nel.___ = \"<strong>Важно!</strong>\";',
        blanks: ['innerHTML'],
        expected: 'const el = document.getElementById(\"content\");\nel.innerHTML = \"<strong>Важно!</strong>\";',
        xp: 15
    },
    {
        id: 'js-51',
        module: 'DOM',
        title: 'classList.add',
        difficulty: 2,
        type: 'fill-blank',
        description: 'classList.add() добавляет класс к элементу.',
        task: 'Добавь класс "active" к кнопке',
        hint: 'элемент.classList.add("класс")',
        template: 'const btn = document.querySelector(\".btn\");\nbtn.classList.___(\"active\");',
        blanks: ['add'],
        expected: 'const btn = document.querySelector(\".btn\");\nbtn.classList.add(\"active\");',
        xp: 15
    },
    {
        id: 'js-52',
        module: 'DOM',
        title: 'classList.remove',
        difficulty: 2,
        type: 'fill-blank',
        description: 'classList.remove() удаляет класс у элемента.',
        task: 'Удали класс "hidden" у элемента',
        hint: 'элемент.classList.remove("класс")',
        template: 'const modal = document.querySelector(\".modal\");\nmodal.classList.___(\"hidden\");',
        blanks: ['remove'],
        expected: 'const modal = document.querySelector(\".modal\");\nmodal.classList.remove(\"hidden\");',
        xp: 15
    },
    {
        id: 'js-53',
        module: 'DOM',
        title: 'classList.toggle',
        difficulty: 2,
        type: 'fill-blank',
        description: 'classList.toggle() переключает класс: добавляет если нет, удаляет если есть.',
        task: 'Переключи класс "dark" у body',
        hint: 'элемент.classList.toggle("класс")',
        template: 'document.body.classList.___(\"dark\");',
        blanks: ['toggle'],
        expected: 'document.body.classList.toggle(\"dark\");',
        xp: 15
    },
    {
        id: 'js-54',
        module: 'DOM',
        title: 'style',
        difficulty: 2,
        type: 'fill-blank',
        description: 'element.style изменяет инлайновые стили элемента.',
        task: 'Измени цвет фона на синий',
        hint: 'элемент.style.backgroundColor = "цвет"',
        template: 'const box = document.querySelector(\".box\");\nbox.style.___ = \"blue\";',
        blanks: ['backgroundColor'],
        expected: 'const box = document.querySelector(\".box\");\nbox.style.backgroundColor = \"blue\";',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 7
    {
        id: 'js-54-challenge',
        module: 'DOM',
        title: '🏆 Контрольное: Манипуляция DOM',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Полная работа с DOM:<br>• Поиск элемента (<code>querySelector</code>)<br>• Изменение текста (<code>textContent</code>)<br>• Добавление класса (<code>classList.add</code>)<br>• Изменение стилей (<code>style</code>)<br><br>DOM — связь JavaScript и HTML!',
        task: 'Найди элемент .card, измени текст, добавь класс active, установи красный фон',
        hint: 'querySelector, textContent, classList.add, style.backgroundColor',
        template: 'const card = document.___(\"___\");\ncard.___ = \"Новый текст\";\ncard.classList.___(\"active\");\ncard.style.___ = \"red\";',
        blanks: ['querySelector', '.card', 'textContent', 'add', 'backgroundColor'],
        blankLabels: ['метод', 'селектор', 'текст', 'добавить', 'стиль'],
        expected: 'const card = document.querySelector(\".card\");\ncard.textContent = \"Новый текст\";\ncard.classList.add(\"active\");\ncard.style.backgroundColor = \"red\";',
        xp: 50
    },

    // ===== Module 8: Events =====
    {
        id: 'js-55',
        module: 'События',
        title: 'addEventListener',
        difficulty: 2,
        type: 'fill-blank',
        description: 'addEventListener() привязывает обработчик к событию.',
        task: 'Добавь обработчик клика на кнопку',
        hint: 'элемент.addEventListener("событие", функция)',
        template: 'const btn = document.querySelector(\".btn\");\nbtn.___(\"click\", () => {\n  console.log(\"Клик!\");\n});',
        blanks: ['addEventListener'],
        expected: 'const btn = document.querySelector(\".btn\");\nbtn.addEventListener(\"click\", () => {\n  console.log(\"Клик!\");\n});',
        xp: 15
    },
    {
        id: 'js-56',
        module: 'События',
        title: 'Event click',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Событие "click" срабатывает при клике мышью.',
        task: 'Укажи тип события для клика',
        hint: 'Событие клика: "click"',
        template: 'btn.addEventListener(\"___\", handleClick);',
        blanks: ['click'],
        expected: 'btn.addEventListener(\"click\", handleClick);',
        xp: 15
    },
    {
        id: 'js-57',
        module: 'События',
        title: 'Event input',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Событие "input" срабатывает при изменении значения поля ввода.',
        task: 'Отслеживай ввод в текстовое поле',
        hint: 'Событие ввода: "input"',
        template: 'const input = document.querySelector(\"input\");\ninput.addEventListener(\"___\", (e) => {\n  console.log(e.target.value);\n});',
        blanks: ['input'],
        expected: 'const input = document.querySelector(\"input\");\ninput.addEventListener(\"input\", (e) => {\n  console.log(e.target.value);\n});',
        xp: 15
    },
    {
        id: 'js-58',
        module: 'События',
        title: 'event.target',
        difficulty: 2,
        type: 'fill-blank',
        description: 'event.target - элемент, на котором произошло событие.',
        task: 'Получи элемент, на который кликнули',
        hint: 'e.target',
        template: 'document.addEventListener(\"click\", (e) => {\n  console.log(e.___);\n});',
        blanks: ['target'],
        expected: 'document.addEventListener(\"click\", (e) => {\n  console.log(e.target);\n});',
        xp: 15
    },
    {
        id: 'js-59',
        module: 'События',
        title: 'preventDefault',
        difficulty: 2,
        type: 'fill-blank',
        description: 'preventDefault() отменяет действие по умолчанию (например, отправку формы).',
        task: 'Отмени отправку формы',
        hint: 'e.preventDefault()',
        template: 'form.addEventListener(\"submit\", (e) => {\n  e.___();\n  // обработка формы\n});',
        blanks: ['preventDefault'],
        expected: 'form.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  // обработка формы\n});',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 8
    {
        id: 'js-59-challenge',
        module: 'События',
        title: '🏆 Контрольное: Интерактивная форма',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Создай обработку формы:<br>• Подписка на событие (<code>addEventListener</code>)<br>• Отмена действия (<code>preventDefault</code>)<br>• Получение значения (<code>e.target</code>)<br>• Событие отправки (<code>submit</code>)<br><br>События — интерактивность веб-приложений!',
        task: 'Подпишись на submit формы, отмени отправку, получи значение из e.target.email.value',
        hint: 'addEventListener, submit, preventDefault, e.target',
        template: 'form.___(\"___\", (e) => {\n  e.___();\n  const email = e.___.email.value;\n  console.log(email);\n});',
        blanks: ['addEventListener', 'submit', 'preventDefault', 'target'],
        blankLabels: ['метод', 'событие', 'отмена', 'цель'],
        expected: 'form.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const email = e.target.email.value;\n  console.log(email);\n});',
        xp: 50
    },

    // ===== Module 9: Async =====
    {
        id: 'js-60',
        module: 'Асинхронность',
        title: 'setTimeout',
        difficulty: 2,
        type: 'fill-blank',
        description: 'setTimeout() выполняет код через заданное время (в миллисекундах).',
        task: 'Выполни функцию через 2 секунды',
        hint: 'setTimeout(функция, время_в_мс)',
        template: '___(()  => {\n  console.log(\"Прошло 2 секунды!\");\n}, 2000);',
        blanks: ['setTimeout'],
        expected: 'setTimeout(() => {\n  console.log(\"Прошло 2 секунды!\");\n}, 2000);',
        xp: 15
    },
    {
        id: 'js-61',
        module: 'Асинхронность',
        title: 'setInterval',
        difficulty: 2,
        type: 'fill-blank',
        description: 'setInterval() выполняет код регулярно с заданным интервалом.',
        task: 'Выполняй функцию каждую секунду',
        hint: 'setInterval(функция, интервал)',
        template: '___(()  => {\n  console.log(\"Тик\");\n}, 1000);',
        blanks: ['setInterval'],
        expected: 'setInterval(() => {\n  console.log(\"Тик\");\n}, 1000);',
        xp: 15
    },
    {
        id: 'js-62',
        module: 'Асинхронность',
        title: 'Promise',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Promise - объект, представляющий отложенное или асинхронное вычисление.',
        task: 'Создай Promise',
        hint: 'new Promise((resolve, reject) => { ... })',
        template: 'const promise = new ___((resolve, reject) => {\n  resolve(\"Успех!\");\n});',
        blanks: ['Promise'],
        expected: 'const promise = new Promise((resolve, reject) => {\n  resolve(\"Успех!\");\n});',
        xp: 20
    },
    {
        id: 'js-63',
        module: 'Асинхронность',
        title: '.then()',
        difficulty: 2,
        type: 'fill-blank',
        description: '.then() обрабатывает успешный результат Promise.',
        task: 'Обработай успешный результат промиса',
        hint: 'promise.then(result => ...)',
        template: 'fetch(\"/api/data\")\n  .___(data => console.log(data));',
        blanks: ['then'],
        expected: 'fetch(\"/api/data\")\n  .then(data => console.log(data));',
        xp: 15
    },
    {
        id: 'js-64',
        module: 'Асинхронность',
        title: '.catch()',
        difficulty: 2,
        type: 'fill-blank',
        description: '.catch() обрабатывает ошибки Promise.',
        task: 'Обработай ошибку промиса',
        hint: 'promise.catch(error => ...)',
        template: 'fetch(\"/api/data\")\n  .then(data => console.log(data))\n  .___(err => console.error(err));',
        blanks: ['catch'],
        expected: 'fetch(\"/api/data\")\n  .then(data => console.log(data))\n  .catch(err => console.error(err));',
        xp: 15
    },
    {
        id: 'js-65',
        module: 'Асинхронность',
        title: 'async/await',
        difficulty: 3,
        type: 'fill-blank',
        description: 'async/await - синтаксис для работы с Promise более читабельно.',
        task: 'Создай async функцию',
        hint: 'async function имя() { await ... }',
        template: '___ function fetchData() {\n  const data = await fetch(\"/api\");\n  return data;\n}',
        blanks: ['async'],
        expected: 'async function fetchData() {\n  const data = await fetch(\"/api\");\n  return data;\n}',
        xp: 20
    },
    {
        id: 'js-66',
        module: 'Асинхронность',
        title: 'await',
        difficulty: 3,
        type: 'fill-blank',
        description: 'await приостанавливает выполнение до завершения Promise.',
        task: 'Дождись результата fetch',
        hint: 'await promise',
        template: 'async function getData() {\n  const response = ___ fetch(\"/api\");\n  return response.json();\n}',
        blanks: ['await'],
        expected: 'async function getData() {\n  const response = await fetch(\"/api\");\n  return response.json();\n}',
        xp: 20
    },
    {
        id: 'js-67',
        module: 'Асинхронность',
        title: 'fetch',
        difficulty: 2,
        type: 'fill-blank',
        description: 'fetch() делает HTTP-запрос и возвращает Promise.',
        task: 'Сделай GET-запрос к API',
        hint: 'fetch(url)',
        template: '___(\"/api/users\")\n  .then(response => response.json())\n  .then(data => console.log(data));',
        blanks: ['fetch'],
        expected: 'fetch(\"/api/users\")\n  .then(response => response.json())\n  .then(data => console.log(data));',
        xp: 15
    },
    {
        id: 'js-68',
        module: 'Асинхронность',
        title: 'response.json()',
        difficulty: 2,
        type: 'fill-blank',
        description: 'response.json() парсит ответ как JSON.',
        task: 'Преобразуй ответ в JSON',
        hint: 'response.json()',
        template: 'fetch(\"/api\")\n  .then(response => response.___())\n  .then(data => console.log(data));',
        blanks: ['json'],
        expected: 'fetch(\"/api\")\n  .then(response => response.json())\n  .then(data => console.log(data));',
        xp: 15
    },
    {
        id: 'js-69',
        module: 'Асинхронность',
        title: 'try/catch',
        difficulty: 2,
        type: 'fill-blank',
        description: 'try/catch позволяет обрабатывать ошибки в async функциях.',
        task: 'Оберни код в try/catch',
        hint: 'try { ... } catch (error) { ... }',
        template: 'async function fetchData() {\n  ___ {\n    const data = await fetch(\"/api\");\n    return data.json();\n  } catch (error) {\n    console.error(error);\n  }\n}',
        blanks: ['try'],
        expected: 'async function fetchData() {\n  try {\n    const data = await fetch(\"/api\");\n    return data.json();\n  } catch (error) {\n    console.error(error);\n  }\n}',
        xp: 15
    },
    {
        id: 'js-70',
        module: 'Асинхронность',
        title: 'JSON.stringify',
        difficulty: 2,
        type: 'fill-blank',
        description: 'JSON.stringify() преобразует объект в JSON-строку.',
        task: 'Преобразуй объект в JSON-строку',
        hint: 'JSON.stringify(объект)',
        template: 'const user = { name: \"Космонавт\" };\nconst json = JSON.___(user);',
        blanks: ['stringify'],
        expected: 'const user = { name: \"Космонавт\" };\nconst json = JSON.stringify(user);',
        xp: 15
    },
    // 🏆 ФИНАЛЬНОЕ КОНТРОЛЬНОЕ ЗАДАНИЕ JS
    {
        id: 'js-70-challenge',
        module: 'Асинхронность',
        title: '🏆 Финальное: API запрос',
        difficulty: 5,
        type: 'fill-blank',
        description: '<strong>🏆 ФИНАЛЬНОЕ КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Создай полноценный API-запрос:<br>• Асинхронная функция (<code>async</code>)<br>• Ожидание результата (<code>await</code>)<br>• HTTP-запрос (<code>fetch</code>)<br>• Парсинг JSON (<code>.json()</code>)<br>• Обработка ошибок (<code>try/catch</code>)<br><br>🎉 Поздравляем с завершением курса JavaScript!',
        task: 'Создай async функцию, которая делает fetch запрос, парсит JSON и обрабатывает ошибки',
        hint: 'async, await, fetch, .json(), try/catch',
        template: '___ function loadData() {\n  ___ {\n    const response = ___ ___(\"http://localhost:5000/api\");\n    const data = await response.___();\n    return data;\n  } catch (error) {\n    console.error(error);\n  }\n}',
        blanks: ['async', 'try', 'await', 'fetch', 'json'],
        blankLabels: ['асинхр.', 'попытка', 'ожидание', 'запрос', 'парсинг'],
        expected: 'async function loadData() {\n  try {\n    const response = await fetch(\"http://localhost:5000/api\");\n    const data = await response.json();\n    return data;\n  } catch (error) {\n    console.error(error);\n  }\n}',
        xp: 75
    }
];

// Make available globally
window.jsLevels = jsLevels;
