/**
 * Node.js Backend Course Levels
 * 45 levels covering Node.js fundamentals to building APIs
 */

window.nodeLevels = [
    // === Module 1: Node.js Basics (Levels 1-10) ===
    {
        id: 'node-1',
        title: 'console.log в Node',
        description: 'В Node.js мы тоже используем console.log для вывода.',
        task: 'Выведи сообщение в консоль',
        type: 'fill-blank',
        template: '[[METHOD]]("Hello from Node.js!");',
        blanks: ['console.log'],
        blankLabels: ['метод'],
        hint: 'Тот же console.log что и в браузере',
        xp: 10,
        difficulty: 1
    },
    {
        id: 'node-2',
        title: 'Переменные окружения',
        description: 'process.env содержит переменные окружения.',
        task: 'Получи переменную окружения NODE_ENV',
        type: 'fill-blank',
        template: 'const env = [[OBJ]].env.NODE_ENV;',
        blanks: ['process'],
        blankLabels: ['объект'],
        hint: 'process - глобальный объект Node.js',
        xp: 15,
        difficulty: 1
    },
    {
        id: 'node-3',
        title: 'Require модуля',
        description: 'require() загружает модули в CommonJS.',
        task: 'Импортируй модуль fs',
        type: 'fill-blank',
        template: 'const fs = [[FUNC]]("fs");',
        blanks: ['require'],
        blankLabels: ['функция'],
        hint: 'require загружает модуль',
        xp: 15,
        difficulty: 1
    },
    {
        id: 'node-4',
        title: 'ES Modules import',
        description: 'В современном Node.js можно использовать import.',
        task: 'Импортируй fs используя ES modules',
        type: 'fill-blank',
        template: '[[KEYWORD]] fs from "fs";',
        blanks: ['import'],
        blankLabels: ['ключевое слово'],
        hint: 'import - синтаксис ES modules',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'node-5',
        title: 'Export модуля',
        description: 'module.exports экспортирует из модуля.',
        task: 'Экспортируй функцию greet',
        type: 'fill-blank',
        template: 'function greet(name) {\n  return `Hello, ${name}!`;\n}\n\n[[OBJ]].exports = greet;',
        blanks: ['module'],
        blankLabels: ['объект'],
        hint: 'module.exports для CommonJS экспорта',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'node-6',
        title: 'Named exports',
        description: 'Можно экспортировать несколько значений.',
        task: 'Экспортируй add и subtract',
        type: 'fill-blank',
        template: 'const add = (a, b) => a + b;\nconst subtract = (a, b) => a - b;\n\nmodule.exports = { [[PROPS]] };',
        blanks: ['add, subtract'],
        blankLabels: ['свойства'],
        hint: 'Перечисли функции через запятую',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'node-7',
        title: 'ES Module export',
        description: 'export default для основного экспорта.',
        task: 'Экспортируй функцию по умолчанию',
        type: 'fill-blank',
        template: 'function processData(data) {\n  return data.map(x => x * 2);\n}\n\nexport [[KEYWORD]] processData;',
        blanks: ['default'],
        blankLabels: ['ключевое слово'],
        hint: 'default для экспорта по умолчанию',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'node-8',
        title: '__dirname',
        description: '__dirname содержит путь к текущей директории.',
        task: 'Выведи текущую директорию',
        type: 'fill-blank',
        template: 'console.log([[VAR]]);',
        blanks: ['__dirname'],
        blankLabels: ['переменная'],
        hint: '__dirname - путь к папке файла',
        xp: 15,
        difficulty: 1
    },
    {
        id: 'node-9',
        title: '__filename',
        description: '__filename содержит полный путь к файлу.',
        task: 'Выведи путь к текущему файлу',
        type: 'fill-blank',
        template: 'console.log([[VAR]]);',
        blanks: ['__filename'],
        blankLabels: ['переменная'],
        hint: '__filename - полный путь к файлу',
        xp: 15,
        difficulty: 1
    },
    {
        id: 'node-10',
        title: 'Аргументы командной строки',
        description: 'process.argv содержит аргументы CLI.',
        task: 'Получи аргументы командной строки',
        type: 'fill-blank',
        template: 'const args = process.[[PROP]];\nconsole.log(args);',
        blanks: ['argv'],
        blankLabels: ['свойство'],
        hint: 'argv - массив аргументов',
        xp: 20,
        difficulty: 2
    },

    // === Module 2: File System (Levels 11-20) ===
    {
        id: 'node-11',
        title: 'Чтение файла (sync)',
        description: 'readFileSync читает файл синхронно.',
        task: 'Прочитай файл синхронно',
        type: 'fill-blank',
        template: 'const fs = require("fs");\nconst data = fs.[[METHOD]]("file.txt", "utf8");',
        blanks: ['readFileSync'],
        blankLabels: ['метод'],
        hint: 'Sync методы блокируют выполнение',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'node-12',
        title: 'Чтение файла (async)',
        description: 'readFile читает файл асинхронно.',
        task: 'Прочитай файл асинхронно',
        type: 'fill-blank',
        template: 'const fs = require("fs");\n\nfs.[[METHOD]]("file.txt", "utf8", (err, data) => {\n  if (err) throw err;\n  console.log(data);\n});',
        blanks: ['readFile'],
        blankLabels: ['метод'],
        hint: 'Асинхронный метод принимает callback',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-13',
        title: 'Запись в файл',
        description: 'writeFile записывает данные в файл.',
        task: 'Запиши текст в файл',
        type: 'fill-blank',
        template: 'const fs = require("fs");\n\nfs.[[METHOD]]("output.txt", "Hello!", (err) => {\n  if (err) throw err;\n  console.log("File saved!");\n});',
        blanks: ['writeFile'],
        blankLabels: ['метод'],
        hint: 'writeFile создаёт или перезаписывает файл',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-14',
        title: 'Добавление в файл',
        description: 'appendFile добавляет данные в конец файла.',
        task: 'Добавь текст в конец файла',
        type: 'fill-blank',
        template: 'const fs = require("fs");\n\nfs.[[METHOD]]("log.txt", "New log entry\\n", (err) => {\n  if (err) throw err;\n});',
        blanks: ['appendFile'],
        blankLabels: ['метод'],
        hint: 'appendFile не перезаписывает файл',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-15',
        title: 'Проверка существования',
        description: 'existsSync проверяет существует ли файл.',
        task: 'Проверь существование файла',
        type: 'fill-blank',
        template: 'const fs = require("fs");\n\nif (fs.[[METHOD]]("config.json")) {\n  console.log("Config exists!");\n}',
        blanks: ['existsSync'],
        blankLabels: ['метод'],
        hint: 'existsSync возвращает boolean',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'node-16',
        title: 'Создание директории',
        description: 'mkdir создаёт директорию.',
        task: 'Создай папку uploads',
        type: 'fill-blank',
        template: 'const fs = require("fs");\n\nfs.[[METHOD]]("uploads", { recursive: true }, (err) => {\n  if (err) throw err;\n});',
        blanks: ['mkdir'],
        blankLabels: ['метод'],
        hint: 'mkdir создаёт папку',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-17',
        title: 'Чтение директории',
        description: 'readdir возвращает список файлов.',
        task: 'Получи список файлов в папке',
        type: 'fill-blank',
        template: 'const fs = require("fs");\n\nfs.[[METHOD]]("./src", (err, files) => {\n  console.log(files);\n});',
        blanks: ['readdir'],
        blankLabels: ['метод'],
        hint: 'readdir возвращает массив имён файлов',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-18',
        title: 'FS Promises',
        description: 'fs.promises для работы с Promise API.',
        task: 'Используй промисы для чтения файла',
        type: 'fill-blank',
        template: 'const fs = require("fs").[[PROP]];\n\nasync function readConfig() {\n  const data = await fs.readFile("config.json", "utf8");\n  return JSON.parse(data);\n}',
        blanks: ['promises'],
        blankLabels: ['свойство'],
        hint: 'fs.promises для async/await',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-19',
        title: 'Path модуль',
        description: 'path помогает работать с путями.',
        task: 'Объедини пути безопасно',
        type: 'fill-blank',
        template: 'const path = require("path");\n\nconst fullPath = path.[[METHOD]](__dirname, "uploads", "file.txt");',
        blanks: ['join'],
        blankLabels: ['метод'],
        hint: 'join объединяет части пути',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-20',
        title: 'Расширение файла',
        description: 'path.extname возвращает расширение.',
        task: 'Получи расширение файла',
        type: 'fill-blank',
        template: 'const path = require("path");\n\nconst ext = path.[[METHOD]]("photo.jpg");\nconsole.log(ext); // .jpg',
        blanks: ['extname'],
        blankLabels: ['метод'],
        hint: 'extname возвращает расширение с точкой',
        xp: 20,
        difficulty: 2
    },

    // === Module 3: HTTP & Express (Levels 21-30) ===
    {
        id: 'node-21',
        title: 'HTTP сервер',
        description: 'http.createServer создаёт веб-сервер.',
        task: 'Создай HTTP сервер',
        type: 'fill-blank',
        template: 'const http = require("http");\n\nconst server = http.[[METHOD]]((req, res) => {\n  res.end("Hello World!");\n});\n\nserver.listen(3000);',
        blanks: ['createServer'],
        blankLabels: ['метод'],
        hint: 'createServer создаёт сервер',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-22',
        title: 'Ответ сервера',
        description: 'res.end отправляет ответ клиенту.',
        task: 'Отправь ответ клиенту',
        type: 'fill-blank',
        template: 'const server = http.createServer((req, res) => {\n  res.statusCode = 200;\n  res.setHeader("Content-Type", "text/plain");\n  res.[[METHOD]]("Hello World!");\n});',
        blanks: ['end'],
        blankLabels: ['метод'],
        hint: 'end завершает и отправляет ответ',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-23',
        title: 'Express приложение',
        description: 'Express - популярный фреймворк для Node.js.',
        task: 'Создай Express приложение',
        type: 'fill-blank',
        template: 'const express = require("express");\nconst app = [[FUNC]]();',
        blanks: ['express'],
        blankLabels: ['функция'],
        hint: 'express() создаёт приложение',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-24',
        title: 'GET маршрут',
        description: 'app.get определяет GET маршрут.',
        task: 'Создай GET маршрут для главной страницы',
        type: 'fill-blank',
        template: 'const express = require("express");\nconst app = express();\n\napp.[[METHOD]]("/", (req, res) => {\n  res.send("Welcome!");\n});',
        blanks: ['get'],
        blankLabels: ['метод'],
        hint: 'get для GET запросов',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-25',
        title: 'POST маршрут',
        description: 'app.post для POST запросов.',
        task: 'Создай POST маршрут для создания пользователя',
        type: 'fill-blank',
        template: 'app.[[METHOD]]("/users", (req, res) => {\n  // создание пользователя\n  res.status(201).json({ message: "User created" });\n});',
        blanks: ['post'],
        blankLabels: ['метод'],
        hint: 'post для POST запросов',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-26',
        title: 'URL параметры',
        description: 'req.params содержит параметры из URL.',
        task: 'Получи id из URL',
        type: 'fill-blank',
        template: 'app.get("/users/:id", (req, res) => {\n  const userId = req.[[PROP]].id;\n  res.send(`User ${userId}`);\n});',
        blanks: ['params'],
        blankLabels: ['свойство'],
        hint: 'params содержит параметры маршрута',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-27',
        title: 'Query параметры',
        description: 'req.query содержит query string параметры.',
        task: 'Получи параметр поиска',
        type: 'fill-blank',
        template: 'app.get("/search", (req, res) => {\n  const searchTerm = req.[[PROP]].q;\n  res.send(`Searching for: ${searchTerm}`);\n});',
        blanks: ['query'],
        blankLabels: ['свойство'],
        hint: 'query для ?key=value параметров',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-28',
        title: 'JSON middleware',
        description: 'express.json() парсит JSON тело запроса.',
        task: 'Добавь middleware для JSON',
        type: 'fill-blank',
        template: 'const express = require("express");\nconst app = express();\n\napp.use(express.[[METHOD]]());',
        blanks: ['json'],
        blankLabels: ['метод'],
        hint: 'json() парсит JSON body',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-29',
        title: 'Request body',
        description: 'req.body содержит тело POST запроса.',
        task: 'Получи данные из тела запроса',
        type: 'fill-blank',
        template: 'app.post("/users", (req, res) => {\n  const { name, email } = req.[[PROP]];\n  res.json({ name, email });\n});',
        blanks: ['body'],
        blankLabels: ['свойство'],
        hint: 'body содержит данные POST запроса',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-30',
        title: 'Запуск сервера',
        description: 'app.listen запускает сервер.',
        task: 'Запусти сервер на порту 3000',
        type: 'fill-blank',
        template: 'app.[[METHOD]](3000, () => {\n  console.log("Server running on port 3000");\n});',
        blanks: ['listen'],
        blankLabels: ['метод'],
        hint: 'listen запускает прослушивание порта',
        xp: 20,
        difficulty: 2
    },

    // === Module 4: Middleware & Error Handling (Levels 31-38) ===
    {
        id: 'node-31',
        title: 'Custom middleware',
        description: 'Middleware - функция с доступом к req, res, next.',
        task: 'Создай middleware для логирования',
        type: 'fill-blank',
        template: 'const logger = (req, res, [[PARAM]]) => {\n  console.log(`${req.method} ${req.url}`);\n  next();\n};\n\napp.use(logger);',
        blanks: ['next'],
        blankLabels: ['параметр'],
        hint: 'next() передаёт управление дальше',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-32',
        title: 'Применение middleware',
        description: 'app.use применяет middleware ко всем маршрутам.',
        task: 'Примени middleware глобально',
        type: 'fill-blank',
        template: 'app.[[METHOD]](express.json());\napp.[[METHOD]](logger);',
        blanks: ['use'],
        blankLabels: ['метод'],
        hint: 'use для глобального middleware',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-33',
        title: 'Router',
        description: 'express.Router создаёт модульные маршруты.',
        task: 'Создай роутер для users',
        type: 'fill-blank',
        template: 'const express = require("express");\nconst router = express.[[METHOD]]();\n\nrouter.get("/", (req, res) => {\n  res.json([]);\n});\n\nmodule.exports = router;',
        blanks: ['Router'],
        blankLabels: ['метод'],
        hint: 'Router() создаёт новый роутер',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-34',
        title: 'Подключение роутера',
        description: 'Подключи роутер к основному приложению.',
        task: 'Подключи userRouter к /api/users',
        type: 'fill-blank',
        template: 'const userRouter = require("./routes/users");\n\napp.[[METHOD]]("/api/users", userRouter);',
        blanks: ['use'],
        blankLabels: ['метод'],
        hint: 'use с путём подключает роутер',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-35',
        title: 'Error middleware',
        description: 'Error middleware имеет 4 параметра.',
        task: 'Создай middleware для обработки ошибок',
        type: 'fill-blank',
        template: 'app.use(([[PARAM]], req, res, next) => {\n  console.error(err.stack);\n  res.status(500).json({ error: "Something went wrong" });\n});',
        blanks: ['err'],
        blankLabels: ['параметр'],
        hint: 'Первый параметр - объект ошибки',
        xp: 35,
        difficulty: 3
    },
    {
        id: 'node-36',
        title: 'Async обработчик',
        description: 'Оберни async обработчики для отлова ошибок.',
        task: 'Создай обёртку для async',
        type: 'fill-blank',
        template: 'const asyncHandler = (fn) => (req, res, next) => {\n  [[METHOD]].resolve(fn(req, res, next)).catch(next);\n};',
        blanks: ['Promise'],
        blankLabels: ['объект'],
        hint: 'Promise.resolve для обработки async',
        xp: 40,
        difficulty: 4
    },
    {
        id: 'node-37',
        title: 'Статус ответа',
        description: 'res.status устанавливает HTTP статус.',
        task: 'Верни 404 для не найденного ресурса',
        type: 'fill-blank',
        template: 'app.get("/users/:id", (req, res) => {\n  const user = users.find(u => u.id === req.params.id);\n  if (!user) {\n    return res.[[METHOD]](404).json({ error: "Not found" });\n  }\n  res.json(user);\n});',
        blanks: ['status'],
        blankLabels: ['метод'],
        hint: 'status устанавливает код ответа',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-38',
        title: 'CORS middleware',
        description: 'CORS позволяет кросс-доменные запросы.',
        task: 'Подключи CORS',
        type: 'fill-blank',
        template: 'const cors = require("cors");\n\napp.[[METHOD]](cors());',
        blanks: ['use'],
        blankLabels: ['метод'],
        hint: 'use подключает middleware',
        xp: 25,
        difficulty: 2
    },

    // === Module 5: Database & Auth (Levels 39-45) ===
    {
        id: 'node-39',
        title: 'MongoDB подключение',
        description: 'mongoose.connect подключает к MongoDB.',
        task: 'Подключись к MongoDB',
        type: 'fill-blank',
        template: 'const mongoose = require("mongoose");\n\nmongoose.[[METHOD]]("mongodb://localhost:27017/myapp")\n  .then(() => console.log("Connected!"))\n  .catch(err => console.error(err));',
        blanks: ['connect'],
        blankLabels: ['метод'],
        hint: 'connect для подключения к базе',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-40',
        title: 'Mongoose Schema',
        description: 'Schema определяет структуру документа.',
        task: 'Создай схему пользователя',
        type: 'fill-blank',
        template: 'const mongoose = require("mongoose");\n\nconst userSchema = new mongoose.[[CLASS]]({\n  name: String,\n  email: { type: String, required: true }\n});',
        blanks: ['Schema'],
        blankLabels: ['класс'],
        hint: 'Schema определяет поля документа',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-41',
        title: 'Mongoose Model',
        description: 'model создаёт модель из схемы.',
        task: 'Создай модель User',
        type: 'fill-blank',
        template: 'const User = mongoose.[[METHOD]]("User", userSchema);\n\nmodule.exports = User;',
        blanks: ['model'],
        blankLabels: ['метод'],
        hint: 'model(name, schema) создаёт модель',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-42',
        title: 'Создание документа',
        description: 'Model.create сохраняет документ в базу.',
        task: 'Создай нового пользователя',
        type: 'fill-blank',
        template: 'app.post("/users", async (req, res) => {\n  const user = await User.[[METHOD]](req.body);\n  res.status(201).json(user);\n});',
        blanks: ['create'],
        blankLabels: ['метод'],
        hint: 'create создаёт и сохраняет документ',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'node-43',
        title: 'Поиск документов',
        description: 'Model.find возвращает массив документов.',
        task: 'Найди всех пользователей',
        type: 'fill-blank',
        template: 'app.get("/users", async (req, res) => {\n  const users = await User.[[METHOD]]();\n  res.json(users);\n});',
        blanks: ['find'],
        blankLabels: ['метод'],
        hint: 'find без аргументов возвращает все',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'node-44',
        title: 'JWT токен',
        description: 'jsonwebtoken создаёт JWT токены.',
        task: 'Создай JWT токен',
        type: 'fill-blank',
        template: 'const jwt = require("jsonwebtoken");\n\nconst token = jwt.[[METHOD]](\n  { userId: user._id },\n  process.env.JWT_SECRET,\n  { expiresIn: "1h" }\n);',
        blanks: ['sign'],
        blankLabels: ['метод'],
        hint: 'sign создаёт токен',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'node-45',
        title: 'Проверка JWT',
        description: 'jwt.verify проверяет и декодирует токен.',
        task: 'Проверь JWT токен',
        type: 'fill-blank',
        template: 'const authMiddleware = (req, res, next) => {\n  const token = req.headers.authorization?.split(" ")[1];\n  try {\n    const decoded = jwt.[[METHOD]](token, process.env.JWT_SECRET);\n    req.userId = decoded.userId;\n    next();\n  } catch {\n    res.status(401).json({ error: "Invalid token" });\n  }\n};',
        blanks: ['verify'],
        blankLabels: ['метод'],
        hint: 'verify проверяет подпись токена',
        xp: 40,
        difficulty: 4
    }
];
