/**
 * Python Levels for CodeQuest
 * Theme: Snake / Data Science
 */

const pythonLevels = [
    // ===== Module 1: Basics =====
    {
        id: 'py-01',
        module: 'Основы Python',
        title: 'Привет, Python!',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Функция <code>print()</code> выводит текст на экран. Текст нужно заключить в кавычки.',
        task: 'Выведи "Hello, World!" на экран',
        hint: 'Используй print() с текстом в кавычках',
        template: '___("Hello, World!")',
        blanks: ['print'],
        blankLabels: ['функция'],
        expected: 'print("Hello, World!")',
        xp: 10
    },
    {
        id: 'py-02',
        module: 'Основы Python',
        title: 'Переменные',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Переменная хранит данные. В Python не нужно указывать тип — он определяется автоматически.',
        task: 'Создай переменную name со значением "Python"',
        hint: 'имя_переменной = значение',
        template: '___ = "Python"',
        blanks: ['name'],
        blankLabels: ['имя'],
        expected: 'name = "Python"',
        xp: 10
    },
    {
        id: 'py-03',
        module: 'Основы Python',
        title: 'Числа',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Python поддерживает целые числа (int) и дробные (float). Числа пишутся без кавычек.',
        task: 'Создай переменную age со значением 25',
        hint: 'Число без кавычек',
        template: 'age = ___',
        blanks: ['25'],
        blankLabels: ['число'],
        expected: 'age = 25',
        xp: 10
    },
    {
        id: 'py-04',
        module: 'Основы Python',
        title: 'Арифметика',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Python умеет считать: + сложение, - вычитание, * умножение, / деление.',
        task: 'Вычисли сумму 10 + 5',
        hint: 'Оператор сложения: +',
        template: 'result = 10 ___ 5',
        blanks: ['+'],
        blankLabels: ['оператор'],
        expected: 'result = 10 + 5',
        xp: 10
    },
    {
        id: 'py-05',
        module: 'Основы Python',
        title: 'Комментарии',
        difficulty: 1,
        type: 'fill-blank',
        description: 'Комментарий начинается с # и игнорируется Python. Используй для пояснений в коде.',
        task: 'Напиши комментарий',
        hint: 'Комментарий начинается с #',
        template: '___ Это комментарий',
        blanks: ['#'],
        blankLabels: ['символ'],
        expected: '# Это комментарий',
        xp: 10
    },
    {
        id: 'py-06',
        module: 'Основы Python',
        title: 'Тип данных',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Функция <code>type()</code> показывает тип переменной: str, int, float, bool.',
        task: 'Узнай тип переменной x',
        hint: 'Функция type()',
        template: 'print(___(x))',
        blanks: ['type'],
        blankLabels: ['функция'],
        expected: 'print(type(x))',
        xp: 15
    },
    {
        id: 'py-07',
        module: 'Основы Python',
        title: 'Ввод данных',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Функция <code>input()</code> запрашивает данные у пользователя.',
        task: 'Запроси имя пользователя',
        hint: 'Функция input() с подсказкой',
        template: 'name = ___("Введите имя: ")',
        blanks: ['input'],
        blankLabels: ['функция'],
        expected: 'name = input("Введите имя: ")',
        xp: 15
    },
    {
        id: 'py-08',
        module: 'Основы Python',
        title: 'Преобразование типов',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>int()</code> преобразует в целое число, <code>str()</code> в строку, <code>float()</code> в дробное.',
        task: 'Преобразуй строку "42" в число',
        hint: 'Функция int()',
        template: 'number = ___("42")',
        blanks: ['int'],
        blankLabels: ['функция'],
        expected: 'number = int("42")',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 1
    {
        id: 'py-08-challenge',
        module: 'Основы Python',
        title: '🏆 Контрольное: Калькулятор',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Создай простой калькулятор: запроси число, преобразуй в int и удвой его.',
        task: 'Запроси число, преобразуй в int и умножь на 2',
        hint: 'input → int → умножение',
        template: 'x = ___(___(___("Число: ")))',
        blanks: ['print', 'int', 'input'],
        blankLabels: ['вывод', 'преобразование', 'ввод'],
        expected: 'print(int(input("Число: ")))',
        xp: 50
    },

    // ===== Module 2: Strings =====
    {
        id: 'py-09',
        module: 'Строки',
        title: 'Конкатенация',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Строки можно склеивать оператором <code>+</code>.',
        task: 'Склей две строки',
        hint: 'Оператор +',
        template: 'full = "Hello" ___ " World"',
        blanks: ['+'],
        blankLabels: ['оператор'],
        expected: 'full = "Hello" + " World"',
        xp: 15
    },
    {
        id: 'py-10',
        module: 'Строки',
        title: 'Длина строки',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Функция <code>len()</code> возвращает длину строки.',
        task: 'Узнай длину строки text',
        hint: 'Функция len()',
        template: 'length = ___(text)',
        blanks: ['len'],
        blankLabels: ['функция'],
        expected: 'length = len(text)',
        xp: 15
    },
    {
        id: 'py-11',
        module: 'Строки',
        title: 'Индексация',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Символы в строке нумеруются с 0. Доступ через квадратные скобки: text[0].',
        task: 'Получи первый символ строки',
        hint: 'Индекс первого элемента: 0',
        template: 'first = text[___]',
        blanks: ['0'],
        blankLabels: ['индекс'],
        expected: 'first = text[0]',
        xp: 15
    },
    {
        id: 'py-12',
        module: 'Строки',
        title: 'Верхний регистр',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Метод <code>.upper()</code> делает все буквы заглавными.',
        task: 'Преобразуй строку в верхний регистр',
        hint: 'Метод upper()',
        template: 'loud = text.___()',
        blanks: ['upper'],
        blankLabels: ['метод'],
        expected: 'loud = text.upper()',
        xp: 15
    },
    {
        id: 'py-13',
        module: 'Строки',
        title: 'Замена',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Метод <code>.replace(old, new)</code> заменяет подстроку.',
        task: 'Замени "Python" на "JavaScript"',
        hint: 'Метод replace()',
        template: 'new_text = text.___("Python", "JavaScript")',
        blanks: ['replace'],
        blankLabels: ['метод'],
        expected: 'new_text = text.replace("Python", "JavaScript")',
        xp: 20
    },
    {
        id: 'py-14',
        module: 'Строки',
        title: 'f-строки',
        difficulty: 3,
        type: 'fill-blank',
        description: 'f-строки позволяют вставлять переменные: <code>f"Hello {name}"</code>.',
        task: 'Создай f-строку с переменной age',
        hint: 'f перед кавычками, переменная в {}',
        template: 'msg = ___"Мне {age} лет"',
        blanks: ['f'],
        blankLabels: ['префикс'],
        expected: 'msg = f"Мне {age} лет"',
        xp: 20
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 2
    {
        id: 'py-14-challenge',
        module: 'Строки',
        title: '🏆 Контрольное: Обработка текста',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Преобразуй имя в верхний регистр и выведи с приветствием.',
        task: 'Выведи "HELLO, {NAME}!" где name в верхнем регистре',
        hint: 'f-строка + upper()',
        template: 'print(___"Hello, {name.___()} !")',
        blanks: ['f', 'upper'],
        blankLabels: ['префикс', 'метод'],
        expected: 'print(f"Hello, {name.upper()} !")',
        xp: 50
    },

    // ===== Module 3: Lists =====
    {
        id: 'py-15',
        module: 'Списки',
        title: 'Создание списка',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Список создаётся квадратными скобками: <code>[1, 2, 3]</code>.',
        task: 'Создай список с числами 1, 2, 3',
        hint: 'Квадратные скобки []',
        template: 'numbers = ___1, 2, 3___',
        blanks: ['[', ']'],
        blankLabels: ['открыть', 'закрыть'],
        expected: 'numbers = [1, 2, 3]',
        xp: 15
    },
    {
        id: 'py-16',
        module: 'Списки',
        title: 'Добавление элемента',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Метод <code>.append(item)</code> добавляет элемент в конец списка.',
        task: 'Добавь число 4 в список',
        hint: 'Метод append()',
        template: 'numbers.___(4)',
        blanks: ['append'],
        blankLabels: ['метод'],
        expected: 'numbers.append(4)',
        xp: 15
    },
    {
        id: 'py-17',
        module: 'Списки',
        title: 'Удаление элемента',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Метод <code>.remove(item)</code> удаляет первое вхождение элемента.',
        task: 'Удали элемент 2 из списка',
        hint: 'Метод remove()',
        template: 'numbers.___(2)',
        blanks: ['remove'],
        blankLabels: ['метод'],
        expected: 'numbers.remove(2)',
        xp: 15
    },
    {
        id: 'py-18',
        module: 'Списки',
        title: 'Срезы',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Срез <code>[start:end]</code> возвращает часть списка.',
        task: 'Получи первые 3 элемента списка',
        hint: 'Срез [:3]',
        template: 'first_three = numbers[___:___]',
        blanks: ['0', '3'],
        blankLabels: ['начало', 'конец'],
        expected: 'first_three = numbers[0:3]',
        xp: 20
    },
    {
        id: 'py-19',
        module: 'Списки',
        title: 'Сортировка',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Метод <code>.sort()</code> сортирует список по возрастанию.',
        task: 'Отсортируй список',
        hint: 'Метод sort()',
        template: 'numbers.___()',
        blanks: ['sort'],
        blankLabels: ['метод'],
        expected: 'numbers.sort()',
        xp: 15
    },
    {
        id: 'py-20',
        module: 'Списки',
        title: 'Проверка наличия',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Оператор <code>in</code> проверяет, есть ли элемент в списке.',
        task: 'Проверь, есть ли 5 в списке',
        hint: 'Оператор in',
        template: 'exists = 5 ___ numbers',
        blanks: ['in'],
        blankLabels: ['оператор'],
        expected: 'exists = 5 in numbers',
        xp: 15
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 3
    {
        id: 'py-20-challenge',
        module: 'Списки',
        title: '🏆 Контрольное: Работа со списком',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Добавь элемент, отсортируй и выведи список.',
        task: 'Добавь 0, отсортируй и выведи',
        hint: 'append → sort → print',
        template: 'nums.___(0)\nnums.___()\n___(nums)',
        blanks: ['append', 'sort', 'print'],
        blankLabels: ['добавить', 'сортировка', 'вывод'],
        expected: 'nums.append(0)\nnums.sort()\nprint(nums)',
        xp: 50
    },

    // ===== Module 4: Conditions =====
    {
        id: 'py-21',
        module: 'Условия',
        title: 'Оператор if',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Условие <code>if</code> выполняет код, если условие истинно.',
        task: 'Напиши условие: если x больше 0',
        hint: 'if условие:',
        template: '___ x > 0:\n    print("Положительное")',
        blanks: ['if'],
        blankLabels: ['оператор'],
        expected: 'if x > 0:\n    print("Положительное")',
        xp: 15
    },
    {
        id: 'py-22',
        module: 'Условия',
        title: 'Оператор else',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>else</code> выполняется, когда условие if ложно.',
        task: 'Добавь ветку else',
        hint: 'else:',
        template: 'if x > 0:\n    print("Да")\n___:\n    print("Нет")',
        blanks: ['else'],
        blankLabels: ['оператор'],
        expected: 'if x > 0:\n    print("Да")\nelse:\n    print("Нет")',
        xp: 15
    },
    {
        id: 'py-23',
        module: 'Условия',
        title: 'Оператор elif',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>elif</code> проверяет дополнительное условие.',
        task: 'Добавь проверку elif x == 0',
        hint: 'elif условие:',
        template: 'if x > 0:\n    print("+")\n___ x == 0:\n    print("0")',
        blanks: ['elif'],
        blankLabels: ['оператор'],
        expected: 'if x > 0:\n    print("+")\nelif x == 0:\n    print("0")',
        xp: 20
    },
    {
        id: 'py-24',
        module: 'Условия',
        title: 'Сравнение',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Операторы сравнения: == равно, != не равно, &lt; меньше, &gt; больше.',
        task: 'Проверь равенство a и b',
        hint: 'Оператор ==',
        template: 'if a ___ b:\n    print("Равны")',
        blanks: ['=='],
        blankLabels: ['оператор'],
        expected: 'if a == b:\n    print("Равны")',
        xp: 15
    },
    {
        id: 'py-25',
        module: 'Условия',
        title: 'Логическое И',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Оператор <code>and</code> — оба условия должны быть истинны.',
        task: 'Проверь, что x > 0 И x < 10',
        hint: 'Оператор and',
        template: 'if x > 0 ___ x < 10:\n    print("OK")',
        blanks: ['and'],
        blankLabels: ['оператор'],
        expected: 'if x > 0 and x < 10:\n    print("OK")',
        xp: 20
    },
    {
        id: 'py-26',
        module: 'Условия',
        title: 'Логическое ИЛИ',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Оператор <code>or</code> — хотя бы одно условие истинно.',
        task: 'Проверь, что x < 0 ИЛИ x > 100',
        hint: 'Оператор or',
        template: 'if x < 0 ___ x > 100:\n    print("Вне диапазона")',
        blanks: ['or'],
        blankLabels: ['оператор'],
        expected: 'if x < 0 or x > 100:\n    print("Вне диапазона")',
        xp: 20
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 4
    {
        id: 'py-26-challenge',
        module: 'Условия',
        title: '🏆 Контрольное: Проверка возраста',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Проверь возраст: >= 18 — взрослый, >= 13 — подросток, иначе — ребёнок.',
        task: 'Напиши условия для трёх возрастных групп',
        hint: 'if → elif → else',
        template: '___ age >= 18:\n    print("Взрослый")\n___ age >= 13:\n    print("Подросток")\n___:\n    print("Ребёнок")',
        blanks: ['if', 'elif', 'else'],
        blankLabels: ['если', 'иначе если', 'иначе'],
        expected: 'if age >= 18:\n    print("Взрослый")\nelif age >= 13:\n    print("Подросток")\nelse:\n    print("Ребёнок")',
        xp: 50
    },

    // ===== Module 5: Loops =====
    {
        id: 'py-27',
        module: 'Циклы',
        title: 'Цикл for',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Цикл <code>for</code> перебирает элементы последовательности.',
        task: 'Переберни элементы списка items',
        hint: 'for item in items:',
        template: '___ item in items:\n    print(item)',
        blanks: ['for'],
        blankLabels: ['оператор'],
        expected: 'for item in items:\n    print(item)',
        xp: 15
    },
    {
        id: 'py-28',
        module: 'Циклы',
        title: 'Функция range',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>range(n)</code> создаёт последовательность от 0 до n-1.',
        task: 'Создай цикл от 0 до 4',
        hint: 'range(5) даёт 0,1,2,3,4',
        template: 'for i in ___(5):\n    print(i)',
        blanks: ['range'],
        blankLabels: ['функция'],
        expected: 'for i in range(5):\n    print(i)',
        xp: 15
    },
    {
        id: 'py-29',
        module: 'Циклы',
        title: 'Цикл while',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Цикл <code>while</code> выполняется, пока условие истинно.',
        task: 'Напиши цикл while с условием x > 0',
        hint: 'while условие:',
        template: '___ x > 0:\n    x = x - 1',
        blanks: ['while'],
        blankLabels: ['оператор'],
        expected: 'while x > 0:\n    x = x - 1',
        xp: 15
    },
    {
        id: 'py-30',
        module: 'Циклы',
        title: 'Прерывание break',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>break</code> немедленно выходит из цикла.',
        task: 'Выйди из цикла при x == 5',
        hint: 'break',
        template: 'for x in range(10):\n    if x == 5:\n        ___',
        blanks: ['break'],
        blankLabels: ['оператор'],
        expected: 'for x in range(10):\n    if x == 5:\n        break',
        xp: 20
    },
    {
        id: 'py-31',
        module: 'Циклы',
        title: 'Пропуск continue',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>continue</code> пропускает текущую итерацию и переходит к следующей.',
        task: 'Пропусти чётные числа',
        hint: 'continue',
        template: 'for x in range(10):\n    if x % 2 == 0:\n        ___',
        blanks: ['continue'],
        blankLabels: ['оператор'],
        expected: 'for x in range(10):\n    if x % 2 == 0:\n        continue',
        xp: 20
    },
    {
        id: 'py-32',
        module: 'Циклы',
        title: 'Enumerate',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>enumerate()</code> возвращает индекс и элемент.',
        task: 'Получи индекс и элемент списка',
        hint: 'enumerate(list)',
        template: 'for i, item in ___(items):\n    print(i, item)',
        blanks: ['enumerate'],
        blankLabels: ['функция'],
        expected: 'for i, item in enumerate(items):\n    print(i, item)',
        xp: 20
    },
    // 🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ МОДУЛЯ 5
    {
        id: 'py-32-challenge',
        module: 'Циклы',
        title: '🏆 Контрольное: Сумма чисел',
        difficulty: 4,
        type: 'fill-blank',
        description: '<strong>🏆 КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Посчитай сумму чисел от 1 до 10.',
        task: 'Используй цикл for и range для подсчёта суммы',
        hint: 'for + range + сумма',
        template: 'total = 0\n___ i in ___(1, 11):\n    total = total + i',
        blanks: ['for', 'range'],
        blankLabels: ['цикл', 'функция'],
        expected: 'total = 0\nfor i in range(1, 11):\n    total = total + i',
        xp: 50
    },

    // ===== Module 6: Functions =====
    {
        id: 'py-33',
        module: 'Функции',
        title: 'Создание функции',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Функция создаётся ключевым словом <code>def</code>.',
        task: 'Создай функцию greet',
        hint: 'def имя_функции():',
        template: '___ greet():\n    print("Привет!")',
        blanks: ['def'],
        blankLabels: ['ключевое слово'],
        expected: 'def greet():\n    print("Привет!")',
        xp: 15
    },
    {
        id: 'py-34',
        module: 'Функции',
        title: 'Параметры',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Функция может принимать параметры в скобках.',
        task: 'Создай функцию greet с параметром name',
        hint: 'def имя(параметр):',
        template: 'def greet(___):\n    print(f"Привет, {name}!")',
        blanks: ['name'],
        blankLabels: ['параметр'],
        expected: 'def greet(name):\n    print(f"Привет, {name}!")',
        xp: 15
    },
    {
        id: 'py-35',
        module: 'Функции',
        title: 'Возврат значения',
        difficulty: 2,
        type: 'fill-blank',
        description: '<code>return</code> возвращает значение из функции.',
        task: 'Верни сумму a и b',
        hint: 'return значение',
        template: 'def add(a, b):\n    ___ a + b',
        blanks: ['return'],
        blankLabels: ['оператор'],
        expected: 'def add(a, b):\n    return a + b',
        xp: 15
    },
    {
        id: 'py-36',
        module: 'Функции',
        title: 'Вызов функции',
        difficulty: 2,
        type: 'fill-blank',
        description: 'Функция вызывается по имени с круглыми скобками.',
        task: 'Вызови функцию greet с аргументом "Мир"',
        hint: 'имя_функции(аргументы)',
        template: 'result = ___(___)',
        blanks: ['greet', '"Мир"'],
        blankLabels: ['функция', 'аргумент'],
        expected: 'result = greet("Мир")',
        xp: 15
    },
    {
        id: 'py-37',
        module: 'Функции',
        title: 'Значение по умолчанию',
        difficulty: 3,
        type: 'fill-blank',
        description: 'Параметр может иметь значение по умолчанию: <code>def func(x=10)</code>.',
        task: 'Добавь значение по умолчанию "Гость"',
        hint: 'параметр=значение',
        template: 'def greet(name___"Гость"):\n    print(f"Привет, {name}!")',
        blanks: ['='],
        blankLabels: ['оператор'],
        expected: 'def greet(name="Гость"):\n    print(f"Привет, {name}!")',
        xp: 20
    },
    {
        id: 'py-38',
        module: 'Функции',
        title: 'Lambda-функции',
        difficulty: 3,
        type: 'fill-blank',
        description: '<code>lambda</code> создаёт анонимную функцию в одну строку.',
        task: 'Создай lambda для удвоения числа',
        hint: 'lambda x: выражение',
        template: 'double = ___ x: x * 2',
        blanks: ['lambda'],
        blankLabels: ['ключевое слово'],
        expected: 'double = lambda x: x * 2',
        xp: 20
    },
    // 🏆 ФИНАЛЬНОЕ КОНТРОЛЬНОЕ ЗАДАНИЕ
    {
        id: 'py-38-challenge',
        module: 'Функции',
        title: '🏆 Финальное: Факториал',
        difficulty: 5,
        type: 'fill-blank',
        description: '<strong>🏆 ФИНАЛЬНОЕ КОНТРОЛЬНОЕ ЗАДАНИЕ</strong><br><br>Создай функцию factorial, которая возвращает факториал числа n.<br><br>🎉 Это финальное задание курса Python!',
        task: 'Напиши рекурсивную функцию факториала',
        hint: 'def, if, return, вызов себя',
        template: '___ factorial(n):\n    ___ n <= 1:\n        ___ 1\n    return n * factorial(n - 1)',
        blanks: ['def', 'if', 'return'],
        blankLabels: ['функция', 'условие', 'возврат'],
        expected: 'def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)',
        xp: 75
    }
];

// Make available globally
window.pythonLevels = pythonLevels;
