/**
 * React Course Levels
 * 45 levels covering React fundamentals to advanced patterns
 */

window.reactLevels = [
    // === Module 1: JSX Basics (Levels 1-10) ===
    {
        id: 'react-1',
        title: 'Первый компонент',
        description: 'В React компоненты - это функции, возвращающие JSX.',
        task: 'Верни JSX элемент h1 из компонента',
        type: 'fill-blank',
        template: 'function Welcome() {\n  return <[[TAG]]>Hello, React!</[[TAG]]>;\n}',
        blanks: ['h1'],
        blankLabels: ['тег'],
        hint: 'Используй тег h1 для заголовка',
        xp: 10,
        difficulty: 1
    },
    {
        id: 'react-2',
        title: 'JSX с переменной',
        description: 'В JSX можно вставлять JavaScript выражения в фигурных скобках.',
        task: 'Вставь переменную name в JSX',
        type: 'fill-blank',
        template: 'function Greeting() {\n  const name = "World";\n  return <h1>Hello, [[EXPR]]!</h1>;\n}',
        blanks: ['{name}'],
        blankLabels: ['выражение'],
        hint: 'Используй {name} для вставки переменной',
        xp: 15,
        difficulty: 1
    },
    {
        id: 'react-3',
        title: 'Атрибут className',
        description: 'В JSX вместо class используется className.',
        task: 'Добавь CSS класс к div',
        type: 'fill-blank',
        template: 'function Card() {\n  return <div [[ATTR]]="card">Content</div>;\n}',
        blanks: ['className'],
        blankLabels: ['атрибут'],
        hint: 'React использует className вместо class',
        xp: 15,
        difficulty: 1
    },
    {
        id: 'react-4',
        title: 'Инлайн стили',
        description: 'Стили в JSX передаются как объект.',
        task: 'Добавь инлайн стиль',
        type: 'fill-blank',
        template: 'function Box() {\n  return <div style=[[OPEN]]{{ backgroundColor: "blue" }}[[CLOSE]]>Box</div>;\n}',
        blanks: ['{', '}'],
        blankLabels: ['открыть', 'закрыть'],
        hint: 'Стили передаются как объект в фигурных скобках',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'react-5',
        title: 'Фрагменты',
        description: 'Fragments позволяют группировать элементы без лишнего DOM узла.',
        task: 'Используй Fragment для группировки',
        type: 'fill-blank',
        template: 'function List() {\n  return (\n    <[[TAG]]>\n      <li>Item 1</li>\n      <li>Item 2</li>\n    </[[TAG]]>\n  );\n}',
        blanks: ['>', '<'],
        blankLabels: ['открыть', 'закрыть'],
        hint: 'Короткий синтаксис Fragment: <> и </>',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'react-6',
        title: 'Условный рендеринг',
        description: 'Используй тернарный оператор для условного рендеринга.',
        task: 'Покажи разный текст в зависимости от isLoggedIn',
        type: 'fill-blank',
        template: 'function Status({ isLoggedIn }) {\n  return <p>{isLoggedIn [[OP]] "Welcome!" : "Please log in"}</p>;\n}',
        blanks: ['?'],
        blankLabels: ['оператор'],
        hint: 'Тернарный оператор: условие ? да : нет',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'react-7',
        title: 'Логический AND',
        description: '&& позволяет рендерить элемент только при true.',
        task: 'Покажи сообщение если есть unreadMessages',
        type: 'fill-blank',
        template: 'function Inbox({ unreadMessages }) {\n  return (\n    <div>\n      {unreadMessages > 0 [[OP]] <p>You have {unreadMessages} unread messages</p>}\n    </div>\n  );\n}',
        blanks: ['&&'],
        blankLabels: ['оператор'],
        hint: 'Используй && для условного рендеринга',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'react-8',
        title: 'Рендеринг списка',
        description: 'Используй map для рендеринга списка элементов.',
        task: 'Отрендери список items',
        type: 'fill-blank',
        template: 'function ItemList({ items }) {\n  return (\n    <ul>\n      {items.[[METHOD]](item => <li key={item.id}>{item.name}</li>)}\n    </ul>\n  );\n}',
        blanks: ['map'],
        blankLabels: ['метод'],
        hint: 'Используй map для преобразования массива в JSX',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'react-9',
        title: 'Key в списках',
        description: 'Каждый элемент списка должен иметь уникальный key.',
        task: 'Добавь key к элементу списка',
        type: 'fill-blank',
        template: 'function List({ users }) {\n  return users.map(user => (\n    <div [[ATTR]]={user.id}>{user.name}</div>\n  ));\n}',
        blanks: ['key'],
        blankLabels: ['атрибут'],
        hint: 'key помогает React отслеживать изменения',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'react-10',
        title: 'Обработка событий',
        description: 'События в React именуются в camelCase.',
        task: 'Добавь обработчик клика',
        type: 'fill-blank',
        template: 'function Button() {\n  function handleClick() {\n    alert("Clicked!");\n  }\n  return <button [[ATTR]]={handleClick}>Click me</button>;\n}',
        blanks: ['onClick'],
        blankLabels: ['событие'],
        hint: 'onClick - событие клика в React',
        xp: 20,
        difficulty: 2
    },

    // === Module 2: Props & State (Levels 11-20) ===
    {
        id: 'react-11',
        title: 'Props компонента',
        description: 'Props - это параметры, передаваемые компоненту.',
        task: 'Получи props в компоненте',
        type: 'fill-blank',
        template: 'function Welcome([[PARAM]]) {\n  return <h1>Hello, {props.name}!</h1>;\n}',
        blanks: ['props'],
        blankLabels: ['параметр'],
        hint: 'props - объект со всеми переданными свойствами',
        xp: 15,
        difficulty: 2
    },
    {
        id: 'react-12',
        title: 'Деструктуризация props',
        description: 'Можно деструктурировать props прямо в параметрах.',
        task: 'Деструктурируй name из props',
        type: 'fill-blank',
        template: 'function Welcome({ [[PROP]] }) {\n  return <h1>Hello, {name}!</h1>;\n}',
        blanks: ['name'],
        blankLabels: ['свойство'],
        hint: 'Извлеки name из props',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'react-13',
        title: 'Дефолтные props',
        description: 'Можно задать значения по умолчанию для props.',
        task: 'Установи дефолтное значение для name',
        type: 'fill-blank',
        template: 'function Welcome({ name [[OP]] "Guest" }) {\n  return <h1>Hello, {name}!</h1>;\n}',
        blanks: ['='],
        blankLabels: ['оператор'],
        hint: 'Используй = для значения по умолчанию',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'react-14',
        title: 'Children props',
        description: 'children - специальный prop для вложенного контента.',
        task: 'Используй children для контента',
        type: 'fill-blank',
        template: 'function Card({ [[PROP]] }) {\n  return <div className="card">{children}</div>;\n}',
        blanks: ['children'],
        blankLabels: ['свойство'],
        hint: 'children содержит вложенные элементы',
        xp: 25,
        difficulty: 2
    },
    {
        id: 'react-15',
        title: 'useState Hook',
        description: 'useState создаёт состояние в функциональном компоненте.',
        task: 'Создай состояние count',
        type: 'fill-blank',
        template: 'function Counter() {\n  const [count, setCount] = [[HOOK]](0);\n  return <p>{count}</p>;\n}',
        blanks: ['useState'],
        blankLabels: ['хук'],
        hint: 'useState возвращает [значение, функцию изменения]',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-16',
        title: 'Обновление состояния',
        description: 'Используй функцию-сеттер для обновления состояния.',
        task: 'Увеличь count на 1',
        type: 'fill-blank',
        template: 'function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => [[FUNC]](count + 1)}>\n      Count: {count}\n    </button>\n  );\n}',
        blanks: ['setCount'],
        blankLabels: ['функция'],
        hint: 'Используй setCount для обновления',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'react-17',
        title: 'Функциональное обновление',
        description: 'Для обновления на основе предыдущего значения используй функцию.',
        task: 'Обнови count функционально',
        type: 'fill-blank',
        template: 'function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount([[PARAM]] => prev + 1)}>\n      {count}\n    </button>\n  );\n}',
        blanks: ['prev'],
        blankLabels: ['параметр'],
        hint: 'Функция получает предыдущее значение',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-18',
        title: 'Состояние объекта',
        description: 'Состояние может быть объектом.',
        task: 'Создай состояние формы',
        type: 'fill-blank',
        template: 'function Form() {\n  const [form, setForm] = useState({ name: "", email: "" });\n  return (\n    <input\n      value={form.[[PROP]]}\n      onChange={e => setForm({ ...form, name: e.target.value })}\n    />\n  );\n}',
        blanks: ['name'],
        blankLabels: ['свойство'],
        hint: 'Привяжи input к form.name',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-19',
        title: 'Spread в состоянии',
        description: 'При обновлении объекта используй spread оператор.',
        task: 'Сохрани остальные свойства при обновлении',
        type: 'fill-blank',
        template: 'function Form() {\n  const [form, setForm] = useState({ name: "", email: "" });\n  const updateEmail = (email) => {\n    setForm({ [[OP]]form, email });\n  };\n}',
        blanks: ['...'],
        blankLabels: ['оператор'],
        hint: 'Spread оператор копирует существующие свойства',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'react-20',
        title: 'Передача состояния',
        description: 'Состояние можно передавать дочерним компонентам через props.',
        task: 'Передай count в дочерний компонент',
        type: 'fill-blank',
        template: 'function Parent() {\n  const [count, setCount] = useState(0);\n  return <Child [[PROP]]={count} />;\n}',
        blanks: ['count'],
        blankLabels: ['prop'],
        hint: 'Передай count как prop',
        xp: 25,
        difficulty: 3
    },

    // === Module 3: useEffect & Lifecycle (Levels 21-30) ===
    {
        id: 'react-21',
        title: 'useEffect Hook',
        description: 'useEffect выполняет side effects в компоненте.',
        task: 'Добавь useEffect для логирования',
        type: 'fill-blank',
        template: 'function Logger() {\n  [[HOOK]](() => {\n    console.log("Component rendered");\n  });\n  return <div>Check console</div>;\n}',
        blanks: ['useEffect'],
        blankLabels: ['хук'],
        hint: 'useEffect для побочных эффектов',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-22',
        title: 'Массив зависимостей',
        description: 'Пустой массив зависимостей = эффект при монтировании.',
        task: 'Выполни эффект только при монтировании',
        type: 'fill-blank',
        template: 'function FetchData() {\n  useEffect(() => {\n    fetchData();\n  }, [[DEPS]]);\n}',
        blanks: ['[]'],
        blankLabels: ['зависимости'],
        hint: 'Пустой массив [] = только при монтировании',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-23',
        title: 'Зависимость от переменной',
        description: 'Добавь переменную в массив зависимостей.',
        task: 'Перезапускай эффект при изменении userId',
        type: 'fill-blank',
        template: 'function UserData({ userId }) {\n  useEffect(() => {\n    fetchUser(userId);\n  }, [[[DEP]]]);\n}',
        blanks: ['userId'],
        blankLabels: ['зависимость'],
        hint: 'Добавь userId в массив зависимостей',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-24',
        title: 'Cleanup функция',
        description: 'Верни функцию из useEffect для очистки.',
        task: 'Добавь cleanup для отписки',
        type: 'fill-blank',
        template: 'function Timer() {\n  useEffect(() => {\n    const id = setInterval(() => {}, 1000);\n    [[KEYWORD]] () => clearInterval(id);\n  }, []);\n}',
        blanks: ['return'],
        blankLabels: ['ключевое слово'],
        hint: 'return возвращает cleanup функцию',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'react-25',
        title: 'Fetch данных',
        description: 'Используй useEffect для загрузки данных.',
        task: 'Загрузи данные при монтировании',
        type: 'fill-blank',
        template: 'function Posts() {\n  const [posts, setPosts] = useState([]);\n  \n  useEffect(() => {\n    [[METHOD]]("/api/posts")\n      .then(res => res.json())\n      .then(data => setPosts(data));\n  }, []);\n}',
        blanks: ['fetch'],
        blankLabels: ['функция'],
        hint: 'fetch для HTTP запросов',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'react-26',
        title: 'useRef Hook',
        description: 'useRef создаёт мутируемую ссылку.',
        task: 'Создай ref для input элемента',
        type: 'fill-blank',
        template: 'function FocusInput() {\n  const inputRef = [[HOOK]](null);\n  return <input ref={inputRef} />;\n}',
        blanks: ['useRef'],
        blankLabels: ['хук'],
        hint: 'useRef для создания ссылки на DOM',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-27',
        title: 'Доступ к DOM через ref',
        description: 'ref.current содержит DOM элемент.',
        task: 'Сфокусируй input при клике',
        type: 'fill-blank',
        template: 'function FocusInput() {\n  const inputRef = useRef(null);\n  const handleClick = () => inputRef.[[PROP]].focus();\n  return (\n    <>\n      <input ref={inputRef} />\n      <button onClick={handleClick}>Focus</button>\n    </>\n  );\n}',
        blanks: ['current'],
        blankLabels: ['свойство'],
        hint: 'current содержит DOM элемент',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-28',
        title: 'useMemo Hook',
        description: 'useMemo кеширует вычисленное значение.',
        task: 'Мемоизируй дорогое вычисление',
        type: 'fill-blank',
        template: 'function ExpensiveComponent({ items }) {\n  const total = [[HOOK]](() => {\n    return items.reduce((sum, item) => sum + item.price, 0);\n  }, [items]);\n}',
        blanks: ['useMemo'],
        blankLabels: ['хук'],
        hint: 'useMemo кеширует результат функции',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'react-29',
        title: 'useCallback Hook',
        description: 'useCallback кеширует функцию.',
        task: 'Мемоизируй callback функцию',
        type: 'fill-blank',
        template: 'function Parent() {\n  const [count, setCount] = useState(0);\n  const increment = [[HOOK]](() => {\n    setCount(c => c + 1);\n  }, []);\n}',
        blanks: ['useCallback'],
        blankLabels: ['хук'],
        hint: 'useCallback кеширует функцию между рендерами',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'react-30',
        title: 'Custom Hook',
        description: 'Создай свой хук для переиспользования логики.',
        task: 'Назови кастомный хук правильно',
        type: 'fill-blank',
        template: 'function [[NAME]](initialValue) {\n  const [value, setValue] = useState(initialValue);\n  const toggle = () => setValue(v => !v);\n  return [value, toggle];\n}',
        blanks: ['useToggle'],
        blankLabels: ['имя'],
        hint: 'Кастомные хуки начинаются с use',
        xp: 40,
        difficulty: 4
    },

    // === Module 4: Context & Forms (Levels 31-40) ===
    {
        id: 'react-31',
        title: 'Создание Context',
        description: 'Context позволяет передавать данные без prop drilling.',
        task: 'Создай контекст темы',
        type: 'fill-blank',
        template: 'const ThemeContext = [[METHOD]]("light");',
        blanks: ['createContext'],
        blankLabels: ['метод'],
        hint: 'createContext создаёт контекст',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-32',
        title: 'Context Provider',
        description: 'Provider предоставляет значение контекста.',
        task: 'Оберни компоненты в Provider',
        type: 'fill-blank',
        template: 'function App() {\n  return (\n    <ThemeContext.[[COMPONENT]] value="dark">\n      <Main />\n    </ThemeContext.[[COMPONENT]]>\n  );\n}',
        blanks: ['Provider'],
        blankLabels: ['компонент'],
        hint: 'Provider передаёт value потомкам',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-33',
        title: 'useContext Hook',
        description: 'useContext читает значение из контекста.',
        task: 'Получи значение темы',
        type: 'fill-blank',
        template: 'function ThemedButton() {\n  const theme = [[HOOK]](ThemeContext);\n  return <button className={theme}>Click</button>;\n}',
        blanks: ['useContext'],
        blankLabels: ['хук'],
        hint: 'useContext читает значение контекста',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-34',
        title: 'Controlled Input',
        description: 'Controlled input привязан к состоянию.',
        task: 'Привяжи input к состоянию',
        type: 'fill-blank',
        template: 'function Form() {\n  const [name, setName] = useState("");\n  return (\n    <input\n      [[ATTR]]={name}\n      onChange={e => setName(e.target.value)}\n    />\n  );\n}',
        blanks: ['value'],
        blankLabels: ['атрибут'],
        hint: 'value привязывает input к состоянию',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'react-35',
        title: 'Обработка формы',
        description: 'Обработай submit формы.',
        task: 'Предотврати перезагрузку страницы',
        type: 'fill-blank',
        template: 'function Form() {\n  const handleSubmit = (e) => {\n    e.[[METHOD]]();\n    // отправка данных\n  };\n  return <form onSubmit={handleSubmit}>...</form>;\n}',
        blanks: ['preventDefault'],
        blankLabels: ['метод'],
        hint: 'preventDefault отменяет действие по умолчанию',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'react-36',
        title: 'useReducer Hook',
        description: 'useReducer для сложной логики состояния.',
        task: 'Используй useReducer',
        type: 'fill-blank',
        template: 'function Counter() {\n  const [state, dispatch] = [[HOOK]](reducer, { count: 0 });\n  return (\n    <button onClick={() => dispatch({ type: "increment" })}>\n      {state.count}\n    </button>\n  );\n}',
        blanks: ['useReducer'],
        blankLabels: ['хук'],
        hint: 'useReducer принимает reducer и начальное состояние',
        xp: 40,
        difficulty: 4
    },
    {
        id: 'react-37',
        title: 'Reducer функция',
        description: 'Reducer принимает state и action, возвращает новый state.',
        task: 'Верни новое состояние из reducer',
        type: 'fill-blank',
        template: 'function reducer(state, action) {\n  switch (action.type) {\n    case "increment":\n      [[KEYWORD]] { count: state.count + 1 };\n    default:\n      return state;\n  }\n}',
        blanks: ['return'],
        blankLabels: ['ключевое слово'],
        hint: 'Reducer должен вернуть новое состояние',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'react-38',
        title: 'Multiple inputs',
        description: 'Управляй несколькими inputs одним состоянием.',
        task: 'Используй name атрибут для идентификации',
        type: 'fill-blank',
        template: 'function Form() {\n  const [form, setForm] = useState({ name: "", email: "" });\n  const handleChange = (e) => {\n    setForm({ ...form, [e.target.[[PROP]]]: e.target.value });\n  };\n}',
        blanks: ['name'],
        blankLabels: ['свойство'],
        hint: 'Используй name для динамического ключа',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-39',
        title: 'Валидация формы',
        description: 'Добавь простую валидацию.',
        task: 'Проверь что поле не пустое',
        type: 'fill-blank',
        template: 'function Form() {\n  const [email, setEmail] = useState("");\n  const [error, setError] = useState("");\n  \n  const validate = () => {\n    if (email.[[METHOD]] === 0) {\n      setError("Email required");\n      return false;\n    }\n    return true;\n  };\n}',
        blanks: ['length'],
        blankLabels: ['свойство'],
        hint: 'Проверь длину строки',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'react-40',
        title: 'Отображение ошибок',
        description: 'Покажи ошибку валидации пользователю.',
        task: 'Условно отрендери сообщение об ошибке',
        type: 'fill-blank',
        template: 'function Form() {\n  const [error, setError] = useState("");\n  return (\n    <div>\n      <input />\n      {error [[OP]] <p className="error">{error}</p>}\n    </div>\n  );\n}',
        blanks: ['&&'],
        blankLabels: ['оператор'],
        hint: 'Используй && для условного рендеринга',
        xp: 25,
        difficulty: 3
    },

    // === Module 5: Advanced Patterns (Levels 41-45) ===
    {
        id: 'react-41',
        title: 'Render Props',
        description: 'Render props - паттерн передачи функции рендеринга.',
        task: 'Используй render prop',
        type: 'fill-blank',
        template: 'function MouseTracker({ [[PROP]] }) {\n  const [position, setPosition] = useState({ x: 0, y: 0 });\n  return render(position);\n}',
        blanks: ['render'],
        blankLabels: ['prop'],
        hint: 'render prop - функция для рендеринга',
        xp: 40,
        difficulty: 4
    },
    {
        id: 'react-42',
        title: 'Higher-Order Component',
        description: 'HOC - функция, принимающая и возвращающая компонент.',
        task: 'Создай HOC',
        type: 'fill-blank',
        template: 'function withLogger([[PARAM]]) {\n  return function LoggedComponent(props) {\n    useEffect(() => console.log("Rendered"), []);\n    return <Component {...props} />;\n  };\n}',
        blanks: ['Component'],
        blankLabels: ['параметр'],
        hint: 'HOC принимает компонент как аргумент',
        xp: 45,
        difficulty: 5
    },
    {
        id: 'react-43',
        title: 'React.memo',
        description: 'memo предотвращает ненужные перерендеры.',
        task: 'Мемоизируй компонент',
        type: 'fill-blank',
        template: 'const ExpensiveList = React.[[METHOD]](function List({ items }) {\n  return items.map(item => <div key={item.id}>{item.name}</div>);\n});',
        blanks: ['memo'],
        blankLabels: ['метод'],
        hint: 'React.memo кеширует компонент',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'react-44',
        title: 'Lazy Loading',
        description: 'Lazy загружает компонент по требованию.',
        task: 'Создай lazy компонент',
        type: 'fill-blank',
        template: 'const HeavyComponent = React.[[METHOD]](() => import("./HeavyComponent"));',
        blanks: ['lazy'],
        blankLabels: ['метод'],
        hint: 'React.lazy для code splitting',
        xp: 40,
        difficulty: 4
    },
    {
        id: 'react-45',
        title: 'Error Boundary',
        description: 'Error boundaries ловят ошибки в дочерних компонентах.',
        task: 'Реализуй метод для отлова ошибок',
        type: 'fill-blank',
        template: 'class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  \n  static [[METHOD]](error) {\n    return { hasError: true };\n  }\n  \n  render() {\n    if (this.state.hasError) return <h1>Error!</h1>;\n    return this.props.children;\n  }\n}',
        blanks: ['getDerivedStateFromError'],
        blankLabels: ['метод'],
        hint: 'getDerivedStateFromError вызывается при ошибке',
        xp: 45,
        difficulty: 5
    }
];
