/**
 * TypeScript Course Levels
 * 50 levels covering TypeScript basics to advanced concepts
 */

window.tsLevels = [
    // === Module 1: TypeScript Basics (Levels 1-10) ===
    {
        id: 'ts-1',
        module: 'Основы TypeScript',
        title: 'Первый тип',
        description: 'TypeScript добавляет типы в JavaScript. Давай начнём с простого - укажем тип переменной.',
        task: 'Укажи тип string для переменной name',
        type: 'fill-blank',
        template: 'let name: [[TYPE]] = "CodeQuest";',
        blanks: ['string'],
        blankLabels: ['тип'],
        hint: 'Для строк используется тип string',
        xp: 10,
        difficulty: 1
    },
    {
        id: 'ts-2',
        module: 'Основы TypeScript',
        title: 'Числовой тип',
        description: 'Для чисел в TypeScript используется тип number.',
        task: 'Укажи тип number для переменной age',
        type: 'fill-blank',
        template: 'let age: [[TYPE]] = 25;',
        blanks: ['number'],
        blankLabels: ['тип'],
        hint: 'Все числа (целые и дробные) имеют тип number',
        xp: 10,
        difficulty: 1
    },
    {
        id: 'ts-3',
        module: 'Основы TypeScript',
        title: 'Логический тип',
        description: 'Boolean - это тип для значений true и false.',
        task: 'Укажи тип boolean для переменной isActive',
        type: 'fill-blank',
        template: 'let isActive: [[TYPE]] = true;',
        blanks: ['boolean'],
        blankLabels: ['тип'],
        hint: 'Для логических значений используется boolean',
        xp: 10,
        difficulty: 1
    },
    {
        id: 'ts-4',
        module: 'Основы TypeScript',
        title: 'Массив строк',
        description: 'Массивы в TypeScript могут быть типизированы.',
        task: 'Укажи тип массива строк',
        type: 'fill-blank',
        template: 'let names: [[TYPE]][] = ["Alice", "Bob"];',
        blanks: ['string'],
        blankLabels: ['тип'],
        hint: 'Используй string[] для массива строк',
        xp: 15,
        difficulty: 1
    },
    {
        id: 'ts-5',
        module: 'Основы TypeScript',
        title: 'Массив чисел',
        description: 'Аналогично создаём массив чисел.',
        task: 'Укажи тип массива чисел',
        type: 'fill-blank',
        template: 'let scores: [[TYPE]][] = [100, 95, 88];',
        blanks: ['number'],
        blankLabels: ['тип'],
        hint: 'Используй number[] для массива чисел',
        xp: 15,
        difficulty: 1
    },
    {
        id: 'ts-6',
        module: 'Основы TypeScript',
        title: 'Функция с типами',
        description: 'Функции тоже могут иметь типы параметров и возвращаемого значения.',
        task: 'Укажи тип параметра и возвращаемого значения',
        type: 'fill-blank',
        template: 'function greet(name: [[TYPE1]]): [[TYPE2]] {\n  return "Hello, " + name;\n}',
        blanks: ['string', 'string'],
        blankLabels: ['тип параметра', 'тип возврата'],
        hint: 'name - строка, и функция возвращает строку',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-7',
        module: 'Основы TypeScript',
        title: 'Функция без возврата',
        description: 'Если функция ничего не возвращает, используется тип void.',
        task: 'Укажи тип void для функции',
        type: 'fill-blank',
        template: 'function logMessage(msg: string): [[TYPE]] {\n  console.log(msg);\n}',
        blanks: ['void'],
        blankLabels: ['тип'],
        hint: 'void означает отсутствие возвращаемого значения',
        xp: 15,
        difficulty: 2
    },
    {
        id: 'ts-8',
        module: 'Основы TypeScript',
        title: 'Объединение типов',
        description: 'Union types позволяют переменной быть одним из нескольких типов.',
        task: 'Создай тип, который может быть string или number',
        type: 'fill-blank',
        template: 'let id: string [[OP]] number = "abc123";',
        blanks: ['|'],
        blankLabels: ['оператор'],
        hint: 'Используй символ | для объединения типов',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-9',
        module: 'Основы TypeScript',
        title: 'Тип any',
        description: 'Тип any отключает проверку типов (использовать осторожно!).',
        task: 'Укажи тип any для динамической переменной',
        type: 'fill-blank',
        template: 'let data: [[TYPE]] = fetchFromAPI();',
        blanks: ['any'],
        blankLabels: ['тип'],
        hint: 'any позволяет присвоить любое значение',
        xp: 15,
        difficulty: 2
    },
    {
        id: 'ts-10',
        module: 'Основы TypeScript',
        title: 'Тип unknown',
        description: 'Unknown - более безопасная альтернатива any.',
        task: 'Укажи тип unknown',
        type: 'fill-blank',
        template: 'let userInput: [[TYPE]];\n// Перед использованием нужна проверка типа',
        blanks: ['unknown'],
        blankLabels: ['тип'],
        hint: 'unknown требует проверки типа перед использованием',
        xp: 20,
        difficulty: 2
    },

    // === Module 2: Interfaces (Levels 11-20) ===
    {
        id: 'ts-11',
        module: 'Интерфейсы',
        title: 'Первый интерфейс',
        description: 'Интерфейсы описывают структуру объектов.',
        task: 'Создай интерфейс User с полем name',
        type: 'fill-blank',
        template: '[[KEYWORD]] User {\n  name: string;\n}',
        blanks: ['interface'],
        blankLabels: ['ключевое слово'],
        hint: 'Используй ключевое слово interface',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-12',
        module: 'Интерфейсы',
        title: 'Несколько полей',
        description: 'Интерфейс может содержать несколько полей разных типов.',
        task: 'Добавь поле age типа number',
        type: 'fill-blank',
        template: 'interface User {\n  name: string;\n  age: [[TYPE]];\n}',
        blanks: ['number'],
        blankLabels: ['тип'],
        hint: 'Возраст - это число',
        xp: 15,
        difficulty: 2
    },
    {
        id: 'ts-13',
        module: 'Интерфейсы',
        title: 'Опциональные поля',
        description: 'Поля со знаком ? являются необязательными.',
        task: 'Сделай поле email опциональным',
        type: 'fill-blank',
        template: 'interface User {\n  name: string;\n  email[[MARK]]: string;\n}',
        blanks: ['?'],
        blankLabels: ['символ'],
        hint: 'Добавь ? перед двоеточием',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-14',
        module: 'Интерфейсы',
        title: 'Readonly поля',
        description: 'Readonly поля нельзя изменить после создания.',
        task: 'Сделай поле id только для чтения',
        type: 'fill-blank',
        template: 'interface User {\n  [[KEYWORD]] id: number;\n  name: string;\n}',
        blanks: ['readonly'],
        blankLabels: ['модификатор'],
        hint: 'Используй ключевое слово readonly',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-15',
        module: 'Интерфейсы',
        title: 'Методы в интерфейсе',
        description: 'Интерфейсы могут описывать методы объекта.',
        task: 'Опиши метод greet, возвращающий string',
        type: 'fill-blank',
        template: 'interface User {\n  name: string;\n  greet(): [[TYPE]];\n}',
        blanks: ['string'],
        blankLabels: ['тип возврата'],
        hint: 'Метод greet возвращает строку приветствия',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-16',
        module: 'Интерфейсы',
        title: 'Расширение интерфейсов',
        description: 'Интерфейсы могут расширять другие интерфейсы.',
        task: 'Расширь интерфейс User',
        type: 'fill-blank',
        template: 'interface Admin [[KEYWORD]] User {\n  adminLevel: number;\n}',
        blanks: ['extends'],
        blankLabels: ['ключевое слово'],
        hint: 'Используй extends для наследования',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'ts-17',
        module: 'Интерфейсы',
        title: 'Индексные сигнатуры',
        description: 'Index signatures позволяют описать объект с динамическими ключами.',
        task: 'Создай интерфейс словаря',
        type: 'fill-blank',
        template: 'interface Dictionary {\n  [key: [[TYPE]]]: string;\n}',
        blanks: ['string'],
        blankLabels: ['тип ключа'],
        hint: 'Ключи словаря обычно строки',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'ts-18',
        module: 'Интерфейсы',
        title: 'Интерфейс функции',
        description: 'Интерфейсы могут описывать функции.',
        task: 'Опиши функцию сложения',
        type: 'fill-blank',
        template: 'interface AddFunc {\n  (a: number, b: number): [[TYPE]];\n}',
        blanks: ['number'],
        blankLabels: ['тип возврата'],
        hint: 'Сложение двух чисел даёт число',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'ts-19',
        module: 'Интерфейсы',
        title: 'Множественное наследование',
        description: 'Интерфейс может расширять несколько интерфейсов.',
        task: 'Расширь два интерфейса',
        type: 'fill-blank',
        template: 'interface SuperUser extends User[[COMMA]] Admin {\n  superPower: string;\n}',
        blanks: [','],
        blankLabels: ['разделитель'],
        hint: 'Используй запятую для перечисления',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'ts-20',
        module: 'Интерфейсы',
        title: 'Использование интерфейса',
        description: 'Применим интерфейс к объекту.',
        task: 'Укажи тип интерфейса User',
        type: 'fill-blank',
        template: 'const user: [[TYPE]] = {\n  name: "John",\n  age: 30\n};',
        blanks: ['User'],
        blankLabels: ['интерфейс'],
        hint: 'Используй имя интерфейса как тип',
        xp: 20,
        difficulty: 2
    },

    // === Module 3: Type Aliases & Generics (Levels 21-30) ===
    {
        id: 'ts-21',
        module: 'Type Aliases и Generics',
        title: 'Type Alias',
        description: 'Type alias создаёт псевдоним для типа.',
        task: 'Создай псевдоним типа ID',
        type: 'fill-blank',
        template: '[[KEYWORD]] ID = string | number;',
        blanks: ['type'],
        blankLabels: ['ключевое слово'],
        hint: 'Используй ключевое слово type',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-22',
        module: 'Type Aliases и Generics',
        title: 'Тип объекта',
        description: 'Type alias также может описывать объекты.',
        task: 'Создай тип Point',
        type: 'fill-blank',
        template: 'type Point = {\n  x: [[TYPE]];\n  y: number;\n};',
        blanks: ['number'],
        blankLabels: ['тип'],
        hint: 'Координаты - это числа',
        xp: 15,
        difficulty: 2
    },
    {
        id: 'ts-23',
        module: 'Type Aliases и Generics',
        title: 'Литеральные типы',
        description: 'Литеральные типы ограничивают значения конкретными вариантами.',
        task: 'Создай тип для направления',
        type: 'fill-blank',
        template: 'type Direction = "left" | "right" | "up" | "[[VALUE]]";',
        blanks: ['down'],
        blankLabels: ['значение'],
        hint: 'Четвёртое направление - вниз',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-24',
        module: 'Type Aliases и Generics',
        title: 'Первый Generic',
        description: 'Generics позволяют создавать переиспользуемые компоненты.',
        task: 'Создай generic функцию identity',
        type: 'fill-blank',
        template: 'function identity<[[T]]>(arg: T): T {\n  return arg;\n}',
        blanks: ['T'],
        blankLabels: ['параметр типа'],
        hint: 'T - стандартное имя для generic параметра',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'ts-25',
        module: 'Type Aliases и Generics',
        title: 'Generic массив',
        description: 'Используем generic для массива.',
        task: 'Укажи тип generic массива',
        type: 'fill-blank',
        template: 'function getFirst<T>(arr: [[TYPE]]): T {\n  return arr[0];\n}',
        blanks: ['T[]'],
        blankLabels: ['тип массива'],
        hint: 'Массив элементов типа T записывается как T[]',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'ts-26',
        module: 'Type Aliases и Generics',
        title: 'Generic интерфейс',
        description: 'Интерфейсы тоже могут быть generic.',
        task: 'Создай generic интерфейс Box',
        type: 'fill-blank',
        template: 'interface Box<[[T]]> {\n  value: T;\n}',
        blanks: ['T'],
        blankLabels: ['параметр типа'],
        hint: 'Добавь параметр типа T',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'ts-27',
        module: 'Type Aliases и Generics',
        title: 'Ограничение Generic',
        description: 'Constraints ограничивают возможные типы generic.',
        task: 'Ограничь T объектами с length',
        type: 'fill-blank',
        template: 'function logLength<T [[KEYWORD]] { length: number }>(arg: T): void {\n  console.log(arg.length);\n}',
        blanks: ['extends'],
        blankLabels: ['ключевое слово'],
        hint: 'Используй extends для ограничения',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'ts-28',
        module: 'Type Aliases и Generics',
        title: 'Несколько Generic',
        description: 'Функция может иметь несколько generic параметров.',
        task: 'Добавь второй параметр типа',
        type: 'fill-blank',
        template: 'function pair<T, [[U]]>(first: T, second: U): [T, U] {\n  return [first, second];\n}',
        blanks: ['U'],
        blankLabels: ['второй параметр'],
        hint: 'Используй U для второго параметра типа',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'ts-29',
        module: 'Type Aliases и Generics',
        title: 'keyof оператор',
        description: 'keyof возвращает объединение ключей типа.',
        task: 'Используй keyof для получения ключей',
        type: 'fill-blank',
        template: 'type UserKeys = [[KEYWORD]] User;',
        blanks: ['keyof'],
        blankLabels: ['оператор'],
        hint: 'keyof возвращает тип ключей объекта',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'ts-30',
        module: 'Type Aliases и Generics',
        title: 'typeof оператор',
        description: 'typeof в контексте типов получает тип переменной.',
        task: 'Получи тип переменной user',
        type: 'fill-blank',
        template: 'const user = { name: "John", age: 30 };\ntype UserType = [[KEYWORD]] user;',
        blanks: ['typeof'],
        blankLabels: ['оператор'],
        hint: 'typeof извлекает тип из значения',
        xp: 35,
        difficulty: 4
    },

    // === Module 4: Classes (Levels 31-40) ===
    {
        id: 'ts-31',
        module: 'Классы',
        title: 'Класс с типами',
        description: 'Классы в TypeScript поддерживают типизацию свойств.',
        task: 'Укажи тип свойства name',
        type: 'fill-blank',
        template: 'class Person {\n  name: [[TYPE]];\n  \n  constructor(name: string) {\n    this.name = name;\n  }\n}',
        blanks: ['string'],
        blankLabels: ['тип'],
        hint: 'name - это строка',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-32',
        module: 'Классы',
        title: 'Модификатор public',
        description: 'Public - доступ отовсюду (по умолчанию).',
        task: 'Укажи модификатор public',
        type: 'fill-blank',
        template: 'class Person {\n  [[MOD]] name: string;\n}',
        blanks: ['public'],
        blankLabels: ['модификатор'],
        hint: 'public - открытый доступ',
        xp: 20,
        difficulty: 2
    },
    {
        id: 'ts-33',
        module: 'Классы',
        title: 'Модификатор private',
        description: 'Private - доступ только внутри класса.',
        task: 'Сделай поле приватным',
        type: 'fill-blank',
        template: 'class BankAccount {\n  [[MOD]] balance: number = 0;\n}',
        blanks: ['private'],
        blankLabels: ['модификатор'],
        hint: 'private скрывает поле от внешнего доступа',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'ts-34',
        module: 'Классы',
        title: 'Модификатор protected',
        description: 'Protected - доступ в классе и наследниках.',
        task: 'Используй protected для наследуемого поля',
        type: 'fill-blank',
        template: 'class Animal {\n  [[MOD]] name: string;\n}',
        blanks: ['protected'],
        blankLabels: ['модификатор'],
        hint: 'protected доступен в подклассах',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'ts-35',
        module: 'Классы',
        title: 'Сокращённый конструктор',
        description: 'TypeScript позволяет объявлять свойства прямо в конструкторе.',
        task: 'Объяви свойство в параметре конструктора',
        type: 'fill-blank',
        template: 'class Person {\n  constructor([[MOD]] name: string) {}\n}',
        blanks: ['public'],
        blankLabels: ['модификатор'],
        hint: 'Добавь модификатор перед параметром',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'ts-36',
        module: 'Классы',
        title: 'Readonly в классе',
        description: 'Readonly свойства можно установить только в конструкторе.',
        task: 'Сделай id только для чтения',
        type: 'fill-blank',
        template: 'class User {\n  [[MOD]] id: number;\n  \n  constructor(id: number) {\n    this.id = id;\n  }\n}',
        blanks: ['readonly'],
        blankLabels: ['модификатор'],
        hint: 'readonly запрещает изменение после инициализации',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'ts-37',
        module: 'Классы',
        title: 'Геттеры и сеттеры',
        description: 'Accessors позволяют контролировать доступ к свойствам.',
        task: 'Создай геттер для fullName',
        type: 'fill-blank',
        template: 'class Person {\n  firstName: string;\n  lastName: string;\n  \n  [[KEYWORD]] fullName(): string {\n    return this.firstName + " " + this.lastName;\n  }\n}',
        blanks: ['get'],
        blankLabels: ['ключевое слово'],
        hint: 'get создаёт геттер',
        xp: 30,
        difficulty: 3
    },
    {
        id: 'ts-38',
        module: 'Классы',
        title: 'Статические свойства',
        description: 'Static свойства принадлежат классу, а не экземплярам.',
        task: 'Создай статическое свойство',
        type: 'fill-blank',
        template: 'class Counter {\n  [[KEYWORD]] count: number = 0;\n}',
        blanks: ['static'],
        blankLabels: ['ключевое слово'],
        hint: 'static делает свойство статическим',
        xp: 25,
        difficulty: 3
    },
    {
        id: 'ts-39',
        module: 'Классы',
        title: 'Абстрактный класс',
        description: 'Абстрактные классы не могут быть созданы напрямую.',
        task: 'Сделай класс абстрактным',
        type: 'fill-blank',
        template: '[[KEYWORD]] class Shape {\n  abstract getArea(): number;\n}',
        blanks: ['abstract'],
        blankLabels: ['ключевое слово'],
        hint: 'abstract создаёт абстрактный класс',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'ts-40',
        module: 'Классы',
        title: 'Реализация интерфейса',
        description: 'Класс может реализовывать интерфейс.',
        task: 'Реализуй интерфейс Printable',
        type: 'fill-blank',
        template: 'class Document [[KEYWORD]] Printable {\n  print(): void {\n    console.log("Printing...");\n  }\n}',
        blanks: ['implements'],
        blankLabels: ['ключевое слово'],
        hint: 'implements связывает класс с интерфейсом',
        xp: 30,
        difficulty: 3
    },

    // === Module 5: Advanced Types (Levels 41-50) ===
    {
        id: 'ts-41',
        module: 'Продвинутые типы',
        title: 'Utility Type: Partial',
        description: 'Partial делает все свойства опциональными.',
        task: 'Используй Partial для частичного обновления',
        type: 'fill-blank',
        template: 'function updateUser(user: User, updates: [[TYPE]]<User>): User {\n  return { ...user, ...updates };\n}',
        blanks: ['Partial'],
        blankLabels: ['утилита'],
        hint: 'Partial<T> делает все поля T опциональными',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'ts-42',
        module: 'Продвинутые типы',
        title: 'Utility Type: Required',
        description: 'Required делает все свойства обязательными.',
        task: 'Используй Required',
        type: 'fill-blank',
        template: 'type CompleteUser = [[TYPE]]<User>;',
        blanks: ['Required'],
        blankLabels: ['утилита'],
        hint: 'Required<T> убирает опциональность',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'ts-43',
        module: 'Продвинутые типы',
        title: 'Utility Type: Pick',
        description: 'Pick выбирает определённые свойства из типа.',
        task: 'Выбери только name и email',
        type: 'fill-blank',
        template: 'type UserContact = [[TYPE]]<User, "name" | "email">;',
        blanks: ['Pick'],
        blankLabels: ['утилита'],
        hint: 'Pick<T, K> выбирает ключи K из T',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'ts-44',
        module: 'Продвинутые типы',
        title: 'Utility Type: Omit',
        description: 'Omit исключает указанные свойства.',
        task: 'Исключи поле password',
        type: 'fill-blank',
        template: 'type PublicUser = [[TYPE]]<User, "password">;',
        blanks: ['Omit'],
        blankLabels: ['утилита'],
        hint: 'Omit<T, K> исключает ключи K из T',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'ts-45',
        module: 'Продвинутые типы',
        title: 'Utility Type: Record',
        description: 'Record создаёт тип объекта с указанными ключами.',
        task: 'Создай тип записи',
        type: 'fill-blank',
        template: 'type PageViews = [[TYPE]]<string, number>;',
        blanks: ['Record'],
        blankLabels: ['утилита'],
        hint: 'Record<K, V> создаёт объект с ключами K и значениями V',
        xp: 35,
        difficulty: 4
    },
    {
        id: 'ts-46',
        module: 'Продвинутые типы',
        title: 'Условные типы',
        description: 'Conditional types позволяют выбирать тип по условию.',
        task: 'Заверши условный тип',
        type: 'fill-blank',
        template: 'type IsString<T> = T extends string ? [[TRUE]] : false;',
        blanks: ['true'],
        blankLabels: ['значение'],
        hint: 'Если T extends string, возвращаем true',
        xp: 40,
        difficulty: 5
    },
    {
        id: 'ts-47',
        module: 'Продвинутые типы',
        title: 'Mapped Types',
        description: 'Mapped types трансформируют существующие типы.',
        task: 'Создай тип с readonly свойствами',
        type: 'fill-blank',
        template: 'type Readonly<T> = {\n  [[MOD]] [P in keyof T]: T[P];\n};',
        blanks: ['readonly'],
        blankLabels: ['модификатор'],
        hint: 'Добавляем readonly к каждому свойству',
        xp: 45,
        difficulty: 5
    },
    {
        id: 'ts-48',
        module: 'Продвинутые типы',
        title: 'Template Literal Types',
        description: 'Template literals работают и с типами.',
        task: 'Создай тип события',
        type: 'fill-blank',
        template: 'type EventName = [[TEMPLATE]]on${Capitalize<string>}[[TEMPLATE]];',
        blanks: ['`', '`'],
        blankLabels: ['открыть', 'закрыть'],
        hint: 'Используй обратные кавычки для template literal',
        xp: 45,
        difficulty: 5
    },
    {
        id: 'ts-49',
        module: 'Продвинутые типы',
        title: 'Infer в условных типах',
        description: 'infer позволяет извлекать типы внутри условий.',
        task: 'Извлеки тип возврата функции',
        type: 'fill-blank',
        template: 'type ReturnType<T> = T extends (...args: any[]) => [[KEYWORD]] R ? R : never;',
        blanks: ['infer'],
        blankLabels: ['ключевое слово'],
        hint: 'infer R извлекает тип R',
        xp: 50,
        difficulty: 5
    },
    {
        id: 'ts-50',
        module: 'Продвинутые типы',
        title: 'Type Guard',
        description: 'Type guards сужают типы в условиях.',
        task: 'Создай функцию-guard для string',
        type: 'fill-blank',
        template: 'function isString(value: unknown): value [[KEYWORD]] string {\n  return typeof value === "string";\n}',
        blanks: ['is'],
        blankLabels: ['ключевое слово'],
        hint: 'is указывает, что функция - type guard',
        xp: 45,
        difficulty: 5
    }
];
